-- Dados sintéticos; reverte títulos, contas, extratos e conciliações ao terminar.
begin;
select set_config('request.jwt.claim.sub',(select user_id::text from public.fc_perfis where perfil='MASTER' and ativo and status_aprovacao='APROVADO' limit 1),true);
create temporary table bank_results(name text,ok boolean,detail text);
grant all on bank_results to authenticated,anon;
create function pg_temp.check(p_name text,p_ok boolean,p_detail text default '') returns void language sql as $$insert into bank_results values(p_name,coalesce(p_ok,false),p_detail);$$;
create function pg_temp.reject(p_name text,p_sql text,p_pattern text default 'inválid|limite|precisão|obrigat|inconsistente|imutável|conteúdo diferente|já |supera|maior|incompatível|mudou|não encontr|encerrado|denied|aprovado|ausente|anterior|diferentes|duas casas') returns void language plpgsql as $$
begin begin execute p_sql;raise exception 'ACEITO INDEVIDAMENTE' using errcode='PT001';exception when sqlstate 'PT001' then insert into bank_results values(p_name,false,'ACEITO INDEVIDAMENTE');when others then insert into bank_results values(p_name,sqlerrm ~* p_pattern,sqlerrm);end;end;$$;
create temporary table bank_vars(a uuid,b uuid,m uuid,m2 uuid,request uuid default gen_random_uuid(),receipt uuid,second uuid,normal uuid default gen_random_uuid(),normal_r uuid default gen_random_uuid());
grant all on bank_vars to authenticated,anon;
insert into bank_vars default values;
update public.fc_app_state set versao=versao+1,estado=estado||'{"contasPagar":[{"id":"P-SIM","valor":1000,"status":"ABERTO"}],"contasReceber":[{"id":"R-SIM","valor":1000,"status":"ABERTO"}]}' where empresa_id=public.fc_current_empresa_id();
insert into public.fc_clientes(id,empresa_id,documento,razao_social) select normal_r,public.fc_current_empresa_id(),'11144477735','CLIENTE SINTÉTICO SIM' from bank_vars;
insert into public.fc_contas_pagar(id,empresa_id,unidade_id,descricao,vencimento,valor,saldo,status) select normal,public.fc_current_empresa_id(),(select id from public.fc_unidades where empresa_id=public.fc_current_empresa_id() limit 1),'Pagar normalizado SIM','2026-10-03',800,800,'ABERTO' from bank_vars;
insert into public.fc_contas_receber(id,empresa_id,unidade_id,cliente_id,descricao,vencimento,valor,saldo,status) select normal_r,public.fc_current_empresa_id(),(select id from public.fc_unidades where empresa_id=public.fc_current_empresa_id() limit 1),normal_r,'Receber normalizado SIM','2026-10-03',500,500,'ABERTO' from bank_vars;
set local role authenticated;
update bank_vars set a=(public.fc_banco_criar_conta('{"nome":"Conta A SIM","banco":"SIM A","agencia":"0001","numero":"SIM-A","data":"2026-10-01","saldo":"1000"}')->>'contaId')::uuid;
update bank_vars set b=(public.fc_banco_criar_conta('{"nome":"Conta B SIM","banco":"SIM B","agencia":"0002","numero":"SIM-B","data":"2026-10-01","saldo":"200"}')->>'contaId')::uuid;
select pg_temp.check('Conta repetida idêntica retorna mesma identidade',(public.fc_banco_criar_conta('{"nome":"Conta A SIM","banco":"SIM A","agencia":"0001","numero":"SIM-A","data":"2026-10-01","saldo":"1000"}')->>'contaId')::uuid=(select a from bank_vars));
select pg_temp.reject('Saldo inicial não pode ser sobrescrito',$$select public.fc_banco_criar_conta('{"nome":"Conta A SIM","banco":"SIM A","agencia":"0001","numero":"SIM-A","data":"2026-10-01","saldo":"999"}')$$);
select pg_temp.reject('Dados bancários ausentes bloqueados',$$select public.fc_banco_criar_conta('{"saldo":"0","data":"2026-10-01"}')$$);
select pg_temp.reject('Saldo NaN bloqueado', $$select public.fc_banco_criar_conta('{"nome":"X","banco":"X","agencia":"X","numero":"X","data":"2026-10-01","saldo":"NaN"}')$$);
select pg_temp.reject('Saldo Infinity bloqueado', $$select public.fc_banco_criar_conta('{"nome":"X","banco":"X","agencia":"X","numero":"X","data":"2026-10-01","saldo":"Infinity"}')$$);
select pg_temp.reject('Saldo centavo fracionado bloqueado', $$select public.fc_banco_criar_conta('{"nome":"X","banco":"X","agencia":"X","numero":"X","data":"2026-10-01","saldo":"1.001"}')$$);
select pg_temp.reject('Saldo fora do limite bloqueado', $$select public.fc_banco_criar_conta('{"nome":"X","banco":"X","agencia":"X","numero":"X","data":"2026-10-01","saldo":"90071992547409.92"}')$$);
select public.fc_banco_importar((select a from bank_vars),'[{"data":"2026-10-03","referencia":"P1","descricao":"Pagamento SIM","valor":"-400"},{"data":"2026-10-03","referencia":"R1","descricao":"Recebimento SIM","valor":"600"},{"data":"2026-10-03","referencia":"T1","descricao":"Transferência SIM","valor":"-200"},{"data":"2026-10-03","referencia":"NP","descricao":"Pagar normalizado","valor":"-800"},{"data":"2026-10-03","referencia":"NR","descricao":"Receber normalizado","valor":"500"}]','SIM.csv');
select public.fc_banco_importar((select b from bank_vars),'[{"data":"2026-10-03","referencia":"T2","descricao":"Transferência SIM","valor":"200"}]','SIM2.csv');
select pg_temp.check('Saldo A=700 e B=400 após movimentos',exists(select 1 from jsonb_array_elements(public.fc_banco_painel()->'contas') c where c->>'id'=(select a::text from bank_vars) and (c->>'saldo')::numeric=700) and exists(select 1 from jsonb_array_elements(public.fc_banco_painel()->'contas') c where c->>'id'=(select b::text from bank_vars) and (c->>'saldo')::numeric=400));
select pg_temp.check('Reimportação idêntica não soma duas vezes',(public.fc_banco_importar((select a from bank_vars),'[{"data":"2026-10-03","referencia":"P1","descricao":"Pagamento SIM","valor":"-400"}]','outroNome.csv')->>'repetidos')::int=1);
select pg_temp.reject('Referência existente com valor diferente rejeitada',format('select public.fc_banco_importar(%L,%L::jsonb,%L)',(select a from bank_vars),'[{"data":"2026-10-03","referencia":"P1","descricao":"Pagamento SIM","valor":"-401"}]','X.csv'));
select pg_temp.reject('Arquivo com linha inválida reverte todas as linhas',format('select public.fc_banco_importar(%L,%L::jsonb,%L)',(select a from bank_vars),'[{"data":"2026-10-03","referencia":"ROLLBACK","descricao":"Não persistir","valor":"10"},{"data":"2026-10-03","referencia":"ERR","descricao":"Inválido","valor":"NaN"}]','X.csv'));
select pg_temp.check('Importação inválida não deixou primeira linha',not exists(select 1 from jsonb_array_elements(public.fc_banco_painel()->'movimentos') m where m->>'referencia'='ROLLBACK'));
select pg_temp.reject('Extrato valor zero rejeitado',format('select public.fc_banco_importar(%L,%L::jsonb,%L)',(select a from bank_vars),'[{"data": "2026-10-03", "referencia": "ZERO", "descricao": "x", "valor": "0"}]','X.csv'),'inválid|zero|fora|anterior|obrigat|duas casas');
select pg_temp.reject('Extrato data impossível rejeitado',format('select public.fc_banco_importar(%L,%L::jsonb,%L)',(select a from bank_vars),'[{"data": "2026-02-30", "referencia": "DATE", "descricao": "x", "valor": "1"}]','X.csv'),'inválid|zero|fora|anterior|obrigat|duas casas');
select pg_temp.reject('Extrato data anterior à abertura rejeitado',format('select public.fc_banco_importar(%L,%L::jsonb,%L)',(select a from bank_vars),'[{"data": "2026-09-30", "referencia": "DATE", "descricao": "x", "valor": "1"}]','X.csv'),'inválid|zero|fora|anterior|obrigat|duas casas');
select pg_temp.reject('Extrato sem referência rejeitado',format('select public.fc_banco_importar(%L,%L::jsonb,%L)',(select a from bank_vars),'[{"data": "2026-10-03", "descricao": "x", "valor": "1"}]','X.csv'),'inválid|zero|fora|anterior|obrigat|duas casas');
select pg_temp.reject('Extrato centavo fracionado rejeitado',format('select public.fc_banco_importar(%L,%L::jsonb,%L)',(select a from bank_vars),'[{"data": "2026-10-03", "referencia": "FRAC", "descricao": "x", "valor": "0.001"}]','X.csv'),'inválid|zero|fora|anterior|obrigat|duas casas');
select pg_temp.reject('Conta de outra empresa não acessível',format('select public.fc_banco_importar(%L,%L::jsonb,%L)',gen_random_uuid(),'[{"data":"2026-10-03","referencia":"A","descricao":"x","valor":"1"}]','X.csv'));
update bank_vars set m=(select (x->>'id')::uuid from jsonb_array_elements(public.fc_banco_painel()->'movimentos') x where x->>'referencia'='P1');
select pg_temp.reject('Motivo obrigatório na conciliação',format('select public.fc_banco_conciliar(%L::jsonb,%L)',jsonb_build_object('tipo','TITULO','movimentoId',(select m from bank_vars),'tituloTipo','PAGAR','tituloId','vendas:PAGAR:P-SIM','valor','400','saldoEsperado','1000'),gen_random_uuid()));
select pg_temp.reject('Conciliação sinal incompatível rejeitada',format('select public.fc_banco_conciliar(%L::jsonb,%L)',jsonb_build_object('tipo','TITULO','movimentoId',(select m from bank_vars),'tituloTipo','RECEBER','tituloId','vendas:RECEBER:R-SIM','valor','100','saldoEsperado','1000','motivo','SIM'),gen_random_uuid()));
select pg_temp.reject('Conciliação valor maior que movimento rejeitada',format('select public.fc_banco_conciliar(%L::jsonb,%L)',jsonb_build_object('tipo','TITULO','movimentoId',(select m from bank_vars),'tituloTipo','PAGAR','tituloId','vendas:PAGAR:P-SIM','valor','401','saldoEsperado','1000','motivo','SIM'),gen_random_uuid()));
select pg_temp.reject('Conciliação saldo esperado obsoleto rejeitada',format('select public.fc_banco_conciliar(%L::jsonb,%L)',jsonb_build_object('tipo','TITULO','movimentoId',(select m from bank_vars),'tituloTipo','PAGAR','tituloId','vendas:PAGAR:P-SIM','valor','400','saldoEsperado','999','motivo','SIM'),gen_random_uuid()));
select pg_temp.reject('Conciliação valor negativo rejeitada',format('select public.fc_banco_conciliar(%L::jsonb,%L)',jsonb_build_object('tipo','TITULO','movimentoId',(select m from bank_vars),'tituloTipo','PAGAR','tituloId','vendas:PAGAR:P-SIM','valor','-1','saldoEsperado','1000','motivo','SIM'),gen_random_uuid()));
update bank_vars set receipt=(public.fc_banco_conciliar(jsonb_build_object('tipo','TITULO','movimentoId',m,'tituloTipo','PAGAR','tituloId','vendas:PAGAR:P-SIM','valor','400','saldoEsperado','1000','motivo','SIM'),request)->>'id')::uuid;
select pg_temp.check('Baixa parcial no pagar 1000-400=600 propagada',exists(select 1 from public.fc_financeiro_titulos() where id='vendas:PAGAR:P-SIM' and saldo=600 and status='PARCIALMENTE PAGO'));
select pg_temp.check('ValorPago 400 e saldoAberto 600 gravados no Vendas',(select estado#>>'{contasPagar,0,valorPago}' from public.fc_app_state where empresa_id=public.fc_current_empresa_id())::numeric=400 and (select estado#>>'{contasPagar,0,saldoAberto}' from public.fc_app_state where empresa_id=public.fc_current_empresa_id())::numeric=600);
select pg_temp.check('Mesmo pedido/requisição retorna recibo sem duplicar',(public.fc_banco_conciliar(jsonb_build_object('tipo','TITULO','movimentoId',(select m from bank_vars),'tituloTipo','PAGAR','tituloId','vendas:PAGAR:P-SIM','valor','400','saldoEsperado','1000','motivo','SIM'),(select request from bank_vars))->>'repetida')::boolean);
select pg_temp.reject('Requisição reutilizada com intenção diferente',format('select public.fc_banco_conciliar(%L::jsonb,%L)',jsonb_build_object('tipo','ESTORNO','conciliacaoId',(select receipt from bank_vars),'motivo','DIFF'),(select request from bank_vars)));
select pg_temp.reject('Movimento totalmente conciliado não é reutilizado',format('select public.fc_banco_conciliar(%L::jsonb,%L)',jsonb_build_object('tipo','TITULO','movimentoId',(select m from bank_vars),'tituloTipo','PAGAR','tituloId','vendas:PAGAR:P-SIM','valor','1','saldoEsperado','600','motivo','SIM'),gen_random_uuid()));
select public.fc_banco_conciliar(jsonb_build_object('tipo','ESTORNO','conciliacaoId',(select receipt from bank_vars),'motivo','Correção SIM'),gen_random_uuid());
select pg_temp.check('Estorno restaura título e libera movimento sem alterar saldo bancário',exists(select 1 from public.fc_financeiro_titulos() where id='vendas:PAGAR:P-SIM' and saldo=1000) and exists(select 1 from jsonb_array_elements(public.fc_banco_painel()->'movimentos') x where x->>'referencia'='P1' and (x->>'disponivel')::numeric=400) and exists(select 1 from jsonb_array_elements(public.fc_banco_painel()->'contas') c where c->>'id'=(select a::text from bank_vars) and (c->>'saldo')::numeric=700));
select pg_temp.reject('Segundo estorno da mesma conciliação rejeitado',format('select public.fc_banco_conciliar(%L::jsonb,%L)',jsonb_build_object('tipo','ESTORNO','conciliacaoId',(select receipt from bank_vars),'motivo','SIM'),gen_random_uuid()));
select public.fc_banco_conciliar(jsonb_build_object('tipo','TITULO','movimentoId',(select (x->>'id')::uuid from jsonb_array_elements(public.fc_banco_painel()->'movimentos') x where x->>'referencia'='R1'),'tituloTipo','RECEBER','tituloId','vendas:RECEBER:R-SIM','valor','600','saldoEsperado','1000','motivo','Recebimento SIM'),gen_random_uuid());
select pg_temp.check('Recebimento parcial 1000-600=400 propagado',exists(select 1 from public.fc_financeiro_titulos() where id='vendas:RECEBER:R-SIM' and saldo=400));
update bank_vars set m=(select (x->>'id')::uuid from jsonb_array_elements(public.fc_banco_painel()->'movimentos') x where x->>'referencia'='T1'),m2=(select (x->>'id')::uuid from jsonb_array_elements(public.fc_banco_painel()->'movimentos') x where x->>'referencia'='T2');
select pg_temp.reject('Transferência com mesma conta rejeitada',format('select public.fc_banco_conciliar(%L::jsonb,%L)',jsonb_build_object('tipo','TRANSFERENCIA','movimentoId',(select m from bank_vars),'movimento2Id',(select m from bank_vars),'motivo','SIM'),gen_random_uuid()),'Transferência exige');
select pg_temp.reject('Transferência com valores diferentes rejeitada',format('select public.fc_banco_conciliar(%L::jsonb,%L)',jsonb_build_object('tipo','TRANSFERENCIA','movimentoId',(select m from bank_vars),'movimento2Id',(select (x->>'id')::uuid from jsonb_array_elements(public.fc_banco_painel()->'movimentos') x where x->>'referencia'='R1'),'motivo','SIM'),gen_random_uuid()),'Transferência exige');
update bank_vars set second=(public.fc_banco_conciliar(jsonb_build_object('tipo','TRANSFERENCIA','movimentoId',m,'movimento2Id',m2,'motivo','SIM'),gen_random_uuid())->>'id')::uuid;
select pg_temp.check('Transferência concilia os dois lados sem duplicar saldos',not exists(select 1 from jsonb_array_elements(public.fc_banco_painel()->'movimentos') x where x->>'referencia' in('T1','T2') and (x->>'disponivel')::numeric<>0));
select pg_temp.reject('Transferência já conciliada não é repetida',format('select public.fc_banco_conciliar(%L::jsonb,%L)',jsonb_build_object('tipo','TRANSFERENCIA','movimentoId',(select m from bank_vars),'movimento2Id',(select m2 from bank_vars),'motivo','SIM'),gen_random_uuid()));
select public.fc_banco_conciliar(jsonb_build_object('tipo','ESTORNO','conciliacaoId',(select second from bank_vars),'motivo','SIM'),gen_random_uuid());
select pg_temp.check('Estorno da transferência libera os dois lados',not exists(select 1 from jsonb_array_elements(public.fc_banco_painel()->'movimentos') x where x->>'referencia' in('T1','T2') and (x->>'disponivel')::numeric<>200));
update bank_vars set receipt=(public.fc_banco_conciliar(jsonb_build_object('tipo','TITULO','movimentoId',(select (x->>'id')::uuid from jsonb_array_elements(public.fc_banco_painel()->'movimentos') x where x->>'referencia'='NP'),'tituloTipo','PAGAR','tituloId',normal::text,'valor','800','saldoEsperado','800','motivo','Normalizado SIM'),gen_random_uuid())->>'id')::uuid;
select pg_temp.check('Título normalizado liquidado sem cópia',exists(select 1 from public.fc_financeiro_titulos() where id=(select normal::text from bank_vars) and saldo=0 and status='LIQUIDADO / CONCILIADO'));
select public.fc_banco_conciliar(jsonb_build_object('tipo','ESTORNO','conciliacaoId',(select receipt from bank_vars),'motivo','Normalizado SIM'),gen_random_uuid());
select pg_temp.check('Estorno normalizado restaura saldo 800',exists(select 1 from public.fc_financeiro_titulos() where id=(select normal::text from bank_vars) and saldo=800));
-- Two installments to the same title require undo in reverse order.
update bank_vars set receipt=(public.fc_banco_conciliar(jsonb_build_object('tipo','TITULO','movimentoId',(select (x->>'id')::uuid from jsonb_array_elements(public.fc_banco_painel()->'movimentos') x where x->>'referencia'='NR'),'tituloTipo','RECEBER','tituloId',normal_r::text,'valor','200','saldoEsperado','500','motivo','Normalizado parcial 1'),gen_random_uuid())->>'id')::uuid;
update bank_vars set second=(public.fc_banco_conciliar(jsonb_build_object('tipo','TITULO','movimentoId',(select (x->>'id')::uuid from jsonb_array_elements(public.fc_banco_painel()->'movimentos') x where x->>'referencia'='NR'),'tituloTipo','RECEBER','tituloId',normal_r::text,'valor','100','saldoEsperado','300','motivo','Normalizado parcial 2'),gen_random_uuid())->>'id')::uuid;
select pg_temp.reject('Estorno fora da ordem protege baixas posteriores',format('select public.fc_banco_conciliar(%L::jsonb,%L)',jsonb_build_object('tipo','ESTORNO','conciliacaoId',(select receipt from bank_vars),'motivo','SIM'),gen_random_uuid()));
select public.fc_banco_conciliar(jsonb_build_object('tipo','ESTORNO','conciliacaoId',(select second from bank_vars),'motivo','SIM'),gen_random_uuid());
select public.fc_banco_conciliar(jsonb_build_object('tipo','ESTORNO','conciliacaoId',(select receipt from bank_vars),'motivo','SIM'),gen_random_uuid());
select pg_temp.check('Estornos em ordem inversa restauram saldo normalizado 500',exists(select 1 from public.fc_financeiro_titulos() where id=(select normal_r::text from bank_vars) and saldo=500));
reset role;
select pg_temp.reject('Movimento do extrato não pode ser alterado nem por fluxo privilegiado',$$update private.fc_banco_movimentos set centavos=0 where conta_id=(select a from bank_vars)$$);
select pg_temp.reject('Conciliação não pode ser apagada',$$delete from private.fc_banco_conciliacoes where empresa_id=public.fc_current_empresa_id()$$);
update public.fc_perfis set perfil='OPERADOR_PATIO' where user_id=auth.uid();
set local role authenticated;
select pg_temp.reject('Pátio não recebe dados bancários',$$select public.fc_banco_painel()$$);
select pg_temp.reject('Pátio não grava banco',$$select public.fc_banco_criar_conta('{}')$$);
reset role;
update public.fc_perfis set perfil='MASTER',ativo=false where user_id=auth.uid();
set local role authenticated;
select pg_temp.reject('Usuário inativo bloqueado',$$select public.fc_banco_painel()$$);
reset role;
update public.fc_perfis set ativo=true,status_aprovacao='PENDENTE' where user_id=auth.uid();
set local role authenticated;
select pg_temp.reject('Usuário pendente bloqueado',$$select public.fc_banco_painel()$$);
reset role;
update public.fc_perfis set status_aprovacao='APROVADO',trocar_senha=true where user_id=auth.uid();
set local role authenticated;
select pg_temp.reject('Troca obrigatória de senha bloqueia banco',$$select public.fc_banco_painel()$$);
reset role;
update public.fc_perfis set trocar_senha=false,perfil='FINANCEIRO' where user_id=auth.uid();
set local role authenticated;
select pg_temp.check('Perfil financeiro autorizado consulta contas',jsonb_array_length(public.fc_banco_painel()->'contas')>=2);
select pg_temp.reject('Cliente não acessa tabela privada diretamente',$$select * from private.fc_banco_movimentos$$);
reset role;
set local role anon;
select pg_temp.reject('Anônimo não executa painel bancário',$$select public.fc_banco_painel()$$);
reset role;
select name,ok,detail from bank_results order by name;
rollback;
