begin;
select set_config('request.jwt.claim.sub','347967ec-c67b-40ac-9b89-6a86482b0ada',true);
create temporary table simulation_results(name text,ok boolean,detail text);
grant all on simulation_results to authenticated,anon;
create function pg_temp.reject(p_name text) returns void language plpgsql as $$
 begin
  begin perform * from public.fc_financeiro_titulos(); raise exception 'ACEITO INDEVIDAMENTE' using errcode='PT001';
  exception when sqlstate 'PT001' then insert into simulation_results values(p_name,false,'ACEITO INDEVIDAMENTE');
   when others then insert into simulation_results values(p_name,sqlerrm ~* 'permiss|inválid|inconsistente|duplicado',sqlerrm);end;
 end;$$;
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasPagar": [{"id": "P", "valor": 800, "valorPago": 300, "status": "PARCIALMENTE PAGO"}], "contasReceber": [{"id": "R", "valor": 1000, "valorRecebido": 400, "status": "PARCIALMENTE PAGO"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
insert into simulation_results select 'Parciais: pagar 500 e receber 600',coalesce(sum(saldo) filter(where tipo='PAGAR'),0)=500 and coalesce(sum(saldo) filter(where tipo='RECEBER'),0)=600 and count(*)=2,'pagar='||coalesce(sum(saldo) filter(where tipo='PAGAR'),0)||', receber='||coalesce(sum(saldo) filter(where tipo='RECEBER'),0) from public.fc_financeiro_titulos();
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasPagar": [{"id": "P", "valor": 800, "status": "PAGO"}], "contasReceber": [{"id": "R", "valor": 1000, "status": "PAGO"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
insert into simulation_results select 'Encerrado: PAGO',coalesce(sum(saldo) filter(where tipo='PAGAR'),0)=0 and coalesce(sum(saldo) filter(where tipo='RECEBER'),0)=0 and count(*)=2,'pagar='||coalesce(sum(saldo) filter(where tipo='PAGAR'),0)||', receber='||coalesce(sum(saldo) filter(where tipo='RECEBER'),0) from public.fc_financeiro_titulos();
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasPagar": [{"id": "P", "valor": 800, "status": "LIQUIDADO"}], "contasReceber": [{"id": "R", "valor": 1000, "status": "LIQUIDADO"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
insert into simulation_results select 'Encerrado: LIQUIDADO',coalesce(sum(saldo) filter(where tipo='PAGAR'),0)=0 and coalesce(sum(saldo) filter(where tipo='RECEBER'),0)=0 and count(*)=2,'pagar='||coalesce(sum(saldo) filter(where tipo='PAGAR'),0)||', receber='||coalesce(sum(saldo) filter(where tipo='RECEBER'),0) from public.fc_financeiro_titulos();
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasPagar": [{"id": "P", "valor": 800, "status": "RECEBIDO"}], "contasReceber": [{"id": "R", "valor": 1000, "status": "RECEBIDO"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
insert into simulation_results select 'Encerrado: RECEBIDO',coalesce(sum(saldo) filter(where tipo='PAGAR'),0)=0 and coalesce(sum(saldo) filter(where tipo='RECEBER'),0)=0 and count(*)=2,'pagar='||coalesce(sum(saldo) filter(where tipo='PAGAR'),0)||', receber='||coalesce(sum(saldo) filter(where tipo='RECEBER'),0) from public.fc_financeiro_titulos();
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasPagar": [{"id": "P", "valor": 800, "status": "CANCELADO"}], "contasReceber": [{"id": "R", "valor": 1000, "status": "CANCELADO"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
insert into simulation_results select 'Encerrado: CANCELADO',coalesce(sum(saldo) filter(where tipo='PAGAR'),0)=0 and coalesce(sum(saldo) filter(where tipo='RECEBER'),0)=0 and count(*)=2,'pagar='||coalesce(sum(saldo) filter(where tipo='PAGAR'),0)||', receber='||coalesce(sum(saldo) filter(where tipo='RECEBER'),0) from public.fc_financeiro_titulos();
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasPagar": [{"id": "P", "valor": 800, "status": "PAGO/LIQUIDADO — COMPROVANTE"}], "contasReceber": [{"id": "R", "valor": 1000, "status": "PAGO/LIQUIDADO — COMPROVANTE"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
insert into simulation_results select 'Encerrado: PAGO/LIQUIDADO — COMPROVANTE',coalesce(sum(saldo) filter(where tipo='PAGAR'),0)=0 and coalesce(sum(saldo) filter(where tipo='RECEBER'),0)=0 and count(*)=2,'pagar='||coalesce(sum(saldo) filter(where tipo='PAGAR'),0)||', receber='||coalesce(sum(saldo) filter(where tipo='RECEBER'),0) from public.fc_financeiro_titulos();
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasReceber": [{"id": "R", "valor": 1000, "valorRecebido": 400, "saldoAberto": 600, "status": "ABERTO"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
insert into simulation_results select 'Saldo explícito coerente usado como no Vendas',coalesce(sum(saldo) filter(where tipo='PAGAR'),0)=0 and coalesce(sum(saldo) filter(where tipo='RECEBER'),0)=600 and count(*)=1,'pagar='||coalesce(sum(saldo) filter(where tipo='PAGAR'),0)||', receber='||coalesce(sum(saldo) filter(where tipo='RECEBER'),0) from public.fc_financeiro_titulos();
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasPagar": [{"id": "P", "valor": 700, "valorPago": 200, "preConferenciaId": "PRE"}], "preConferenciaBoletos": [{"id": "PRE", "status": "RECEBIDO"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
insert into simulation_results select 'Pré-conferência: RECEBIDO',coalesce(sum(saldo) filter(where tipo='PAGAR'),0)=0 and coalesce(sum(saldo) filter(where tipo='RECEBER'),0)=0,'pagar='||coalesce(sum(saldo) filter(where tipo='PAGAR'),0)||', receber='||coalesce(sum(saldo) filter(where tipo='RECEBER'),0) from public.fc_financeiro_titulos();
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasPagar": [{"id": "P", "valor": 700, "valorPago": 200, "preConferenciaId": "PRE"}], "preConferenciaBoletos": [{"id": "PRE", "status": "EM ANÁLISE"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
insert into simulation_results select 'Pré-conferência: EM ANÁLISE',coalesce(sum(saldo) filter(where tipo='PAGAR'),0)=0 and coalesce(sum(saldo) filter(where tipo='RECEBER'),0)=0,'pagar='||coalesce(sum(saldo) filter(where tipo='PAGAR'),0)||', receber='||coalesce(sum(saldo) filter(where tipo='RECEBER'),0) from public.fc_financeiro_titulos();
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasPagar": [{"id": "P", "valor": 700, "valorPago": 200, "preConferenciaId": "PRE"}], "preConferenciaBoletos": [{"id": "PRE", "status": "REJEITADO/CANCELADO"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
insert into simulation_results select 'Pré-conferência: REJEITADO/CANCELADO',coalesce(sum(saldo) filter(where tipo='PAGAR'),0)=0 and coalesce(sum(saldo) filter(where tipo='RECEBER'),0)=0,'pagar='||coalesce(sum(saldo) filter(where tipo='PAGAR'),0)||', receber='||coalesce(sum(saldo) filter(where tipo='RECEBER'),0) from public.fc_financeiro_titulos();
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasPagar": [{"id": "P", "valor": 700, "valorPago": 200, "preConferenciaId": "PRE"}], "preConferenciaBoletos": [{"id": "PRE", "status": "INCORPORADO AO CONTAS A PAGAR"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
insert into simulation_results select 'Pré-conferência: INCORPORADO AO CONTAS A PAGAR',coalesce(sum(saldo) filter(where tipo='PAGAR'),0)=500 and coalesce(sum(saldo) filter(where tipo='RECEBER'),0)=0,'pagar='||coalesce(sum(saldo) filter(where tipo='PAGAR'),0)||', receber='||coalesce(sum(saldo) filter(where tipo='RECEBER'),0) from public.fc_financeiro_titulos();
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasReceber": [{"id": "R1", "valor": 0.1}, {"id": "R2", "valor": 0.2}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
insert into simulation_results select 'Centavos somam exatamente 0,30',coalesce(sum(saldo) filter(where tipo='PAGAR'),0)=0 and coalesce(sum(saldo) filter(where tipo='RECEBER'),0)=0.3 and count(*)=2,'pagar='||coalesce(sum(saldo) filter(where tipo='PAGAR'),0)||', receber='||coalesce(sum(saldo) filter(where tipo='RECEBER'),0) from public.fc_financeiro_titulos();
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasReceber": [{"id": "R", "valor": "NaN"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.reject('Bloqueia valor NaN');
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasReceber": [{"id": "R", "valor": "Infinity"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.reject('Bloqueia valor Infinity');
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasReceber": [{"id": "R", "valor": "-Infinity"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.reject('Bloqueia valor -Infinity');
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasReceber": [{"id": "R", "valor": "texto"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.reject('Bloqueia valor texto');
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasReceber": [{"id": "R", "valor": -1}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.reject('Bloqueia valor -1');
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasReceber": [{"id": "R", "valor": 1000, "valorRecebido": 400, "saldoAberto": 550}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.reject('Bloqueia saldo divergente das baixas');
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasReceber": [{"id": "R", "valor": 1000, "valorRecebido": 400, "saldoAberto": 0, "status": "ABERTO"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.reject('Bloqueia saldo aberto divergente: 0');
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasReceber": [{"id": "R", "valor": 1000, "valorRecebido": 400, "saldoAberto": 599.99, "status": "ABERTO"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.reject('Bloqueia saldo aberto divergente: 599.99');
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasReceber": [{"id": "R", "valor": 10, "valorRecebido": 11}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.reject('Bloqueia recebimento superior ao título');
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasReceber": [{"id": "R", "valor": 10}, {"id": "R", "valor": 20}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.reject('Bloqueia identidade duplicada');
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasReceber": [{"valor": 10}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.reject('Bloqueia título sem identificação');
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasReceber": {"valor": 10}}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.reject('Bloqueia lista inválida');
reset role;
update public.fc_app_state set versao=versao+1, estado='{"contasReceber": [{"id": "R", "valor": 10, "vencimento": "2026-02-31"}]}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.reject('Bloqueia vencimento impossível');
reset role;
update public.fc_app_state set versao=versao+1, estado='{}'::jsonb where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
reset role;
create temporary table native_fixture as with inserted as (insert into public.fc_contas_pagar(empresa_id,unidade_id,descricao,vencimento,valor,saldo) select p.empresa_id,u.id,'SIMULACAO','2026-10-04',80,30 from public.fc_perfis p join public.fc_unidades u on u.empresa_id=p.empresa_id where p.user_id=auth.uid() limit 1 returning id) select id from inserted;
update public.fc_app_state set versao=versao+1, estado=jsonb_build_object('contasPagar',jsonb_build_array(jsonb_build_object('id',(select id::text from native_fixture),'valor',80))) where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
insert into simulation_results select 'Título normalizado prevalece sem duplicação',coalesce(sum(saldo) filter(where tipo='PAGAR'),0)=30 and coalesce(sum(saldo) filter(where tipo='RECEBER'),0)=0 and count(*)=1,'pagar='||coalesce(sum(saldo) filter(where tipo='PAGAR'),0)||', receber='||coalesce(sum(saldo) filter(where tipo='RECEBER'),0) from public.fc_financeiro_titulos();
reset role;
update public.fc_app_state set versao=versao+1, estado=jsonb_build_object('contasPagar',jsonb_build_array(jsonb_build_object('id','LEGADO','normalized_id',(select id::text from native_fixture),'valor',80))) where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
insert into simulation_results select 'Vínculo explícito do legado sem duplicação',coalesce(sum(saldo) filter(where tipo='PAGAR'),0)=30 and coalesce(sum(saldo) filter(where tipo='RECEBER'),0)=0 and count(*)=1,'pagar='||coalesce(sum(saldo) filter(where tipo='PAGAR'),0)||', receber='||coalesce(sum(saldo) filter(where tipo='RECEBER'),0) from public.fc_financeiro_titulos();
reset role;
update public.fc_perfis set ativo=false where user_id=auth.uid();
set local role authenticated;
select pg_temp.reject('Usuário inativo');
reset role;
update public.fc_perfis set ativo=true where user_id=auth.uid();
reset role;
update public.fc_perfis set status_aprovacao='PENDENTE' where user_id=auth.uid();
set local role authenticated;
select pg_temp.reject('Usuário pendente');
reset role;
update public.fc_perfis set status_aprovacao='APROVADO' where user_id=auth.uid();
reset role;
update public.fc_perfis set perfil='VENDAS' where user_id=auth.uid();
set local role authenticated;
select pg_temp.reject('Usuário sem permissão financeira');
reset role;
update public.fc_perfis set perfil='MASTER' where user_id=auth.uid();
update public.fc_perfis set perfil='FINANCEIRO' where user_id=auth.uid();
set local role authenticated;
insert into simulation_results select 'Perfil FINANCEIRO autorizado',coalesce(sum(saldo) filter(where tipo='PAGAR'),0)=30 and coalesce(sum(saldo) filter(where tipo='RECEBER'),0)=0 and count(*)=1,'pagar='||coalesce(sum(saldo) filter(where tipo='PAGAR'),0)||', receber='||coalesce(sum(saldo) filter(where tipo='RECEBER'),0) from public.fc_financeiro_titulos();
reset role;
update public.fc_perfis set perfil='VENDAS',permissoes=jsonb_build_object('financeiro',true) where user_id=auth.uid();
set local role authenticated;
insert into simulation_results select 'Permissão financeira explícita autorizada',coalesce(sum(saldo) filter(where tipo='PAGAR'),0)=30 and coalesce(sum(saldo) filter(where tipo='RECEBER'),0)=0 and count(*)=1,'pagar='||coalesce(sum(saldo) filter(where tipo='PAGAR'),0)||', receber='||coalesce(sum(saldo) filter(where tipo='RECEBER'),0) from public.fc_financeiro_titulos();
reset role;
update public.fc_perfis set perfil='MASTER' where user_id=auth.uid();
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000099',true);
set local role authenticated;
select pg_temp.reject('Usuário sem perfil não recebe dados');
reset role;
set local role anon;
select pg_temp.reject('Anônimo não executa RPC');
reset role;
select jsonb_agg(jsonb_build_object('name',name,'ok',ok,'detail',detail)) as results from simulation_results;
rollback;
