-- Cenários sintéticos. Toda escrita é revertida no final, inclusive contagens e fechamento.
begin;
select set_config('request.jwt.claim.sub',(select user_id::text from public.fc_perfis where perfil='MASTER' and ativo and status_aprovacao='APROVADO' order by created_at limit 1),true);
create temporary table patio_results(name text,ok boolean,detail text);
grant all on patio_results to authenticated,anon;
create temporary table patio_vars as select empresa_id,user_id,versao,estado original,('SIM-PATIO-'||gen_random_uuid()::text) caixa_id from public.fc_app_state a join public.fc_perfis p using(empresa_id) where p.user_id=auth.uid();
grant select,update on patio_vars to authenticated,anon;
create function pg_temp.check(p_name text,p_ok boolean,p_detail text default '') returns void language sql as $$insert into patio_results values(p_name,coalesce(p_ok,false),p_detail);$$;
create function pg_temp.reject(p_name text,p_sql text,p_pattern text default 'inválid|bloquead|permiss|aprovad|imutável|atualiz|mudou|confere|conferem|obrigat|inconsistente|negativ|não encontrado|violates|denied') returns void language plpgsql as $$
begin
 begin execute p_sql;raise exception 'ACEITO INDEVIDAMENTE' using errcode='PT001';
 exception when sqlstate 'PT001' then insert into patio_results values(p_name,false,'ACEITO INDEVIDAMENTE');
 when others then insert into patio_results values(p_name,sqlerrm ~* p_pattern,sqlerrm);end;
end;$$;
create temporary table patio_fixture(estado jsonb,candidate jsonb);
grant select,update on patio_fixture to authenticated,anon;
insert into patio_fixture(estado) select replace('{"produtos": [{"id": "A", "nome": "Cimento simulado", "ativo": true}, {"id": "B", "nome": "Revenda sem movimento", "ativo": true}, {"id": "U", "nome": "Uso consumo", "finalidade": "USO / CONSUMO"}, {"id": "I", "nome": "Imobilizado", "categoria": "IMOBILIZADO"}, {"id": "X", "nome": "Inativo", "ativo": false}], "estoqueMov": [{"produtoId": "A", "unidade": "MATRIZ", "tipo": "ENTRADA", "quantidade": 1000}, {"produtoId": "A", "unidade": "FILIAL", "tipo": "ENTRADA", "quantidade": 500}, {"produtoId": "A", "unidade": "MATRIZ", "tipo": "SAÍDA", "quantidade": 300}], "vendasBalcao": [{"id": "ORC", "status": "ORÇAMENTO", "itens": [{"produtoId": "A", "qtd": 200}]}, {"id": "PAR", "status": "PARCIALMENTE ATENDIDO", "itens": [{"produtoId": "A", "qtd": 100}], "itensSaldo": [{"produtoId": "A", "qtd": 17}]}, {"id": "V1", "caixaId": "TEST", "status": "CONCLUÍDA", "total": 100, "pagamento": "DINHEIRO"}, {"id": "V2", "caixaId": "TEST", "status": "CONCLUÍDA", "total": 50, "pagamento": "PIX"}], "caixasBalcao": [{"id": "TEST", "status": "ABERTO", "data": "2026-10-03", "unidade": "ESTOQUE ÚNICO", "operador": "OPERADOR FICTÍCIO", "abertoEm": "2026-10-03T12:00:00Z", "saldoInicial": 200}], "clientes": [{"nome": "DADO FINANCEIRO PRIVADO"}]}', 'TEST',caixa_id)::jsonb from patio_vars;
update public.fc_app_state set versao=versao+1,estado=(select estado from patio_fixture) where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.check('Todos os produtos ativos, inclusive sem movimento; exclui consumo, imobilizado e inativo',jsonb_array_length(public.fc_patio_status((select caixa_id from patio_vars))->'itens')=2);
select pg_temp.check('Estoque unificado 1000+500-300=1200; reserva 200+17=217; disponível 983',exists(select 1 from jsonb_array_elements(public.fc_patio_status((select caixa_id from patio_vars))->'itens') x where x->>'produtoId'='A' and (x->>'total')::numeric=1200 and (x->>'bloqueado')::numeric=217 and (x->>'disponivel')::numeric=983));
select pg_temp.check('Sem contagens: dois pendentes e fechamento bloqueado',(public.fc_patio_status((select caixa_id from patio_vars))->>'pendentes')::int=2 and not (public.fc_patio_status((select caixa_id from patio_vars))->>'liberado')::boolean);
select pg_temp.reject('Contagem campo vazio bloqueada',format('select public.fc_patio_contar(%L,%L,null,%L)',(select caixa_id from patio_vars),'B',(select x->>'base' from jsonb_array_elements(public.fc_patio_status((select caixa_id from patio_vars))->'itens') x where x->>'produtoId'='B')));
select pg_temp.reject('Contagem negativa bloqueada',format('select public.fc_patio_contar(%L,%L,-1,%L)',(select caixa_id from patio_vars),'B',(select x->>'base' from jsonb_array_elements(public.fc_patio_status((select caixa_id from patio_vars))->'itens') x where x->>'produtoId'='B')));
select pg_temp.reject('Contagem NaN bloqueada',format('select public.fc_patio_contar(%L,%L,''NaN''::numeric,%L)',(select caixa_id from patio_vars),'B',(select x->>'base' from jsonb_array_elements(public.fc_patio_status((select caixa_id from patio_vars))->'itens') x where x->>'produtoId'='B')));
select pg_temp.reject('Contagem Infinity bloqueada',format('select public.fc_patio_contar(%L,%L,''Infinity''::numeric,%L)',(select caixa_id from patio_vars),'B',(select x->>'base' from jsonb_array_elements(public.fc_patio_status((select caixa_id from patio_vars))->'itens') x where x->>'produtoId'='B')));
select pg_temp.reject('Contagem limite excedido bloqueada',format('select public.fc_patio_contar(%L,%L,1000000000001,%L)',(select caixa_id from patio_vars),'B',(select x->>'base' from jsonb_array_elements(public.fc_patio_status((select caixa_id from patio_vars))->'itens') x where x->>'produtoId'='B')));
select pg_temp.reject('Contagem sete casas bloqueada',format('select public.fc_patio_contar(%L,%L,0.1234567,%L)',(select caixa_id from patio_vars),'B',(select x->>'base' from jsonb_array_elements(public.fc_patio_status((select caixa_id from patio_vars))->'itens') x where x->>'produtoId'='B')));
select pg_temp.reject('Produto inativo não pode ser contado',format('select public.fc_patio_contar(%L,%L,0,%L)',(select caixa_id from patio_vars),'X','inventada'));
select pg_temp.reject('Caixa de outro contexto não encontrado', $$select public.fc_patio_status('OUTRA-EMPRESA-CAIXA')$$);
select pg_temp.check('Resposta da gravação já mostra a diferença de 1', (public.fc_patio_contar((select caixa_id from patio_vars),'A',982,(select x->>'base' from jsonb_array_elements(public.fc_patio_status((select caixa_id from patio_vars))->'itens') x where x->>'produtoId'='A'))->>'divergencias')::int=1);
select pg_temp.check('Zero explícito do produto sem estoque é salvo', (public.fc_patio_contar((select caixa_id from patio_vars),'B',0,(select x->>'base' from jsonb_array_elements(public.fc_patio_status((select caixa_id from patio_vars))->'itens') x where x->>'produtoId'='B'))->>'pendentes')::int=0);
select pg_temp.check('Diferença em um produto mantém bloqueado',not(public.fc_patio_status((select caixa_id from patio_vars))->>'liberado')::boolean);
select pg_temp.check('Recontagem correta libera todos', (public.fc_patio_contar((select caixa_id from patio_vars),'A',983,(select x->>'base' from jsonb_array_elements(public.fc_patio_status((select caixa_id from patio_vars))->'itens') x where x->>'produtoId'='A'))->>'liberado')::boolean);
reset role;
select pg_temp.check('Histórico preserva revisão anterior',(select count(*) from private.fc_patio_contagens where caixa_id=(select caixa_id from patio_vars))=3);
update patio_fixture set candidate=public.fc_patio_status((select caixa_id from patio_vars));
update public.fc_app_state set versao=versao+1,estado=jsonb_set(estado,'{estoqueMov}',estado->'estoqueMov'||'[{"produtoId":"A","tipo":"AJUSTE","ajuste":0,"quantidade":999,"motivo":"Simulação líquida zero"}]') where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.check('Ajuste zero não soma quantidade substituta 999',exists(select 1 from jsonb_array_elements(public.fc_patio_status((select caixa_id from patio_vars))->'itens') x where x->>'produtoId'='A' and (x->>'total')::numeric=1200));
select pg_temp.check('Novo movimento, mesmo saldo, exige recontagem',(public.fc_patio_status((select caixa_id from patio_vars))->>'desatualizados')::int=1 and not(public.fc_patio_status((select caixa_id from patio_vars))->>'liberado')::boolean);
select pg_temp.reject('Base obsoleta não grava contagem',format('select public.fc_patio_contar(%L,%L,983,%L)',(select caixa_id from patio_vars),'A',(select x->>'base' from patio_fixture,jsonb_array_elements(candidate->'itens') x where x->>'produtoId'='A')));
select public.fc_patio_contar((select caixa_id from patio_vars),'A',983,(select x->>'base' from jsonb_array_elements(public.fc_patio_status((select caixa_id from patio_vars))->'itens') x where x->>'produtoId'='A'));
reset role;
update public.fc_app_state set versao=versao+1,estado=jsonb_set(estado,'{vendasBalcao,1,itensSaldo,0,qtd}','18') where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.check('Mudança do orçamento parcial usa saldo 18 e desatualiza contagem',exists(select 1 from jsonb_array_elements(public.fc_patio_status((select caixa_id from patio_vars))->'itens') x where x->>'produtoId'='A' and (x->>'bloqueado')::numeric=218 and not(x->>'atual')::boolean));
reset role;
update public.fc_perfis set perfil='OPERADOR_PATIO' where user_id=auth.uid();
set local role authenticated;
select pg_temp.check('Operador acessa somente RPC e não o snapshot financeiro',(select count(*) from public.fc_app_state)=0 and jsonb_array_length(public.fc_patio_status((select caixa_id from patio_vars))->'itens')=2);
select pg_temp.reject('Operador não grava a base inteira', $$select public.fc_salvar_estado('{}',0)$$);
select pg_temp.check('Operador autorizado pode recontar', (public.fc_patio_contar((select caixa_id from patio_vars),'A',982,(select x->>'base' from jsonb_array_elements(public.fc_patio_status((select caixa_id from patio_vars))->'itens') x where x->>'produtoId'='A'))->>'liberado')::boolean);
reset role;
update public.fc_perfis set status_aprovacao='PENDENTE' where user_id=auth.uid();
set local role authenticated;
select pg_temp.reject('Usuário não aprovado bloqueado', $$select public.fc_patio_status()$$);
reset role;
update public.fc_perfis set status_aprovacao='APROVADO',ativo=false where user_id=auth.uid();
set local role authenticated;
select pg_temp.reject('Usuário inativo bloqueado', $$select public.fc_patio_status()$$);
reset role;
update public.fc_perfis set ativo=true,trocar_senha=true where user_id=auth.uid();
set local role authenticated;
select pg_temp.reject('Troca obrigatória de senha bloqueia pátio', $$select public.fc_patio_status()$$);
reset role;
update public.fc_perfis set trocar_senha=false,perfil='CAIXA' where user_id=auth.uid();
set local role authenticated;
select pg_temp.reject('Caixa sem permissão não realiza contagem',format('select public.fc_patio_contar(%L,%L,982,%L)',(select caixa_id from patio_vars),'A',(select x->>'base' from jsonb_array_elements(public.fc_patio_status((select caixa_id from patio_vars))->'itens') x where x->>'produtoId'='A')),'reservada');
reset role;
update public.fc_perfis set perfil='MASTER' where user_id=auth.uid();
set local role anon;
select pg_temp.reject('Anônimo não lê pátio', $$select public.fc_patio_status()$$);
reset role;
-- Catalog and malformed source checks run with privileged read, still rolled back.
select pg_temp.check('Catálogo vazio nunca libera fechamento',not(private.fc_status_patio((select empresa_id from patio_vars),(select caixa_id from patio_vars),'{"produtos":[],"estoqueMov":[],"vendasBalcao":[]}')->>'liberado')::boolean);
select pg_temp.reject('Orçamento parcial sem itensSaldo bloqueia',format('select * from private.fc_itens_patio(%L::jsonb)',(select jsonb_set(estado,'{vendasBalcao,1}',(estado#>'{vendasBalcao,1}')-'itensSaldo') from public.fc_app_state where empresa_id=public.fc_current_empresa_id())),'ausente');
select pg_temp.reject('Produto duplicado bloqueia catálogo',format('select * from private.fc_itens_patio(%L::jsonb)',(select jsonb_set(estado,'{produtos}',estado->'produtos'||jsonb_build_array(estado#>'{produtos,0}')) from public.fc_app_state where empresa_id=public.fc_current_empresa_id())),'duplicado');
select pg_temp.check('Reserva maior que estoque marca inconsistência e bloqueia',exists(select 1 from jsonb_array_elements(private.fc_status_patio((select empresa_id from patio_vars),(select caixa_id from patio_vars),(select jsonb_set(estado,'{estoqueMov}','[]') from public.fc_app_state where empresa_id=public.fc_current_empresa_id()))->'itens') x where x->>'produtoId'='A' and (x->>'inconsistente')::boolean and (x->>'disponivel')::numeric<0));
update public.fc_app_state set versao=versao+1,estado=jsonb_set(estado,'{produtos}',estado->'produtos'||'[{"id":"NOVO","nome":"Novo ativo sem movimento"}]') where empresa_id=public.fc_current_empresa_id();
set local role authenticated;
select pg_temp.check('Produto novo ativo exige nova contagem mesmo sem movimento',(public.fc_patio_status((select caixa_id from patio_vars))->>'pendentes')::int=1 and not(public.fc_patio_status((select caixa_id from patio_vars))->>'liberado')::boolean);
reset role;
update public.fc_app_state set versao=versao+1,estado=jsonb_set(estado,'{produtos}',(select jsonb_agg(x) from jsonb_array_elements(estado->'produtos') x where x->>'id'<>'NOVO')) where empresa_id=public.fc_current_empresa_id();
-- Generate correct closure from backend stock, then attack individual fields.
update patio_fixture set candidate=(select a.estado from public.fc_app_state a where a.empresa_id=public.fc_current_empresa_id());
update patio_fixture set candidate=jsonb_set(candidate,'{caixasBalcao,0}',candidate->'caixasBalcao'->0||jsonb_build_object('status','FECHADO','totalVendas',150,'porForma',jsonb_build_object('DINHEIRO',100,'PIX',50),'vendaIds',jsonb_build_array('V1','V2'),'saldoEsperado',300,'saldoContado',300,'diferenca',0,'justificativa','','estoqueSnapshot',(select jsonb_agg(jsonb_build_object('produtoId',produto_id,'saldoFinal',total,'bloqueadoOrcamento',bloqueado,'disponivel',disponivel)) from private.fc_itens_patio(candidate))));
set local role authenticated;
select pg_temp.reject('Versão antiga não sobrescreve snapshot',format('select public.fc_salvar_estado(%L::jsonb,%s)',(select estado from patio_fixture),(select versao from patio_vars)));
select pg_temp.reject('Update direto sem incrementar versão é rejeitado',$$update public.fc_app_state set estado=estado||'{"semVersao":true}' where empresa_id=public.fc_current_empresa_id()$$);
select pg_temp.reject('Receita adulterada',format('select public.fc_salvar_estado(%L::jsonb,%s)',(select jsonb_set(candidate,'{caixasBalcao,0,totalVendas}','151') from patio_fixture),(select versao from public.fc_app_state where empresa_id=public.fc_current_empresa_id())));
select pg_temp.reject('Numerário inclui PIX indevidamente',format('select public.fc_salvar_estado(%L::jsonb,%s)',(select jsonb_set(candidate,'{caixasBalcao,0,saldoEsperado}','350') from patio_fixture),(select versao from public.fc_app_state where empresa_id=public.fc_current_empresa_id())));
select pg_temp.reject('Diferença incoerente',format('select public.fc_salvar_estado(%L::jsonb,%s)',(select jsonb_set(candidate,'{caixasBalcao,0,diferenca}','1') from patio_fixture),(select versao from public.fc_app_state where empresa_id=public.fc_current_empresa_id())));
select pg_temp.reject('Saldo contado inválido',format('select public.fc_salvar_estado(%L::jsonb,%s)',(select jsonb_set(candidate,'{caixasBalcao,0,saldoContado}','"NaN"') from patio_fixture),(select versao from public.fc_app_state where empresa_id=public.fc_current_empresa_id())));
select pg_temp.reject('Relatório de estoque sem disponível rejeitado',format('select public.fc_salvar_estado(%L::jsonb,%s)',(select jsonb_set(candidate,'{caixasBalcao,0,estoqueSnapshot,0}',(candidate#>'{caixasBalcao,0,estoqueSnapshot,0}')-'disponivel') from patio_fixture),(select versao from public.fc_app_state where empresa_id=public.fc_current_empresa_id())));
select pg_temp.reject('Diferença sem justificativa rejeitada',format('select public.fc_salvar_estado(%L::jsonb,%s)',(select jsonb_set(jsonb_set(candidate,'{caixasBalcao,0,saldoContado}','290'),'{caixasBalcao,0,diferenca}','-10') from patio_fixture),(select versao from public.fc_app_state where empresa_id=public.fc_current_empresa_id())));
select pg_temp.reject('Mudança de origem durante fechamento rejeitada',format('select public.fc_salvar_estado(%L::jsonb,%s)',(select candidate||'{"adulterado":true}' from patio_fixture),(select versao from public.fc_app_state where empresa_id=public.fc_current_empresa_id())));
select pg_temp.reject('Histórico não aceita inserção direta',$$insert into public.fc_caixa_fechamentos(id,empresa_id) values('FORJADO',public.fc_current_empresa_id())$$);
reset role;
-- Change stock; closure must fail without creating history or closed state.
update public.fc_app_state set versao=versao+1,estado=jsonb_set(estado,'{estoqueMov}',estado->'estoqueMov'||'[{"produtoId":"A","tipo":"AJUSTE","ajuste":0}]') where empresa_id=public.fc_current_empresa_id();
update patio_fixture set candidate=jsonb_set((select estado from public.fc_app_state where empresa_id=public.fc_current_empresa_id()),'{caixasBalcao}',candidate->'caixasBalcao');
set local role authenticated;
select pg_temp.reject('Fechamento com contagem obsoleta bloqueado',format('select public.fc_salvar_estado(%L::jsonb,%s)',(select candidate from patio_fixture),(select versao from public.fc_app_state where empresa_id=public.fc_current_empresa_id())));
select pg_temp.check('Falhas não marcaram fechado nem criaram histórico',(select estado#>>'{caixasBalcao,0,status}' from public.fc_app_state where empresa_id=public.fc_current_empresa_id())='ABERTO' and (select count(*) from public.fc_caixa_fechamentos where id=(select caixa_id from patio_vars))=0);
select public.fc_patio_contar((select caixa_id from patio_vars),'A',982,(select x->>'base' from jsonb_array_elements(public.fc_patio_status((select caixa_id from patio_vars))->'itens') x where x->>'produtoId'='A'));
update patio_fixture set estado=public.fc_salvar_estado((select candidate from patio_fixture),(select versao from public.fc_app_state where empresa_id=public.fc_current_empresa_id()));
select pg_temp.check('Fechamento e recibo canônico confirmados',(select estado#>>'{estado,caixasBalcao,0,status}' from patio_fixture)='FECHADO' and (select estado#>>'{estado,caixasBalcao,0,patioConferencia,liberado}' from patio_fixture)='true');
select pg_temp.check('Histórico financeiro contém exatamente o mesmo caixa e conferente',(select snapshot from public.fc_caixa_fechamentos where id=(select caixa_id from patio_vars))=(select estado#>'{estado,caixasBalcao,0}' from patio_fixture));
select pg_temp.reject('Caixa fechado não reabre',format('select public.fc_salvar_estado(%L::jsonb,%s)',(select jsonb_set(estado->'estado','{caixasBalcao,0,status}','"ABERTO"') from patio_fixture),(select versao from public.fc_app_state where empresa_id=public.fc_current_empresa_id())));
select pg_temp.reject('Histórico não pode ser alterado pelo cliente',$$update public.fc_caixa_fechamentos set saldo_contado=0 where id=(select caixa_id from patio_vars)$$);
select pg_temp.reject('Histórico não pode ser apagado pelo cliente',$$delete from public.fc_caixa_fechamentos where id=(select caixa_id from patio_vars)$$);
reset role;
select pg_temp.reject('Histórico também protege contra alteração privilegiada',$$update public.fc_caixa_fechamentos set saldo_contado=0 where id=(select caixa_id from patio_vars)$$);
select name,ok,detail from patio_results order by name;
rollback;
