import{useEffect,useState}from"react";import App from"./App.jsx";import{setAuthContext,supabase,supabaseConfigured}from"./supabase.js";
const LAST="forte_vendas_last_login";
const strong=s=>s.length>=9&&/[A-Z]/.test(s)&&/[a-z]/.test(s)&&/\d/.test(s)&&/[^A-Za-z0-9]/.test(s)&&!/(012|123|234|345|456|567|678|789|987|876|765|654|543|432|321|210)/.test(s);
const digits=v=>String(v||"").replace(/\D/g,"");
export default function AuthGate(){
 const[ready,setReady]=useState(!supabaseConfigured),[session,setSession]=useState(null),[profile,setProfile]=useState(null),[pending,setPending]=useState(null),[mode,setMode]=useState("login"),[login,setLogin]=useState(()=>localStorage.getItem(LAST)||""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const[reg,setReg]=useState({nome:"",cpf:"",whatsapp:"",email:"",password:"",confirm:""});
 const[form,setForm]=useState({endereco:"",numero:"",bairro:"",cidade:"",uf:"",cep:"",complemento:"",contato_emergencia:""}),[identidade,setIdentidade]=useState(null),[comprovante,setComprovante]=useState(null);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session)).finally(()=>setReady(true));const{data}=supabase.auth.onAuthStateChange((event,next)=>{setSession(next);if(!next){setAuthContext(null);setProfile(null);setMode("login")}if(event==="PASSWORD_RECOVERY")setMode("recovery")});return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session||!supabase)return;setReady(false);supabase.from("fc_perfis").select("*").eq("user_id",session.user.id).maybeSingle().then(async({data,error})=>{if(error||!data){setMsg("CADASTRO NÃO LOCALIZADO.");setReady(true);return}setProfile(data);if(data.ativo){setAuthContext({user:session.user,profile:data});if(data.trocar_senha){setMode("recovery");setReady(true)}else setReady("authorized");return}const p=await supabase.from("fc_usuarios_pendentes").select("*").eq("auth_user_id",session.user.id).maybeSingle();setPending(p.data||null);if(p.data)setForm(x=>({...x,...Object.fromEntries(Object.keys(x).map(k=>[k,p.data?.[k]||""]))}));setMode("onboarding");setReady(true)})},[session]);
 if(!supabaseConfigured)return <App/>;if(ready==="authorized")return <App/>;if(!ready)return <div className="authPage"><div className="authCard">CARREGANDO…</div></div>;
 const enter=async e=>{e.preventDefault();setBusy(true);setMsg("ENTRANDO…");const id=login.trim().toLowerCase();let error;if(id.includes("@"))({error}=await supabase.auth.signInWithPassword({email:id,password}));else{const x=await supabase.functions.invoke("login-cpf",{body:{cpf:digits(id),password}});error=x.error;if(!error&&x.data?.access_token)({error}=await supabase.auth.setSession({access_token:x.data.access_token,refresh_token:x.data.refresh_token}));}if(!error)localStorage.setItem(LAST,id);setMsg(error?"CPF, E-MAIL OU SENHA INVÁLIDOS.":"");setBusy(false)};
 const register=async e=>{e.preventDefault();if(!strong(reg.password))return setMsg("A SENHA PRECISA TER 9 CARACTERES, MAIÚSCULA, MINÚSCULA, NÚMERO E SÍMBOLO.");if(reg.password!==reg.confirm)return setMsg("AS SENHAS NÃO COINCIDEM.");setBusy(true);const{data,error}=await supabase.functions.invoke("first-access",{body:reg});if(!error&&data?.access_token)await supabase.auth.setSession({access_token:data.access_token,refresh_token:data.refresh_token});setMsg(error?(error.context?.body?.error||"NÃO FOI POSSÍVEL CONCLUIR O PRÉ-CADASTRO."):"PRÉ-CADASTRO CRIADO. COMPLETE A SEGUNDA ETAPA.");setBusy(false)};
 const forgot=async()=>{const identificador=login.trim().toLowerCase();if(!identificador)return setMsg("INFORME CPF OU E-MAIL.");setBusy(true);const{error}=await supabase.functions.invoke("recover-password-whatsapp",{body:{identificador}});setMsg(error?"ENVIO PELO WHATSAPP AINDA NÃO CONFIGURADO. PROCURE O ADMINISTRADOR.":"SE O CADASTRO EXISTIR, O LINK SERÁ ENVIADO AO WHATSAPP CADASTRADO.");setBusy(false)};
 const change=async e=>{e.preventDefault();if(!strong(password)||password!==confirm)return setMsg("CONFIRA AS REGRAS E A CONFIRMAÇÃO DA SENHA.");const{error}=await supabase.auth.updateUser({password});if(error)return setMsg("NÃO FOI POSSÍVEL ALTERAR A SENHA.");await supabase.from("fc_perfis").update({trocar_senha:false}).eq("user_id",session.user.id);setMsg("SENHA ALTERADA.");location.replace("/")};
 const upload=async(file,tipo)=>{if(!file)return"";const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_"),path=`${session.user.id}/${tipo}-${Date.now()}-${safe}`;const{error}=await supabase.storage.from("forte-vendas-cadastros").upload(path,file);if(error)throw error;return path};
 const submit=async e=>{e.preventDefault();if(!form.endereco||!form.numero||!form.bairro||!form.cidade||!form.uf||digits(form.cep).length!==8)return setMsg("PREENCHA O ENDEREÇO COMPLETO.");if(!identidade&&!pending?.documento_identificacao_path)return setMsg("ANEXE O DOCUMENTO DE IDENTIFICAÇÃO.");if(!comprovante&&!pending?.comprovante_endereco_path)return setMsg("ANEXE O COMPROVANTE DE ENDEREÇO.");setBusy(true);try{const doc=identidade?await upload(identidade,"identificacao"):pending.documento_identificacao_path,end=comprovante?await upload(comprovante,"endereco"):pending.comprovante_endereco_path;const{error}=await supabase.from("fc_usuarios_pendentes").update({...form,cep:digits(form.cep),documento_identificacao_path:doc,comprovante_endereco_path:end,status:"EM_ANALISE",enviado_em:new Date().toISOString()}).eq("auth_user_id",session.user.id);if(error)throw error;setPending(x=>({...x,...form,status:"EM_ANALISE"}));setMsg("CADASTRO ENVIADO. AGUARDE A APROVAÇÃO DO ADMINISTRADOR.")}catch(err){setMsg(err.message||"NÃO FOI POSSÍVEL ENVIAR.")}setBusy(false)};
 const card=children=><div className="authPage"><div className="authCard">{children}{msg&&<div className="authMessage">{msg}</div>}</div></div>;
 if(mode==="onboarding")return card(<>{pending?.status==="EM_ANALISE"?<><h1>FORTE VENDAS</h1><h2>CADASTRO EM ANÁLISE</h2><p>O administrador conferirá os documentos e definirá suas funções. Você receberá o aviso no WhatsApp cadastrado.</p><button onClick={()=>supabase.auth.signOut()}>SAIR</button></>:<form onSubmit={submit}><h1>SEGUNDA ETAPA</h1><p>COMPLETE SEUS DADOS PARA ANÁLISE</p>{["endereco","numero","bairro","cidade","uf","cep","complemento","contato_emergencia"].map(k=><input key={k} value={form[k]} onChange={e=>setForm(x=>({...x,[k]:e.target.value}))} placeholder={k.replaceAll("_"," ").toUpperCase()} required={!["complemento","contato_emergencia"].includes(k)}/>)}<label>DOCUMENTO DE IDENTIFICAÇÃO<input type="file" accept=".pdf,image/*" onChange={e=>setIdentidade(e.target.files?.[0]||null)}/></label><label>COMPROVANTE DE ENDEREÇO<input type="file" accept=".pdf,image/*" onChange={e=>setComprovante(e.target.files?.[0]||null)}/></label><button disabled={busy}>ENVIAR PARA ANÁLISE</button><button type="button" className="linkButton" onClick={()=>supabase.auth.signOut()}>SAIR</button></form>}</>);
 if(mode==="register")return card(<form onSubmit={register}><h1>FORTE VENDAS</h1><p>PRIMEIRO ACESSO</p><input value={reg.nome} onChange={e=>setReg(x=>({...x,nome:e.target.value}))} placeholder="Nome completo" required/><input value={reg.cpf} onChange={e=>setReg(x=>({...x,cpf:e.target.value}))} inputMode="numeric" placeholder="CPF" required/><input value={reg.whatsapp} onChange={e=>setReg(x=>({...x,whatsapp:e.target.value}))} inputMode="tel" placeholder="WhatsApp com DDD" required/><input type="email" value={reg.email} onChange={e=>setReg(x=>({...x,email:e.target.value}))} placeholder="E-mail (opcional)"/><input type="password" value={reg.password} onChange={e=>setReg(x=>({...x,password:e.target.value}))} placeholder="Criar senha" required/><input type="password" value={reg.confirm} onChange={e=>setReg(x=>({...x,confirm:e.target.value}))} placeholder="Confirmar senha" required/><button disabled={busy}>CRIAR PRÉ-CADASTRO</button><button type="button" className="linkButton" onClick={()=>{setMode("login");setMsg("")}}>VOLTAR</button></form>);
 if(mode==="recovery")return card(<form onSubmit={change}><h1>CRIAR NOVA SENHA</h1><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Nova senha" required/><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Confirmar nova senha" required/><button>SALVAR NOVA SENHA</button><small>Use maiúscula, minúscula, número e símbolo.</small></form>);
 return card(<form onSubmit={enter}><h1>FORTE VENDAS</h1><p>ACESSO AO SISTEMA</p><input value={login} onChange={e=>setLogin(e.target.value)} placeholder="CPF ou e-mail" required/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha" required/><button disabled={busy}>ENTRAR</button><button type="button" className="linkButton" onClick={()=>{setMode("register");setMsg("")}}>PRIMEIRO ACESSO</button><button type="button" className="linkButton" onClick={forgot}>RECUPERAR SENHA PELO WHATSAPP</button></form>);
}
