import{useEffect,useState}from"react";import App from"./App.jsx";import{setAuthContext,supabase,supabaseConfigured}from"./supabase.js";
const recoveryRequested=new URLSearchParams(location.search).get("recovery")==="1"||location.hash.includes("type=recovery");
const LAST="forte_vendas_last_login";
const strong=s=>/^\d{6,}$/.test(s);
const digits=v=>String(v||"").replace(/\D/g,"");
export default function AuthGate(){
 const[ready,setReady]=useState(!supabaseConfigured),[session,setSession]=useState(null),[profile,setProfile]=useState(null),[pending,setPending]=useState(null),[mode,setMode]=useState(recoveryRequested?"recovery":"login"),[login,setLogin]=useState(()=>/^\d{11}$/.test(localStorage.getItem(LAST)||"")?localStorage.getItem(LAST):""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const[recoveryChannel,setRecoveryChannel]=useState("email"),[recoveryEmail,setRecoveryEmail]=useState("");
 const[recoveryPhone,setRecoveryPhone]=useState(""),[showRecoveryPhone,setShowRecoveryPhone]=useState(false);
 const[installEvent,setInstallEvent]=useState(null);const isIos=/iPad|iPhone|iPod/.test(navigator.userAgent);
 const[reg,setReg]=useState({nome:"",cpf:"",whatsapp:"",email:"",password:"",confirm:""});
 const[form,setForm]=useState({endereco:"",numero:"",bairro:"",cidade:"",uf:"",cep:"",complemento:"",contato_emergencia:""}),[identidade,setIdentidade]=useState(null),[comprovante,setComprovante]=useState(null);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session)).finally(()=>setReady(true));const{data}=supabase.auth.onAuthStateChange((event,next)=>{setSession(next);if(!next){setAuthContext(null);setProfile(null);setMode("login")}if(event==="PASSWORD_RECOVERY")setMode("recovery")});return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{const save=e=>{e.preventDefault();setInstallEvent(e)};window.addEventListener("beforeinstallprompt",save);return()=>window.removeEventListener("beforeinstallprompt",save)},[]);
 useEffect(()=>{if(!session||!supabase)return;setReady(false);supabase.from("fc_perfis").select("*").eq("user_id",session.user.id).maybeSingle().then(async({data,error})=>{if(error||!data){setMsg("CADASTRO NÃO LOCALIZADO.");setReady(true);return}setProfile(data);if(data.ativo){setAuthContext({user:session.user,profile:data});if(data.trocar_senha||recoveryRequested){setMode("recovery");setReady(true)}else setReady("authorized");return}const p=await supabase.from("fc_usuarios_pendentes").select("*").eq("auth_user_id",session.user.id).maybeSingle();setPending(p.data||null);if(p.data)setForm(x=>({...x,...Object.fromEntries(Object.keys(x).map(k=>[k,p.data?.[k]||""]))}));setMode("onboarding");setReady(true)})},[session]);
 if(!supabaseConfigured)return <App/>;if(ready==="authorized")return <App/>;if(!ready)return <div className="authPage"><div className="authCard">CARREGANDO…</div></div>;
 const enter=async e=>{e.preventDefault();if(!/^\d{11}$/.test(digits(login))||!strong(password))return setMsg("INFORME CPF E SENHA NUMÉRICA COM NO MÍNIMO 6 DÍGITOS.");setBusy(true);setMsg("ENTRANDO…");try{const x=await supabase.functions.invoke("login-cpf",{body:{cpf:digits(login),password}});if(x.error||!x.data?.access_token)throw x.error||new Error();const result=await supabase.auth.setSession({access_token:x.data.access_token,refresh_token:x.data.refresh_token});if(result.error)throw result.error;localStorage.setItem(LAST,digits(login));setMsg("")}catch{setMsg("CPF OU SENHA INVÁLIDOS, OU ACESSO NÃO AUTORIZADO.")}finally{setBusy(false)}};
 const register=async e=>{e.preventDefault();if(!strong(reg.password))return setMsg("A SENHA DEVE TER NO MÍNIMO 6 NÚMEROS.");if(reg.password!==reg.confirm)return setMsg("AS SENHAS NÃO COINCIDEM.");setBusy(true);const{data,error}=await supabase.functions.invoke("first-access",{body:reg});if(!error&&data?.access_token)await supabase.auth.setSession({access_token:data.access_token,refresh_token:data.refresh_token});let detail="";if(error?.context instanceof Response){try{detail=(await error.context.clone().json())?.error||""}catch{detail=""}}setMsg(error?(detail||"NÃO FOI POSSÍVEL CONCLUIR O PRÉ-CADASTRO."):data?.access_token?"ACESSO ATIVADO COM SUCESSO.":"PRÉ-CADASTRO CRIADO. COMPLETE A SEGUNDA ETAPA.");setBusy(false)};
 async function forgot(){setShowRecoveryPhone(true);if(!/^\d{11}$/.test(digits(login)))return setMsg("INFORME O CPF CADASTRADO.");if(recoveryChannel==="whatsapp"&&!recoveryPhone.trim())return setMsg("INFORME O WHATSAPP CADASTRADO COM DDD.");if(recoveryChannel==="email"&&!recoveryEmail.trim())return setMsg("INFORME O E-MAIL CADASTRADO.");setBusy(true);try{const{data,error}=await supabase.functions.invoke("recover-password-email",{body:{identificador:digits(login),canal:recoveryChannel,email:recoveryEmail.trim(),whatsapp:recoveryPhone.trim()}});if(error){let detail="NÃO FOI POSSÍVEL ENVIAR O LINK.";if(error.context instanceof Response){try{detail=(await error.context.clone().json()).error||detail}catch{}}setMsg(detail)}else setMsg(data.message)}catch{setMsg("VERIFIQUE A CONEXÃO E TENTE NOVAMENTE.")}finally{setBusy(false)}};
 const change=async e=>{
  e.preventDefault();
  if(!strong(password))return setMsg("A SENHA DEVE TER NO MÍNIMO 6 NÚMEROS.");
  if(password!==confirm)return setMsg("AS DUAS SENHAS ESTÃO DIFERENTES. DIGITE A MESMA SENHA NOS DOIS CAMPOS.");
  if(!session?.user?.id)return setMsg("O LINK EXPIROU. VOLTE AO LOGIN E SOLICITE UM NOVO LINK EM ESQUECI MINHA SENHA.");
  setBusy(true);setMsg("SALVANDO NOVA SENHA…");
  try{
   const{error}=await supabase.auth.updateUser({password});
   if(error)throw error;
   const result=await supabase.from("fc_perfis").update({trocar_senha:false}).eq("user_id",session.user.id).select("user_id");
   if(result.error||!result.data?.length){setMsg("SENHA SALVA, MAS NÃO FOI POSSÍVEL CONCLUIR A LIBERAÇÃO DO ACESSO. TENTE SALVAR NOVAMENTE.");return}
   setPassword("");setConfirm("");setMsg("SENHA ALTERADA COM SUCESSO.");location.replace("/");
  }catch(error){setMsg(error?.code==="same_password"?"ESCOLHA UMA SENHA DIFERENTE DA SENHA ATUAL.":"NÃO FOI POSSÍVEL SALVAR. VERIFIQUE A CONEXÃO OU SOLICITE UM NOVO LINK DE RECUPERAÇÃO.")}
  finally{setBusy(false)}
 };
 const install=async()=>{if(isIos)return setMsg("NO IPHONE: ABRA NO SAFARI, TOQUE EM COMPARTILHAR E DEPOIS EM ADICIONAR À TELA DE INÍCIO.");if(!installEvent)return setMsg("USE O MENU DO NAVEGADOR E ESCOLHA INSTALAR APLICATIVO OU ADICIONAR À TELA INICIAL.");await installEvent.prompt();setInstallEvent(null)};
 const upload=async(file,tipo)=>{if(!file)return"";const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_"),path=`${session.user.id}/${tipo}-${Date.now()}-${safe}`;const{error}=await supabase.storage.from("forte-vendas-cadastros").upload(path,file);if(error)throw error;return path};
 const submit=async e=>{e.preventDefault();if(!form.endereco||!form.numero||!form.bairro||!form.cidade||!form.uf||digits(form.cep).length!==8)return setMsg("PREENCHA O ENDEREÇO COMPLETO.");if(!identidade&&!pending?.documento_identificacao_path)return setMsg("ANEXE O DOCUMENTO DE IDENTIFICAÇÃO.");if(!comprovante&&!pending?.comprovante_endereco_path)return setMsg("ANEXE O COMPROVANTE DE ENDEREÇO.");setBusy(true);try{const doc=identidade?await upload(identidade,"identificacao"):pending.documento_identificacao_path,end=comprovante?await upload(comprovante,"endereco"):pending.comprovante_endereco_path;const{error}=await supabase.from("fc_usuarios_pendentes").update({...form,cep:digits(form.cep),documento_identificacao_path:doc,comprovante_endereco_path:end,status:"EM_ANALISE",enviado_em:new Date().toISOString()}).eq("auth_user_id",session.user.id);if(error)throw error;setPending(x=>({...x,...form,status:"EM_ANALISE"}));setMsg("CADASTRO ENVIADO. AGUARDE A APROVAÇÃO DO ADMINISTRADOR.")}catch(err){setMsg(err.message||"NÃO FOI POSSÍVEL ENVIAR.")}setBusy(false)};
 const card=children=><div className="authPage"><div className="authCard">{children}<button type="button" className="linkButton" onClick={install}>INSTALAR APLICATIVO — ANDROID, IPHONE OU DESKTOP</button>{msg&&<div className="authMessage" role="status" aria-live="polite">{msg}</div>}</div></div>;
 if(mode==="onboarding")return card(<>{pending?.status==="EM_ANALISE"?<><h1>FORTE VENDAS</h1><h2>CADASTRO EM ANÁLISE</h2><p>O administrador conferirá os documentos e definirá suas funções. Você receberá o aviso no WhatsApp cadastrado.</p><button onClick={()=>supabase.auth.signOut()}>SAIR</button></>:<form onSubmit={submit}><h1>SEGUNDA ETAPA</h1><p>COMPLETE SEUS DADOS PARA ANÁLISE</p>{["endereco","numero","bairro","cidade","uf","cep","complemento","contato_emergencia"].map(k=><input key={k} value={form[k]} onChange={e=>setForm(x=>({...x,[k]:e.target.value}))} placeholder={k.replaceAll("_"," ").toUpperCase()} required={!["complemento","contato_emergencia"].includes(k)}/>)}<label>DOCUMENTO DE IDENTIFICAÇÃO<input type="file" accept=".pdf,image/*" onChange={e=>setIdentidade(e.target.files?.[0]||null)}/></label><label>COMPROVANTE DE ENDEREÇO<input type="file" accept=".pdf,image/*" onChange={e=>setComprovante(e.target.files?.[0]||null)}/></label><button disabled={busy}>ENVIAR PARA ANÁLISE</button><button type="button" className="linkButton" onClick={()=>supabase.auth.signOut()}>SAIR</button></form>}</>);
 if(mode==="register")return card(<form onSubmit={register}><h1>FORTE VENDAS</h1><p>ACEITAR CONVITE</p><small>Use os mesmos dados informados pelo administrador no convite.</small><input value={reg.nome} onChange={e=>setReg(x=>({...x,nome:e.target.value}))} placeholder="Nome completo" required/><input value={reg.cpf} onChange={e=>setReg(x=>({...x,cpf:e.target.value}))} inputMode="numeric" placeholder="CPF" required/><input value={reg.whatsapp} onChange={e=>setReg(x=>({...x,whatsapp:e.target.value}))} inputMode="tel" placeholder="WhatsApp com DDD" required/><input type="email" value={reg.email} onChange={e=>setReg(x=>({...x,email:e.target.value}))} placeholder="E-mail (opcional)"/><input type="password" inputMode="numeric" minLength={6} pattern="[0-9]{6,}" value={reg.password} onChange={e=>setReg(x=>({...x,password:digits(e.target.value)}))} placeholder="Criar senha" required/><input type="password" inputMode="numeric" minLength={6} pattern="[0-9]{6,}" value={reg.confirm} onChange={e=>setReg(x=>({...x,confirm:digits(e.target.value)}))} placeholder="Confirmar senha" required/><button disabled={busy}>ACEITAR E CONTINUAR</button><button type="button" className="linkButton" onClick={()=>{setMode("login");setMsg("")}}>VOLTAR</button></form>);
 if(mode==="recovery")return card(<form onSubmit={change}><h1>CRIAR NOVA SENHA</h1><label htmlFor="new-password">Nova senha</label><input id="new-password" type="password" inputMode="numeric" minLength={6} pattern="[0-9]{6,}" autoComplete="new-password" value={password} onChange={e=>setPassword(digits(e.target.value))} placeholder="Digite a nova senha" aria-describedby="password-rules" required/><label htmlFor="confirm-password">Confirmar nova senha</label><input id="confirm-password" type="password" inputMode="numeric" minLength={6} pattern="[0-9]{6,}" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(digits(e.target.value))} placeholder="Repita a mesma senha" required/><small id="password-rules">Somente números, com no mínimo 6 dígitos.</small><button disabled={busy}>{busy?"SALVANDO…":"SALVAR NOVA SENHA"}</button><button type="button" className="linkButton" disabled={busy} onClick={()=>supabase.auth.signOut()}>VOLTAR AO LOGIN</button></form>);
 return card(<form onSubmit={enter}><h1>FORTE VENDAS</h1><p>ACESSO AO SISTEMA</p><input value={login} onChange={e=>setLogin(digits(e.target.value).slice(0,11))} inputMode="numeric" maxLength={11} pattern="[0-9]{11}" placeholder="CPF" required/><input type="password" inputMode="numeric" minLength={6} pattern="[0-9]{6,}" value={password} onChange={e=>setPassword(digits(e.target.value))} placeholder="Senha numérica — mínimo 6 dígitos" required/><button disabled={busy}>ENTRAR</button><button type="button" className="linkButton" onClick={()=>{setMode("register");setMsg("")}}>ACEITAR CONVITE</button>{showRecoveryPhone&&<><label>RECUPERAR POR<select value={recoveryChannel} onChange={e=>setRecoveryChannel(e.target.value)}><option value="email">E-MAIL</option><option value="whatsapp">WHATSAPP</option></select></label>{recoveryChannel==="email"?<label>E-MAIL CADASTRADO<input type="email" autoComplete="email" value={recoveryEmail} onChange={e=>setRecoveryEmail(e.target.value)}/></label>:<label>WHATSAPP CADASTRADO COM DDD<input type="tel" autoComplete="tel" value={recoveryPhone} onChange={e=>setRecoveryPhone(e.target.value)} placeholder="DDD e número"/></label>}</>}<button type="button" className="linkButton" disabled={busy} onClick={forgot}>{showRecoveryPhone?"ENVIAR LINK DE RECUPERAÇÃO":"CRIAR OU RECUPERAR SENHA"}</button></form>);
}
