import{useEffect,useState}from"react";import App from"./App.jsx";import{setAuthContext,supabase,supabaseConfigured}from"./supabase.js";
const LAST_EMAIL_KEY="forte_vendas_last_email";\nconst PROD_URL="https://forte-vendas.onrender.com";
const valid=s=>s.length>=9&&/[A-Z]/.test(s)&&/[a-z]/.test(s)&&/\d/.test(s)&&/[^A-Za-z0-9]/.test(s)&&!/(012|123|234|345|456|567|678|789|987|876|765|654|543|432|321|210)/.test(s);
export default function AuthGate(){const[ready,setReady]=useState(!supabaseConfigured),[session,setSession]=useState(null),[recovery,setRecovery]=useState(false),[email,setEmail]=useState(()=>{try{return localStorage.getItem(LAST_EMAIL_KEY)||""}catch{return""}}),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[message,setMessage]=useState("");
useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session)).finally(()=>setReady(true));const{data}=supabase.auth.onAuthStateChange((event,next)=>{setSession(next);if(!next){setAuthContext(null);setReady(true);setRecovery(false)}if(event==="PASSWORD_RECOVERY")setRecovery(true)});return()=>data.subscription.unsubscribe()},[]);
useEffect(()=>{if(!session||!supabase)return;let timer;const reset=()=>{clearTimeout(timer);timer=setTimeout(()=>supabase.auth.signOut(),15*60*1000)};const events=["mousedown","keydown","touchstart","scroll"];events.forEach(e=>window.addEventListener(e,reset,{passive:true}));reset();return()=>{clearTimeout(timer);events.forEach(e=>window.removeEventListener(e,reset))}},[session]);
useEffect(()=>{if(!session||!supabase)return;supabase.from("fc_perfis").select("*").eq("user_id",session.user.id).maybeSingle().then(({data,error})=>{if(error||!data?.ativo){setMessage("USUÁRIO AINDA NÃO AUTORIZADO PELO MASTER.");return}setAuthContext({user:session.user,profile:data});if(data.trocar_senha||recovery){setRecovery(true);setReady(true);setMessage(data.trocar_senha?"CRIE UMA NOVA SENHA PARA LIBERAR O PRIMEIRO ACESSO.":"");return}setReady("authorized")})},[session,recovery]);
if(!supabaseConfigured)return <><div className="cloudNotice">MODO LOCAL — SUPABASE AINDA NÃO CONFIGURADO</div><App/></>;if(ready==="authorized")return <App/>;if(!ready)return <div className="authPage"><div className="authCard">CARREGANDO FORTE VENDAS…</div></div>;
const login=async e=>{e.preventDefault();setMessage("ENTRANDO…");const normalized=email.trim().toLowerCase();const{error}=await supabase.auth.signInWithPassword({email:normalized,password});if(!error){try{localStorage.setItem(LAST_EMAIL_KEY,normalized)}catch{}}setMessage(error?"E-MAIL OU SENHA INVÁLIDOS.":"")};const useOtherAccount=()=>{try{localStorage.removeItem(LAST_EMAIL_KEY)}catch{}setEmail("");setPassword("");setMessage("")};const forgot=async()=>{if(!email)return setMessage("INFORME O E-MAIL CADASTRADO.");const{error}=await supabase.auth.resetPasswordForEmail(email.trim().toLowerCase(),{redirectTo:PROD_URL+"/?recovery=1"});setMessage(error?"NÃO FOI POSSÍVEL ENVIAR O E-MAIL.":"LINK DE RECUPERAÇÃO ENVIADO. VERIFIQUE O E-MAIL.")};const change=async e=>{e.preventDefault();if(!valid(password))return setMessage("A SENHA NÃO ATENDE ÀS REGRAS DE SEGURANÇA.");if(password!==confirm)return setMessage("AS SENHAS NÃO COINCIDEM.");const{error}=await supabase.auth.updateUser({password});if(error)return setMessage("NÃO FOI POSSÍVEL ALTERAR A SENHA.");await supabase.from("fc_perfis").update({trocar_senha:false}).eq("user_id",session.user.id);setRecovery(false);setMessage("SENHA ALTERADA COM SUCESSO.");setReady("authorized")};
return <div className="authPage"><form className="authCard" onSubmit={recovery?change:login}><h1>FORTE VENDAS</h1><p>{recovery?"CRIAR NOVA SENHA":"ACESSO AO SISTEMA"}</p>{!recovery&&<input type="text" inputMode="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mail" required/>}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder={recovery?"Nova senha":"Senha"} required/>{recovery&&<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Confirmar nova senha" required/>}<button type="submit">{recovery?"SALVAR NOVA SENHA":"ENTRAR"}</button>{!recovery&&<><button className="linkButton" type="button" onClick={forgot}>ESQUECI MINHA SENHA</button>{email&&<button className="linkButton" type="button" onClick={useOtherAccount}>USAR OUTRA CONTA</button>}</>}{message&&<div className="authMessage">{message}</div>}{recovery&&<small>Use maiúscula, minúscula, número e caractere especial; não use sequência de três números.</small>}</form></div>}
