import React, {useEffect, useRef, useState} from 'react';
export function Icon({name='grid'}){const paths={menu:'M4 6h16M4 12h16M4 18h16',home:'m3 10 9-7 9 7M5 9v12h14V9M9 21v-8h6v8',plus:'M12 4v16M4 12h16',file:'M6 3h8l4 4v14H6zM14 3v5h4M9 12h6M9 16h6',truck:'M3 6h11v11H3zM14 10h4l3 4v3h-7M6 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4M18 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4',box:'m3 7 9-4 9 4-9 4zM3 7v10l9 4 9-4V7M12 11v10',users:'M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M2 21v-3a6 6 0 0 1 12 0v3M17 4a4 4 0 0 1 0 8M17 15a5 5 0 0 1 5 5',check:'m5 12 4 4L19 6',money:'M12 2v20M18 6H9a3 3 0 0 0 0 6h6a3 3 0 0 1 0 6H6',grid:'M4 4h5v5H4zM15 4h5v5h-5zM4 15h5v5H4zM15 15h5v5h-5z'};return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.grid}/></svg>}
export function Brand({label}){return <div className="forte-brand"><svg viewBox="0 0 110 20" aria-hidden="true"><path fill="currentColor" d="M0 20 55 0 110 20 55 9z"/></svg><strong>FORTE</strong><span>ATACAREJO</span><b>{label}</b></div>}
export function MenuButton({drawer}){return <button type="button" className="forte-menu-toggle" aria-label="Abrir menu" aria-controls="forte-drawer" aria-expanded={drawer.open} onClick={()=>drawer.setOpen(!drawer.open)}><Icon name="menu"/></button>}
export function useDrawer(){const[open,setOpen]=useState(false);const ref=useRef(null);useEffect(()=>{if(!open)return;const previous=document.activeElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';const panel=ref.current;const focusable=()=>[...(panel?.querySelectorAll('button:not([disabled]),a[href],input,select,[tabindex="0"]')||[])].filter(x=>x.getClientRects().length);focusable()[0]?.focus();function key(e){if(e.key==='Escape'){e.preventDefault();setOpen(false)}if(e.key==='Tab'){const list=focusable(),first=list[0],last=list[list.length-1];if(!first){e.preventDefault();return}if(e.shiftKey&&(document.activeElement===first||!panel?.contains(document.activeElement))){e.preventDefault();last.focus()}else if(!e.shiftKey&&(document.activeElement===last||!panel?.contains(document.activeElement))){e.preventDefault();first.focus()}}}document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);previous?.focus?.()}},[open]);return{open,setOpen,ref}}
export function Drawer({drawer,children}){return <>{drawer.open&&<button className="forte-menu-overlay" aria-label="Fechar menu" tabIndex={-1} onClick={()=>drawer.setOpen(false)}/>}<aside id="forte-drawer" ref={drawer.ref} className={'forte-drawer'+(drawer.open?' is-open':'')} role="dialog" aria-modal={drawer.open||undefined} aria-label="Menu do sistema" aria-hidden={!drawer.open} inert={!drawer.open?true:undefined} onClick={e=>{if(e.target.closest('button,a')&&!e.target.closest('[data-menu-close]'))drawer.setOpen(false)}}><button data-menu-close className="forte-drawer-close" aria-label="Fechar menu" onClick={()=>drawer.setOpen(false)}>×</button>{children}</aside></>}
export function BottomNav({items,active,onSelect,onMore}){return <nav className="forte-bottom-nav" aria-label="Navegação principal">{items.map(x=><button type="button" key={x.id} aria-current={active===x.id?'page':undefined} className={(x.id===active?'is-active ':'')+(x.primary?'is-primary':'')} onClick={()=>onSelect(x.id)}><Icon name={x.icon}/><span>{x.label}</span></button>)}{onMore&&<button type="button" onClick={onMore}><Icon/><span>Mais</span></button>}</nav>}
export function Hero({title,description,icon='box'}){return <section className="forte-hero"><div><h2>{title}</h2><p>{description}</p></div><Icon name={icon}/></section>}
export function Metrics({items}){return <section className="forte-metrics" aria-label="Resumo">{items.map((x,i)=><article key={x.label}><div className={'forte-metric-icon color-'+i}><Icon name={x.icon}/></div><strong>{x.value}</strong><span>{x.label}</span></article>)}</section>}
export function Shortcuts({items}){return <section className="forte-shortcuts" aria-label="Ações rápidas">{items.map((x,i)=><button type="button" className={x.primary?'primary-action':''} key={x.label} onClick={x.onClick}><span className={'forte-shortcut-icon color-'+i}><Icon name={x.icon}/></span><span><b>{x.label}</b><small>{x.description}</small></span><span aria-hidden="true">›</span></button>)}</section>}
