const GMAIL_SCOPE="https://www.googleapis.com/auth/gmail.readonly";
const API="https://gmail.googleapis.com/gmail/v1/users/me";
let gisPromise;
function loadGIS(){if(window.google?.accounts?.oauth2)return Promise.resolve();if(gisPromise)return gisPromise;gisPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.defer=true;s.onload=()=>resolve();s.onerror=()=>reject(new Error('NÃO FOI POSSÍVEL CARREGAR O GOOGLE IDENTITY SERVICES.'));document.head.appendChild(s)});return gisPromise}
function apiFetch(path,token){return fetch(`${API}${path}`,{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{if(!r.ok){let t='';try{t=await r.text()}catch{}throw new Error(`GMAIL API ${r.status}: ${t||r.statusText}`)}return r.json()})}
export async function getGmailProfile(token){return apiFetch('/profile',token)}
export async function authorizeGmail(clientId){if(!clientId)throw new Error('INFORME O GOOGLE OAUTH CLIENT ID.');await loadGIS();return new Promise((resolve,reject)=>{try{const c=window.google.accounts.oauth2.initTokenClient({client_id:clientId,scope:GMAIL_SCOPE,prompt:'consent',callback:(resp)=>{if(resp?.error)return reject(new Error(resp.error));if(!resp?.access_token)return reject(new Error('TOKEN DO GMAIL NÃO RECEBIDO.'));resolve(resp.access_token)}});c.requestAccessToken()}catch(e){reject(e)}})}
function headersMap(h=[]){return Object.fromEntries(h.map(x=>[String(x.name||'').toLowerCase(),x.value||'']))}
function walkParts(parts=[],out=[]){for(const p of parts||[]){if(p.filename)out.push({filename:p.filename,mimeType:p.mimeType||'',attachmentId:p.body?.attachmentId||'',size:p.body?.size||0});if(p.parts)walkParts(p.parts,out)}return out}
export function classifyGmailDocument({subject='',filename='',from=''}){const s=`${subject} ${filename} ${from}`.toLowerCase();if(/comprovante|pagamento|liquida|baixa|quitad/.test(s))return 'COMPROVANTE_PAGAMENTO';if(/boleto|cobran[cç]a|titulo|t[ií]tulo/.test(s))return 'TITULO_BOLETO';if(/\.xml$/i.test(filename)||/nfe|nf-e|nota fiscal|danfe/.test(s))return 'NFE';return 'DOCUMENTO'}
export async function searchGmail(token,query,maxResults=50){const q=encodeURIComponent(query||'newer_than:30d has:attachment in:inbox -in:spam -in:trash');const list=await apiFetch(`/messages?q=${q}&maxResults=${Math.max(1,Math.min(Number(maxResults)||50,100))}`,token);const msgs=list.messages||[];const out=[];for(const m of msgs){const full=await apiFetch(`/messages/${m.id}?format=full`,token);const h=headersMap(full.payload?.headers||[]);const atts=walkParts(full.payload?.parts||[]);for(const a of atts){out.push({messageId:m.id,threadId:full.threadId,subject:h.subject||'',from:h.from||'',to:h.to||'',date:h.date||'',snippet:full.snippet||'',...a,tipo:classifyGmailDocument({subject:h.subject||'',filename:a.filename,from:h.from||''})})}}return out}
function b64urlToBlob(data,mime='application/octet-stream'){const norm=String(data||'').replace(/-/g,'+').replace(/_/g,'/');const bin=atob(norm);const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return new Blob([bytes],{type:mime})}
export async function downloadGmailAttachment(token,item){if(!item?.messageId||!item?.attachmentId)throw new Error('ANEXO SEM IDENTIFICADOR PARA DOWNLOAD.');const r=await apiFetch(`/messages/${item.messageId}/attachments/${item.attachmentId}`,token);return b64urlToBlob(r.data,item.mimeType)}

export async function hashBlob(blob){const buf=await blob.arrayBuffer();const digest=await crypto.subtle.digest('SHA-256',buf);return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('')}
