import {useState} from 'react';
import {collectionReport,todayBrazil,normalize} from './itau-report.js';
import {createCollectionPDF,money,dateBR} from './itau-report-pdf.js';
import './itau-report.css';
export default function ItauCollectionsReport({data}){
 const [filters,setFilters]=useState({query:'',client:'',status:'ABERTOS',start:'',end:'',group:false});const invalid=filters.start&&filters.end&&filters.start>filters.end;
 const report=collectionReport(data,filters);const connection=(data.bankConnections||[]).find(c=>/ITAU/.test(normalize(c.provedor)))||{};
 const update=(k,v)=>setFilters(f=>({...f,[k]:v}));
 return <section className="icr"><div className="icr-heading"><div><span className="icr-eyebrow">CARTEIRA DE COBRANÇAS</span><h3>Boletos Itaú em aberto</h3><p>Referência: {dateBR(todayBrazil())} • dados registrados no sistema</p></div><button type="button" disabled={!!invalid} onClick={()=>createCollectionPDF(report,filters,connection).save('FORTE-COBRANCAS-ITAU-'+report.today+'.pdf')}>Baixar relatório PDF</button></div>
 <div className="icr-filters"><label>Buscar cliente ou número<input aria-label="Buscar cobrança" placeholder="Nome, nosso número, seu número ou venda" value={filters.query} onChange={e=>update('query',e.target.value)}/></label><label>Cliente<select aria-label="Cliente da cobrança" value={filters.client} onChange={e=>update('client',e.target.value)}><option value="">Todos os clientes</option>{report.clients.map(c=><option key={c.key} value={c.key}>{c.name}</option>)}</select></label><label>Situação<select aria-label="Situação da cobrança" value={filters.status} onChange={e=>update('status',e.target.value)}>{['ABERTOS','VENCIDO','VENCE HOJE','A VENCER'].map(s=><option key={s}>{s}</option>)}</select></label><label>Vencimento de<input aria-label="Vencimento de" type="date" value={filters.start} onChange={e=>update('start',e.target.value)}/></label><label>Vencimento até<input aria-label="Vencimento até" type="date" value={filters.end} onChange={e=>update('end',e.target.value)}/></label></div>
 <div className="icr-tools"><label><input type="checkbox" checked={filters.group} onChange={e=>update('group',e.target.checked)}/> Agrupar por cliente</label><button type="button" className="secondary" onClick={()=>setFilters({query:'',client:'',status:'ABERTOS',start:'',end:'',group:false})}>Limpar filtros</button></div>{invalid&&<p className="icr-warning" role="alert">A data inicial deve ser anterior ou igual à data final.</p>}
 <div className="icr-cards">{[['Total em aberto',report.totals.open,'total'],['Vencidos',report.totals.overdue,'late'],['Vencem hoje',report.totals.dueToday,'today'],['A vencer',report.totals.future,'future']].map(([label,value,cls])=><article key={label} className={cls}><span>{label}</span><strong>{money(value)}</strong></article>)}</div><p className="icr-note">{report.totals.count} títulos • {report.groups.length} clientes nos filtros. Saldo considera os recebimentos registrados; encargos bancários não confirmados não são somados.</p>
 <div className="icr-aging">{report.aging.map(a=><span key={a.label}><b>{a.label}</b>{money(a.total)} · {a.count} títulos</span>)}</div>
 <div className="icr-table-wrap"><table><thead><tr>{['Pagador','Venda / parcela','Vencimento','Atraso','Valor original','Saldo aberto','Nosso número / carteira','Seu número','Situação / DDA'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{report.rows.map((r,i)=><tr key={r.id||i}><td><b>{r.name}</b>{r.legal!==r.name&&<small>{r.legal}</small>}</td><td>{r.numeroVenda||'—'}<small>{r.parcela||1}/{r.totalParcelas||1}</small></td><td>{dateBR(r.vencimento)}</td><td>{r.days?r.days+' dias':'—'}</td><td>{money(r.original)}</td><td><b>{money(r.open)}</b></td><td>{r.nossoNumero}<small>Carteira {r.carteira||connection.carteira||'—'}</small></td><td>{r.seuNumero||'—'}</td><td><span className={'icr-status '+(r.days?'late':'')}>{r.situation}</span><small>DDA: {r.dda}</small></td></tr>)}</tbody><tfoot><tr><td colSpan="5">Total · {report.totals.count} títulos</td><td colSpan="4">{money(report.totals.open)}</td></tr></tfoot></table></div>{!report.rows.length&&<p className="icr-empty">Nenhum boleto emitido em aberto corresponde aos filtros.</p>}
 {report.groups.length>0&&<details className="icr-clients"><summary>Resumo por cliente · maior saldo vencido primeiro</summary>{report.groups.map(c=><div key={c.key}><b>{c.name}</b><span>{c.count} títulos</span><span>Em aberto: {money(c.open)}</span><span>Vencido: {money(c.overdue)}</span></div>)}</details>}
 {report.pending.length>0&&<p className="icr-warning">{report.pending.length} solicitações ou cadastros sem nosso número, valor ou vencimento válidos estão fora dos totais. Confira a emissão e os dados do boleto.</p>}
 </section>;
}
