import { useMemo, useState } from "react";
const money=(v)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function ItauPagamentos({data,onChange,currentUser}){
  const [selected,setSelected]=useState([]), [message,setMessage]=useState("");
  const connection=(data.bankConnections||[]).find((x)=>String(x.provedor||"").toUpperCase().includes("ITAU"))||{};
  const enabled=connection.pagamentosHabilitados===true && connection.pagamentosHomologados===true;
  const ready=useMemo(()=>(data.contasPagar||[]).filter((x)=>x.linhaDigitavel&&!/PAGO|LIQUIDADO|CONCILIADO|CANCELADO/.test(String(x.status||"").toUpperCase())),[data.contasPagar]);
  const total=ready.filter((x)=>selected.includes(x.id)).reduce((s,x)=>s+Number(x.valor||0),0);
  function send(){if(!enabled)return setMessage("ENVIO PRODUTIVO BLOQUEADO: O ITAÚ AINDA PRECISA HABILITAR E HOMOLOGAR A API/PRODUTO DE PAGAMENTOS.");if(!selected.length)return setMessage("SELECIONE AO MENOS UM TÍTULO.");if(!confirm(`CONFIRMA O ENVIO DE ${selected.length} TÍTULO(S), TOTAL ${money(total)}, PARA AUTORIZAÇÃO NO ITAÚ?`))return;const key=crypto.randomUUID();onChange((d)=>({...d,pagamentosItau:[...(d.pagamentosItau||[]),{id:key,idempotencyKey:key,tituloIds:selected,total,status:"ENVIADO",enviadoPor:currentUser?.nome||"USUÁRIO",enviadoEm:new Date().toISOString()}],contasPagar:(d.contasPagar||[]).map((x)=>selected.includes(x.id)?{...x,status:"ENVIADO — AGUARDANDO AUTORIZAÇÃO",pagamentoItauId:key}:x),auditoria:[...(d.auditoria||[]),{id:crypto.randomUUID(),acao:"LOTE ENVIADO PARA PAGAMENTO ITAÚ",detalhe:`${selected.length} título(s) • ${money(total)} • idempotência ${key}`,usuario:currentUser?.nome||"USUÁRIO",dataHora:new Date().toISOString()}]}));setSelected([]);setMessage("LOTE ENVIADO. OS TÍTULOS SÓ SERÃO BAIXADOS APÓS CONFIRMAÇÃO BANCÁRIA.")}
  return <section className="subCard"><div className="sectionHead"><div><h3>ITAÚ PAGAMENTOS — CONTAS A PAGAR</h3><p>SELEÇÃO, TOTALIZAÇÃO, AUTORIZAÇÃO, RETORNO E CONCILIAÇÃO.</p></div><span className={enabled?"statusOk":"statusWarn"}>{enabled?"API HABILITADA / HOMOLOGADA":"DEPENDÊNCIA EXTERNA — DESATIVADO"}</span></div><div className="alert warn">ENVIADO NÃO SIGNIFICA PAGO. A BAIXA OCORRE SOMENTE APÓS CONFIRMAÇÃO INEQUÍVOCA DO BANCO.</div>{message&&<div className="alert">{message}</div>}<div className="bulkBar"><button className="ghost dark" onClick={()=>setSelected(ready.map((x)=>x.id))}>MARCAR TODOS</button><button className="ghost dark" onClick={()=>setSelected([])}>DESMARCAR</button><b>{selected.length} TÍTULO(S) • {money(total)}</b><button disabled={!enabled} onClick={send}>ENVIAR PARA PAGAMENTO ITAÚ</button></div><div className="titleList">{ready.map((x)=><label className="titleRow" key={x.id}><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>setSelected((a)=>a.includes(x.id)?a.filter((id)=>id!==x.id):[...a,x.id])}/><b>{x.fornecedor}</b><span>{x.titulo}</span><span>{money(x.valor)}</span><span>{x.vencimento||"—"}</span><span>{x.status}</span></label>)}</div>{!ready.length&&<p className="muted">NENHUM TÍTULO CONFERIDO COM LINHA DIGITÁVEL PRONTO PARA PAGAMENTO.</p>}</section>;
}
