import {useState} from 'react';
import {purchaseReport,loadReport,salesReport,receiptReport} from './orders-reports';
const save=(d,name)=>d.save(name+'.pdf');
export function OrderMirror({order,run}){
 const [open,setOpen]=useState(false),[confirmed,setConfirmed]=useState(false);
 return <><button type="button" className="secondary" onClick={()=>{setOpen(!open);setConfirmed(false);}}>◉ Ver espelho do pedido</button>{open&&<div className="ow-mirror"><h4>{order.numero} • {order.fornecedor}</h4><p>Unidade: {order.unidade} • Expedição: {order.origem} • Destino: {order.destino}</p><p>Motorista: {order.motorista||'A definir'} • Placas: {(order.placas||[]).join(' / ')}</p><p>Pagamento: {order.pagamento} • {order.modalidadeFrete} • {order.regraPallets} • {order.palletQuantidade} pallets</p>{order.itens.map(i=><p key={i.produtoId}>{i.qtd} • {i.produto} • unitário {Number(i.custoUnitario).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} • total {Number(i.total).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</p>)}<div className="ow-actions"><button type="button" className="secondary" onClick={()=>save(purchaseReport(order),order.numero+'-ESPELHO')}>PDF do espelho</button><button type="button" onClick={()=>run({action:'SUPPLIER_PREVIEW',id:order.id}).then(()=>setConfirmed(true)).catch(()=>{})}>Conferi este pedido</button></div>{confirmed&&<div className="ow-actions">{[['WHATSAPP','Enviar pelo WhatsApp'],['EMAIL','Enviar pelo e-mail'],['AMBOS','Enviar pelos dois']].map(([canal,label])=><button type="button" key={canal} onClick={()=>run({action:'SUPPLIER_SEND',id:order.id,canal}).catch(()=>{})}>{label}</button>)}</div>}</div>}</>;
}
export function SalesOperations({data,groups,run,busy}){
 const [editing,setEditing]=useState(null),[qty,setQty]=useState(''),[reason,setReason]=useState('');
 return <><h3>Painel de pedidos de venda</h3><button type="button" className="secondary" onClick={()=>save(salesReport(groups),'FORTE-PEDIDOS-VENDA')}>Relatório de pedidos • PDF</button>{groups.map(g=><article className="ow-record" key={g.id}><h4>{g.numero} • {g.cliente}</h4>{g.rows.map(v=><div key={v.id}><p>{v.qtd} • {v.produto} • {v.status} • {v.cargaId||'Carga a definir'}</p><button type="button" disabled={busy||v.status==='ENTREGUE'} className="secondary" onClick={()=>{setEditing(v);setQty(v.qtd);setReason('Adequação à capacidade do carregamento');}}>Ajustar quantidade</button>{(v.ajustes||[]).map(a=><small key={a.id}>{a.antes} → {a.depois} • {a.motivo} • sem saldo pendente</small>)}</div>)}<button type="button" className="secondary" onClick={()=>{const evidencia=prompt('Referência da autorização do cliente para receber mensagens:');if(evidencia)run({action:'CUSTOMER_CONSENT',clienteId:g.rows[0].clienteId,autorizado:true,evidencia}).catch(()=>{});}}>Registrar autorização do WhatsApp</button></article>)}{editing&&<div className="ow-preview" role="region" aria-label="Ajustar pedido"><h4>{editing.numeroVenda} • {editing.produto}</h4><label>Quantidade final<input type="number" min="1" max={Number(editing.qtd)-1} value={qty} onChange={e=>setQty(e.target.value)}/></label><label>Motivo<input value={reason} onChange={e=>setReason(e.target.value)}/></label><p>A quantidade anterior fica no histórico. O ajuste encerra a diferença sem saldo pendente e prepara a mensagem ao cliente.</p><button type="button" onClick={()=>run({action:'SALE_ADJUST',vendaId:editing.id,qtd:qty,motivo:reason}).then(()=>setEditing(null)).catch(()=>{})}>Salvar ajuste e preparar aviso</button><button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancelar</button></div>}</>;
}
export function CommunicationsPanel({data,onDispatch}){
 const [busy,setBusy]=useState(false),[status,setStatus]=useState('');
 const labels={QUEUED:'Envio pendente',BLOCKED:'Bloqueado',SENDING:'Em processamento',UNCERTAIN:'Resultado incerto — conferir',SENT:'Aceito pelo provedor',DELIVERED:'Entregue',READ:'Lido',FAILED:'Falha',CANCELLED:'Substituído'};
 return <section className="ow-record"><h3>WhatsApp e e-mail • acompanhamento</h3><button type="button" disabled={busy} onClick={async()=>{setBusy(true);try{setStatus(await onDispatch());}catch(e){setStatus(e.message);}finally{setBusy(false);}}}>Processar envios pendentes</button>{status&&<p role="status">{status}</p>}{(data.comunicacoes||[]).slice().reverse().map(j=><article key={j.id} className="ow-record"><b>{j.reference} • {j.canal} • {labels[j.state]||j.state}</b><p>{j.message}</p>{j.reason&&<small>{j.reason}</small>}{j.reply&&<><p>Resposta: {j.reply.answer} • {new Date(j.reply.receivedAt).toLocaleString('pt-BR')}</p><button type="button" className="secondary" onClick={()=>save(receiptReport(j),j.reference+'-CONFIRMACAO-ENTREGA')}>Imprimir confirmação • PDF</button></>}</article>)}{(data.retornosCliente||[]).map(r=><p key={r.providerId}>Resposta de cliente para conferência: {r.from} • {r.at} • vínculo não confirmado.</p>)}{(data.retornosFornecedor||[]).filter(r=>r.state==='CONFERIR').map(r=><p key={r.providerId}>Retorno para conferência: {r.text} • {r.reason}</p>)}</section>;
}
export function LoadReportButton({data,load}){return <button type="button" className="secondary" onClick={()=>save(loadReport(data,load),load.codigo+'-DOSSIE')}>Relatório da carga • PDF</button>;}
