import React,{useState}from"react";

async function digest(value){const bytes=new TextEncoder().encode(value);const hash=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(hash)).map(x=>x.toString(16).padStart(2,"0")).join("")}

export default function PaymentSettingsV47({data,onChange,currentUser,onClose}){
 const [unlocked,setUnlocked]=useState(false);const configured=!!data.settings?.masterPasswordHash;const isMaster=!!currentUser?.master;
 async function authorize(){if(!isMaster)return alert("OPERAÇÃO RESTRITA. SOLICITE AUTORIZAÇÃO AO USUÁRIO MASTER.");const senha=prompt(configured?"INFORME A SENHA DO USUÁRIO MASTER:":"CRIE A SENHA INICIAL DO USUÁRIO MASTER (MÍNIMO 8 CARACTERES):");if(!senha)return;if(senha.length<8)return alert("A SENHA MASTER PRECISA TER AO MENOS 8 CARACTERES.");const senhaHash=await digest(senha);if(configured&&senhaHash!==data.settings.masterPasswordHash)return alert("SENHA MASTER INVÁLIDA.");if(!configured)onChange(d=>({...d,settings:{...d.settings,masterPasswordHash:senhaHash,masterConfiguradoEm:new Date().toISOString()},auditoria:[...(d.auditoria||[]),{id:`aud-${Date.now()}`,acao:"SENHA MASTER CONFIGURADA",usuario:currentUser?.nome||"",dataHora:new Date().toISOString()}]}));setUnlocked(true)}
 function patch(id,key,value){if(!unlocked)return alert("AUTORIZE A SESSÃO COM A SENHA MASTER.");onChange(d=>({...d,pagamentos:(d.pagamentos||[]).map(p=>p.id===id?{...p,[key]:value,parametrizadoEm:new Date().toISOString(),parametrizadoPor:currentUser?.nome||""}:p),auditoria:[...(d.auditoria||[]),{id:`aud-${Date.now()}-${id}`,acao:"PARAMETRIZAÇÃO DE FORMA DE PAGAMENTO",detalhe:`${id} • ${key}: ${value?"SIM":"NÃO"}`,usuario:currentUser?.nome||"",dataHora:new Date().toISOString()}]}))}
 return <section className="card"><div className="sectionHead"><div><h2>PARAMETRIZAÇÃO FINANCEIRA — USUÁRIO MASTER</h2><p>CADA FORMA DEFINE SE ENTRA NO CAIXA, SE GERA CONTAS A RECEBER E SE EXIGE CONCILIAÇÃO. A REGRA FICA GRAVADA NA VENDA.</p></div><div className="cadRowActions"><button onClick={authorize}>{unlocked?"MASTER AUTORIZADO":"AUTORIZAR COM SENHA MASTER"}</button><button className="ghost dark" onClick={onClose}>VOLTAR</button></div></div>{!isMaster&&<div className="alert danger">OPERAÇÃO RESTRITA. SOLICITE AUTORIZAÇÃO AO USUÁRIO MASTER.</div>}<div className="cardLedger"><b>FORMA</b><b>ENTRA NO CAIXA</b><b>GERA CONTAS A RECEBER</b><b>RECEBIDO NA HORA</b><b>EXIGE COMPROVANTE</b><b>EXIGE CONCILIAÇÃO</b><b>PERMITE PRAZO</b>{(data.pagamentos||[]).map(p=><div className="rowContents" key={p.id}><strong>{p.descricao}</strong>{[["entraCaixa",p.entraCaixa!==false],["geraContasReceber",p.geraContasReceber!==false],["recebidoNaHora",!!p.recebidoNaHora],["exigeComprovante",!!p.exigeComprovante],["exigeConciliacao",!!p.exigeConciliacao],["permitePrazo",p.permitePrazo!==false]].map(([k,v])=><label key={k}><input type="checkbox" disabled={!unlocked} checked={v} onChange={e=>patch(p.id,k,e.target.checked)}/> {v?"SIM":"NÃO"}</label>)}</div>)}</div><p className="note">ALTERAÇÕES VALEM PARA NOVAS VENDAS. CAIXAS FECHADOS E TÍTULOS ANTIGOS NÃO SERÃO RECALCULADOS.</p></section>
}
