import {useState} from "react";
import {jsPDF} from "jspdf";
import {openFile} from "./fileStore";

const money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const stamp=v=>v?new Date(String(v).length===10?v+"T12:00:00":v).toLocaleString("pt-BR"):"-";
const upper=v=>String(v||"").toUpperCase();
const same=(a,b)=>String(a||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toUpperCase()===String(b||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toUpperCase();
const digits=v=>String(v||"").replace(/\D/g,"");
const total=rows=>rows.reduce((a,x)=>a+Number(x.qtd||0),0);
function parcelas(v){const cond=upper(v.condicaoPagamento);const prazos=cond.match(/\d+(?:\/\d+)*/)?.[0]?.split("/").map(Number)||[];if(!prazos.length)return [{vencimento:String(v.dataOperacao||v.criadoEm||new Date().toISOString()).slice(0,10),valor:Number(v.qtd||0)*Number(v.precoUnitario||v.preco||0)}];const cents=Math.round(Number(v.qtd||0)*Number(v.precoUnitario||v.preco||0)*100),base=Math.floor(cents/prazos.length);return prazos.map((dias,i)=>{const d=new Date(String(v.dataOperacao||v.criadoEm||new Date().toISOString()).slice(0,10)+"T12:00:00");d.setDate(d.getDate()+dias);return {vencimento:d.toISOString().slice(0,10),valor:(base+(i===prazos.length-1?cents-base*prazos.length:0))/100}})}
export default function VendasDiretasPanel({data,onChange,onDistribuir,onNotas,onEmails,currentUser}){
 const [aberta,setAberta]=useState("");
 const notas=(data.notasFiscais||[]).filter(n=>n.destinacao==="CARGA DIRETA").slice().sort((a,b)=>String(b.importadaEm||b.emissao||"").localeCompare(String(a.importadaEm||a.emissao||"")));
 const cargas=data.cargas||[],vendas=data.vendas||[],docs=data.documentos||[];
 const buscarDocs=n=>{const relacionados=docs.filter(d=>d.notaFiscalPrincipalId===n.id||d.cargaId&&d.cargaId===n.cargaId);const boletos=(data.preConferenciaBoletos||[]).filter(b=>String(b.nf||"")===String(n.numero||"")&&(b.carga===cargas.find(c=>c.id===n.cargaId)?.codigo||b.carga===n.cargaId));const has=t=>relacionados.some(d=>t.test(upper(d.tipo)))||(data.gmailImports||[]).some(d=>d.nfe?.chave===n.chave&&t.test(upper(d.tipo+" "+d.filename)));return {relacionados,boletos,danfe:!!n.danfeDocumentoId||has(/DANFE|NF PRINCIPAL/),boleto:!!n.boletoDocumentoId||boletos.length>0||has(/BOLETO|TÍTULO/),pallet:!!n.notaPallet||has(/PALLET|PALETE/),frete:!!n.comprovanteFreteDocumentoId||has(/FRETE/)}};
 const itens=n=>(n.produtos||[]).map(it=>({nome:it.produto,qtd:Number(it.quantidade||0),vendido:vendas.filter(v=>v.numeroNotaFiscal===n.numero&&v.cargaId===n.cargaId&&(v.produtoId===(data.produtos||[]).find(p=>same(p.nome,it.produto))?.id||same(v.produto,it.produto))&&v.origem==="DISTRIBUIÇÃO DA NF DA CARGA").reduce((sum,v)=>sum+Number(v.qtd||0),0)}));
 const clientes=n=>vendas.filter(v=>v.cargaId===n.cargaId&&String(v.numeroNotaFiscal||"")===String(n.numero||"")&&v.origem==="DISTRIBUIÇÃO DA NF DA CARGA");
 const cargaDe=n=>cargas.find(c=>c.id===n.cargaId);
 const pendencias=(n,documentos,items)=>{const c=cargaDe(n);const r=[];if(!documentos.danfe)r.push("DANFE/PDF");if(!documentos.boleto)r.push("BOLETO PARA CONFERÊNCIA");if(upper(c?.modalidadeFrete||c?.frete)!=="CIF"&&!documentos.frete)r.push("COMPROVANTE DO FRETE");if(items.some(i=>Math.abs(i.vendido-i.qtd)>0.00001))r.push("DISTRIBUIÇÃO POR PRODUTO");return r};
 function fechar(n){const c=cargaDe(n),dd=buscarDocs(n),items=itens(n),linhas=clientes(n),pend=pendencias(n,dd,items);if(!c||!items.length||!linhas.length)return alert("A NF PRECISA ESTAR VINCULADA À CARGA, COM PRODUTOS E VENDAS.");if(linhas.some(v=>!v.clienteId||!(Number(v.precoUnitario||v.preco||0)>0)))return alert("CONFIRA O CLIENTE E O PREÇO DE TODAS AS VENDAS ANTES DE GERAR RECEBÍVEIS.");if(items.some(i=>i.vendido>i.qtd+0.00001))return alert("HÁ PRODUTO VENDIDO ACIMA DA QUANTIDADE DA NOTA.");const bloqueios=pend.filter(p=>p!=="COMPROVANTE DO FRETE");if(bloqueios.length)return alert("FINALIZAÇÃO PENDENTE: "+bloqueios.join(", "));if(n.finalizacaoDiretaEm)return alert("ESTA NF JÁ FOI FINALIZADA.");onChange(d=>{const criados=[];for(const v of linhas){if((d.contasReceber||[]).some(x=>x.vendaId===v.id))continue;parcelas(v).forEach((p,i)=>criados.push({id:crypto.randomUUID(),vendaId:v.id,clienteId:v.clienteId,cliente:v.cliente,numeroVenda:v.numeroVenda,numeroNotaFiscal:n.numero,carga:c.codigo,parcela:i+1,quantidadeParcelas:parcelas(v).length,valor:p.valor,vencimento:p.vencimento,status:"ABERTO",origem:"VENDA DIRETA / NF "+n.numero}))}return {...d,contasReceber:[...(d.contasReceber||[]),...criados],notasFiscais:(d.notasFiscais||[]).map(x=>x.id===n.id?{...x,status:"OPERAÇÃO FINALIZADA",finalizacaoDiretaEm:new Date().toISOString(),finalizadaPor:currentUser?.nome||""}:x),cargas:(d.cargas||[]).map(x=>x.id===c.id?{...x,fase:"NF DISTRIBUÍDA — AGUARDANDO CONFERÊNCIA FINANCEIRA",qtdSemDestino:0}:x),auditoria:[...(d.auditoria||[]),{id:crypto.randomUUID(),acao:"NF DIRETA FINALIZADA / RECEBÍVEIS GERADOS",detalhe:"NF "+n.numero+" • "+linhas.length+" VENDA(S)",usuario:currentUser?.nome||"",dataHora:new Date().toISOString()}]}});alert("NF FINALIZADA. PARCELAS DOS CLIENTES LANÇADAS NO CONTAS A RECEBER. BOLETO DO FORNECEDOR AGUARDA VALIDAÇÃO FINANCEIRA."+(pend.includes("COMPROVANTE DO FRETE")?" COMPROVANTE DE FRETE SEGUE PENDENTE.":""))}
 function pdf(n){const c=cargaDe(n),m=(data.motoristas||[]).find(x=>x.id===c?.motoristaId),dd=buscarDocs(n),items=itens(n),vs=clientes(n),d=new jsPDF(),end=pendencias(n,dd,items);let y=18;const line=(s,size=9)=>{d.setFontSize(size);const parts=d.splitTextToSize(String(s),185);if(y+parts.length*5>280){d.addPage();y=17}d.text(parts,12,y);y+=Math.max(5,parts.length*5)};line("FORTE ATACAREJO - CONFERÊNCIA DE VENDA DIRETA",14);line("NF "+(n.numero||"-")+" | CHAVE "+(n.chave||"-"));line("FORNECEDOR: "+(n.emitente||"-")+" | PEDIDO/OS: "+[...(n.pedidos||[]),...(n.os||[])].join(" / "));line("CARGA: "+(c?.codigo||"-")+" | EMISSÃO: "+stamp(n.emissao)+" | STATUS: "+(n.status||"-"));line("BOLETO: "+(dd.boletos.map(b=>b.linhaDigitavel||b.arquivoNome).join(" / ")||n.boletoDocumentoId||"PENDENTE")+" | FINANCEIRO: "+(dd.boletos.map(b=>b.status).join(", ")||"AGUARDANDO"));line("FRETE: "+(dd.frete?"COMPROVANTE ANEXADO":upper(c?.modalidadeFrete||"")==="CIF"?"CIF - NÃO SE APLICA":"COMPROVANTE PENDENTE")+" | NF PALLETS: "+(dd.pallet?"SIM":"NÃO / NÃO SE APLICA"));line("MOTORISTA: "+(m?.nome||c?.motorista||"-")+" | PLACAS: "+[m?.placa1,m?.placa2,m?.placa3,m?.placa4,c?.placa].filter(Boolean).join(" / "));line("PIX MOTORISTA: "+(m?.chavePix||m?.pix||"NÃO CADASTRADO"));y+=4;line("PRODUTOS DA NF",11);items.forEach(i=>line(i.nome+" | NF "+i.qtd+" | VENDIDO "+i.vendido+" | SALDO "+(i.qtd-i.vendido)));y+=3;line("ENTREGAS E PARCELAS",11);vs.forEach(v=>{line((v.numeroVenda||"-")+" | "+(v.cliente||"-")+" | "+(v.produto||"-")+" | "+Number(v.qtd||0)+" SC | "+money(Number(v.qtd||0)*Number(v.precoUnitario||v.preco||0)));line("DESTINO "+(v.destino||"-")+" | PAGAMENTO "+(v.condicaoPagamento||"-")+" | PALLETS "+(v.qtdPallets||0));parcelas(v).forEach((p,i)=>line("   PARCELA "+(i+1)+" - "+stamp(p.vencimento)+" - "+money(p.valor)))});y+=4;line("TOTAL VENDIDO: "+total(vs)+" SACOS | PENDÊNCIAS: "+(end.join(", ")||"NENHUMA"));line("CONFERIDO POR: ______________________ DATA/HORA: ______________________");d.save("DOSSIÊ-VENDA-DIRETA-NF-"+(n.numero||n.id)+".pdf")}
 return <section className="card"><h2>VENDAS DIRETAS — UMA NOTA, VÁRIOS CLIENTES</h2><p>Selecione uma NF para conferir os documentos, distribuir seus produtos e imprimir a capa do dossiê. Boletos só entram em contas a pagar depois da validação financeira.</p>{!notas.length&&<p>NENHUMA NF ENVIADA PARA VENDAS DIRETAS. ABRA O PAINEL DE NOTAS FISCAIS E SELECIONE “ENVIAR PARA VENDAS DIRETAS”.</p>}
 {notas.map(n=>{const c=cargaDe(n),dd=buscarDocs(n),is=itens(n),vs=clientes(n),pend=pendencias(n,dd,is),open=aberta===n.id;return <article key={n.id} className="card" style={{border:"1px solid #cbd5e1",marginBottom:16}}><button type="button" className="ghost dark" style={{width:"100%",textAlign:"left"}} onClick={()=>setAberta(open?"":n.id)} aria-expanded={open}><b>NF {n.numero||"-"} • {n.emitente||"-"} • {c?.codigo||"CARGA A VINCULAR"}</b> <span>{n.finalizacaoDiretaEm?"FINALIZADA":pend.length?pend.length+" PENDÊNCIA(S)":"PRONTA PARA FINALIZAR"}</span></button>{open&&<><p>CHAVE: {n.chave||"PENDENTE"} • PRODUTOS: {is.map(i=>i.nome+" "+i.qtd+" SC").join(" | ")||"AGUARDANDO XML"}</p><div className="miniGrid">{[["DANFE / PDF",dd.danfe],["BOLETO",dd.boleto],["NF PALLETS (SE HOUVER)",dd.pallet||n.palletAplica==="NÃO"],["FRETE (CIF DISPENSADO)",dd.frete||upper(c?.modalidadeFrete)==="CIF"]].map(([label,ok])=><div key={label} className="note" style={{background:ok?"#eaf7ec":"#fff1bf",padding:10}}><b>{label}</b> • {ok?"ANEXADO / CONFERIR":"PENDENTE"}</div>)}</div><p>BOLETO: {dd.boletos.map(b=><span key={b.id}>{b.arquivoNome} — {b.status} • </span>)}{!dd.boletos.length&&"AGUARDANDO ANEXO / VINCULAÇÃO"}</p><div className="cadRowActions"><button type="button" onClick={()=>onNotas(n)}>ABRIR NF E ANEXOS</button><button type="button" className="secondary" onClick={()=>onEmails(c)}>BUSCAR DOCUMENTOS NO E-MAIL</button><button type="button" disabled={!c||!!n.finalizacaoDiretaEm} onClick={()=>onDistribuir(c.id)}>SELECIONAR CLIENTES / DISTRIBUIR</button><button type="button" className="secondary" onClick={()=>pdf(n)}>IMPRIMIR CAPA DO DOSSIÊ</button></div>{is.map(i=><p key={i.nome} className="note"><b>{i.nome}</b> — NF {i.qtd} • DISTRIBUÍDO {i.vendido} • SALDO {i.qtd-i.vendido}</p>)}<h3>VENDAS DESTA NOTA</h3>{vs.map(v=><div className="financialRow" key={v.id}><b>{v.cliente||v.clienteId} • {v.numeroVenda||""}</b><span>{v.produto} • {v.qtd} SC</span><span>{money(Number(v.qtd||0)*Number(v.precoUnitario||v.preco||0))}</span><span>{v.condicaoPagamento}</span></div>)}{!vs.length&&<p>NENHUM CLIENTE DISTRIBUÍDO.</p>}<div className="alert" style={{background:pend.length?"#fff1bf":"#eaf7ec"}}>{pend.length?"PENDÊNCIAS: "+pend.join(", "):"QUANTIDADES E DOCUMENTOS CONFERIDOS."}</div><button type="button" disabled={!!n.finalizacaoDiretaEm||pend.some(p=>p!=="COMPROVANTE DO FRETE")||!vs.length} onClick={()=>fechar(n)}>FINALIZAR NF E GERAR CONTAS A RECEBER</button></>}</article>})}</section>
}
