import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {stripTypeScriptTypes} from 'node:module';
const source=stripTypeScriptTypes(fs.readFileSync(new URL('../../supabase/functions/access-standard/index.ts',import.meta.url),'utf8'),{mode:'strip'}).replace(/^import .*;\n/,'').replace(/export /g,'');
let handler;let profile={user_id:'user',ativo:false,status_aprovacao:'PENDENTE',trocar_senha:false,perfil:'CONSULTA',nome:'Teste Usuário',cpf:'52998224725',whatsapp:'5534999998888'};let rows=[];let notifications=[];let mutations=[];let sessionUser={id:'user'};let created=0;let loginError=null;let origin='https://forte-vendas.onrender.com';
function query(table){let filters=[],action='select',value;const q={select(){return q},eq(k,v){filters.push([k,v]);return q},in(){return q},order(){return q},limit(){return q},insert(v){action='insert';value=v;return q},update(v){action='update';value=v;return q},delete(){action='delete';return q},maybeSingle(){return Promise.resolve(result(true))},then(ok,no){return Promise.resolve(result()).then(ok,no)}};
function result(single=false){if(action!=='select'){mutations.push({table,action,value});return {data:[],error:null}}let data=table==='fc_perfis'?[profile]:table==='access_requests'?rows:table==='access_notifications'?notifications:[];data=data.filter(x=>filters.every(([k,v])=>x[k]===v));return {data:single?(data[0]||null):data,error:null}}return q}
const fake={from:query,rpc:async(name,body)=>{mutations.push({rpc:name,body});return {data:'request-id',error:null}},auth:{getUser:async()=>({data:{user:sessionUser},error:sessionUser?null:{message:'invalid'}}),signInWithPassword:async()=>({data:{session:loginError?null:{access_token:'test-token',refresh_token:'test-refresh'},user:{id:'user'}},error:loginError}),admin:{createUser:async()=>{created++;return {data:{user:{id:'new-user'}},error:null}},getUserById:async()=>({data:{user:{email:'test@example.invalid'}},error:null}),updateUserById:async()=>({data:{},error:null}),deleteUser:async()=>({error:null})}}};
const context=vm.createContext({createClient:()=>fake,console,Response,Request,TextEncoder,crypto,Date,Deno:{env:{get:k=>k==='SUPABASE_URL'?'https://gtwecfyffjszghnvtlzr.supabase.co':'test-only-key'},serve:f=>handler=f}});vm.runInContext(source,context);
const base={nome:'Usuário de Teste',cpf:'52998224725',whatsapp:'34999998888',data_nascimento:'1990-01-15',email:'',password:'123456'};
async function invoke(body,org=origin,token=true){return handler(new Request('https://example.invalid',{method:'POST',headers:{origin:org,'content-type':'application/json',...(token?{authorization:'Bearer simulation'}:{})},body:JSON.stringify(body)}))}
test('CPF, nascimento e e-mail opcional',()=>{assert.equal(context.validCpf(base.cpf),true);assert.equal(context.validCpf('11111111111'),false);assert.equal(context.validBirth('2000-02-29'),true);assert.equal(context.validBirth('2001-02-29'),false);assert.equal(context.validBirth('2099-01-01'),false);assert.equal(context.validateRegistration(base).email,null)});
test('Senha aceita seis ou mais números e rejeita letras ou cinco números',()=>{for(const password of ['123456','1234567890'])assert.doesNotThrow(()=>context.validateRegistration({...base,password}));for(const password of ['12345','Abc123','123 456'])assert.throws(()=>context.validateRegistration({...base,password}))});
test('Nome completo, CPF, WhatsApp e nascimento são obrigatórios',()=>{for(const [field,value]of [['nome','Teste'],['cpf','123'],['whatsapp','123'],['data_nascimento','']])assert.throws(()=>context.validateRegistration({...base,[field]:value}))});
test('Origem desconhecida e projeto separado são recusados',async()=>{assert.equal((await invoke({action:'REGISTER',...base},'https://evil.invalid')).status,403);assert.equal((await invoke({action:'REGISTER',...base},'https://forte-fiscal.onrender.com')).status,403)});
test('CPF existente não permite trocar senha pelo cadastro público',async()=>{created=0;mutations=[];const r=await invoke({action:'REGISTER',...base});assert.equal(r.status,409);assert.equal(created,0);assert.ok(!mutations.some(x=>x.rpc))});
test('Cadastro inválido não cria usuário',async()=>{created=0;const r=await invoke({action:'REGISTER',...base,password:'abc123'});assert.equal(r.status,400);assert.equal(created,0)});
test('Cadastro novo sem e-mail usa identidade interna e fica pendente',async()=>{profile={...profile,cpf:'11144477735'};created=0;mutations=[];const r=await invoke({action:'REGISTER',...base,perfil:'MASTER',ativo:true,status_aprovacao:'APROVADO'});assert.equal(r.status,201);assert.equal((await r.json()).status,'PENDENTE');assert.equal(created,1);const reg=mutations.find(x=>x.rpc==='access_register_profile');assert.equal(reg.body.p_email,null);assert.equal(reg.body.p_app,'vendas');assert.equal(reg.body.p_user,'new-user');assert.equal(reg.body.p_perfil,undefined);profile={...profile,cpf:base.cpf}});
test('Sessão pendente acompanha situação sem abrir operação',async()=>{rows=[{user_id:'user',app:'vendas',status:'PENDENTE',managed_account:true}];const r=await invoke({action:'STATUS'});const b=await r.json();assert.equal(b.allowed,false);assert.equal(b.status,'PENDENTE');assert.equal(b.isAdmin,false)});
test('Aprovação de outro aplicativo não abre Vendas',async()=>{profile={...profile,ativo:true,status_aprovacao:'APROVADO'};rows=[{user_id:'user',app:'financeiro',status:'APROVADO',managed_account:true}];const b=await (await invoke({action:'STATUS'})).json();assert.equal(b.allowed,false)});
test('Aprovação correta abre somente o aplicativo aprovado',async()=>{rows=[{user_id:'user',app:'vendas',status:'APROVADO',managed_account:true}];assert.equal((await (await invoke({action:'STATUS'})).json()).allowed,true)});
test('Usuário comum não vê fila nem aprova',async()=>{for(const action of ['QUEUE','REVIEW'])assert.equal((await invoke({action,id:'request',decision:'APROVADO'})).status,403)});
test('Recuperação de senha não libera conta pendente',async()=>{rows=[{user_id:'user',app:'vendas',status:'PENDENTE',managed_account:true}];assert.equal((await invoke({action:'SET_PASSWORD',password:'1234567'})).status,200);assert.equal((await (await invoke({action:'STATUS'})).json()).allowed,false)});
test('Senha nova exige sessão verificada e somente números',async()=>{assert.equal((await invoke({action:'SET_PASSWORD',password:'letters'})).status,400);sessionUser=null;assert.equal((await invoke({action:'SET_PASSWORD',password:'123456'})).status,401);sessionUser={id:'user'}});
test('Admin inativo, pendente ou trocando senha não pode analisar',async()=>{for(const x of [{ativo:false},{status_aprovacao:'PENDENTE'},{trocar_senha:true}]){const p=profile;profile={...profile,perfil:'MASTER',...x};assert.equal((await invoke({action:'QUEUE'})).status,403);profile=p}});


test("Avisos do usuário correspondem ao aplicativo consultado",async()=>{rows=[{id:"request-vendas",user_id:"user",app:"vendas",status:"PENDENTE",managed_account:true}];notifications=[{user_id:"user",request_id:"financeiro",audience:"USER",message:"Financeiro aprovado"},{user_id:"user",request_id:"request-vendas",audience:"USER",message:"Vendas em análise"}];const b=await (await invoke({action:"STATUS"})).json();assert.equal(b.notifications.length,1);assert.equal(b.notifications[0].message,"Vendas em análise");notifications=[]});


test('Senha antiga válida exige atualização antes de liberar master',async()=>{const old=profile;profile={...profile,ativo:true,status_aprovacao:'APROVADO',perfil:'MASTER',trocar_senha:false};rows=[];mutations=[];const r=await invoke({action:'LOGIN',cpf:base.cpf,password:'Antiga@123'});assert.equal(r.status,200);assert.ok(mutations.some(x=>x.table==='fc_perfis'&&x.action==='update'&&x.value.trocar_senha===true));profile.trocar_senha=true;const b=await (await invoke({action:'STATUS'})).json();assert.equal(b.allowed,false);assert.equal(b.changing,true);assert.equal(b.isAdmin,false);profile=old});
test('Senha antiga inválida não altera perfil nem abre sessão',async()=>{mutations=[];loginError={message:'invalid'};try{const r=await invoke({action:'LOGIN',cpf:base.cpf,password:'Incorreta@123'});assert.equal(r.status,401);assert.ok(!mutations.some(x=>x.table==='fc_perfis'&&x.action==='update'));assert.equal((await r.json()).access_token,undefined)}finally{loginError=null}});
test('Login com senha numérica não força alteração de senha',async()=>{mutations=[];const r=await invoke({action:'LOGIN',cpf:base.cpf,password:'1234567'});assert.equal(r.status,200);assert.ok(!mutations.some(x=>x.table==='fc_perfis'&&x.action==='update'))});
