export const norm = v => String(v || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim().toUpperCase();
export const PALLETS = ['Com pallets', 'Sem pallets', 'Leva pallets', 'Solicitar pallets com liberação do vendedor'];
export const DOCUMENTS = ['XML NF', 'PDF NF', 'BOLETO FORNECEDOR', 'NF PALLETS', 'COMPROVANTE FRETE', 'COMPROVANTE ENVIO FORNECEDOR', 'COMPROVANTE ENVIO MOTORISTA', 'COMPROVANTE ENTREGA'];
const active = x => x.ativo !== false;
const arr = (s,k) => s[k] || [];
const cents = n => Math.round(Number(n) * 100) / 100;
const fail = msg => { throw new Error(msg); };
const text = (v,label) => String(v || '').trim() || fail(`Informe ${label}.`);
const num = (v,label,zero=false) => { const n=Number(v); if(!Number.isFinite(n)||(zero?n<0:n<=0))fail(`Confira ${label}.`); return n; };
const integer = (v,label,zero=false) => {const n=num(v,label,zero);if(!Number.isSafeInteger(n))fail(`${label} deve ser inteiro.`);return n;};
const byId = (s,k,id,label) => arr(s,k).find(x=>x.id===id&&active(x)) || fail(`${label} não localizado ou inativo.`);
const privileged = p => ['MASTER','ADMINISTRADOR'].includes(p.perfil);
export function supplierProducts(s,id) {
 const f=arr(s,'fornecedores').find(x=>x.id===id);if(!f)return [];
 const brands=(f.marcas||norm(f.nome).split(/\s*\/\s*/)).map(norm);
 return arr(s,'produtos').filter(p=>active(p)&&p.revenda!==false&&!/USO|CONSUMO/.test(norm(p.classificacao||p.destinacao))&&(p.fornecedorId===id||(p.fornecedorIds||[]).includes(id)||arr(s,'custosFornecedor').some(c=>active(c)&&c.fornecedorId===id&&c.produtoId===p.id)||brands.includes(norm(p.marca))));
}
export function supplierTerms(s,id){const f=arr(s,'fornecedores').find(x=>x.id===id)||{};return [...new Set([f.condicaoPagamento,f.formaPagamentoPadrao,...(f.prazosPagamento||[]),...arr(s,'custosFornecedor').filter(c=>active(c)&&c.fornecedorId===id).map(c=>c.condicaoPagamento)].filter(Boolean))];}
export function supplierCost(s,id,product) {return arr(s,'produtos').find(p=>p.id===product)?.precoNegociado;}
export function palletQuantity(s,items,rule) {if(rule===PALLETS[1])return 0;return (items||[]).reduce((total,i)=>{const p=arr(s,'produtos').find(p=>p.id===i.produtoId),q=Number(i.qtd||0);if(!q)return total;const per=Number(p?.palletQtd||p?.qtdPorPallet||p?.sacosPorPallet||p?.unidadesPorPallet);if(!Number.isSafeInteger(per)||per<=0)fail('Cadastre a quantidade por pallet do produto '+(p?.nome||'selecionado')+'.');return total+Math.ceil(q/per);},0);}
export function salePrice(s,client,product){const p=arr(s,'produtos').find(x=>x.id===product);const c=arr(s,'precosClientes').find(x=>active(x)&&x.clienteId===client&&x.produtoId===product);return c?.precoFinal??cents(Number(p?.precoTabela||0)*(1-Number(c?.descontoPct||0)/100));}
export function validDriver(s,id,weight){const m=byId(s,'motoristas',id,'Motorista');if(/PENDENTE|ANALISE|RECUSADO|CONFERENCIA|AGUARDANDO/.test(norm(m.statusCadastro)))fail('Motorista aguarda aprovação.');const capacity=num(m.capacidadeMaximaKg||m.capacidadeAlvoKg,'capacidade do conjunto');if(weight>capacity)fail('Peso acima da capacidade do conjunto.');if(!m.placa1)fail('Cadastre a placa do conjunto.');return m;}
function pallets(s,b,p,at){if(!PALLETS.includes(b.regraPallets))fail('Selecione uma das quatro regras de pallets.');const qtd=palletQuantity(s,b.itens,b.regraPallets);if(b.regraPallets!==PALLETS[1]&&!qtd)fail('Informe a quantidade de pallets.');if(b.regraPallets===PALLETS[1]&&qtd)fail('Sem pallets exige quantidade zero.');if(b.regraPallets===PALLETS[3]&&!privileged(p)&&p.permissoes?.liberarPallets!==true)fail('A liberação de pallets exige vendedor autorizado ou administrador.');return {regraPallets:b.regraPallets,pallet:b.regraPallets,palletQuantidade:qtd,pallets:qtd,aprovacaoPallets:b.regraPallets===PALLETS[3]?{usuario:p.user_id,nome:p.nome,dataHora:at}:null};}
function purchaseItems(s,b,p,at){const allowed=supplierProducts(s,b.fornecedorId);if(!b.itens?.length)fail('Inclua ao menos um produto.');const seen=new Set();return b.itens.map(i=>{if(seen.has(i.produtoId))fail('Consolide quantidades do mesmo produto.');seen.add(i.produtoId);const prod=allowed.find(x=>x.id===i.produtoId)||fail('Produto não vinculado ao fornecedor.');const qtd=integer(i.qtd,'Quantidade'),pesoKg=qtd*num(prod.pesoKg,'peso cadastrado do produto');const cost=supplierCost(s,b.fornecedorId,prod.id,b.pagamento,at);const price=num(cost,'preço negociado no cadastro de produtos');if(i.custoUnitario!=null&&i.custoUnitario!==''&&cents(Number(i.custoUnitario))!==cents(price))fail('Preço negociado mudou no cadastro; selecione novamente o produto.');return {produtoId:prod.id,produto:prod.nome,marca:prod.marca,qtd,pesoKg,custoUnitario:price,total:cents(qtd*price)};});}
function officialUnique(s,f,n,except){if(arr(s,'cargas').some(c=>c.id!==except&&c.status!=='CANCELADA'&&c.fornecedorId===f&&norm(c.numeroPedidoFornecedor)===norm(n)))fail('Este pedido oficial já está vinculado a outra carga.');}
function next(s,key,prefix,collection,field){let seq=Number(s.settings?.[key]||1);const used=new Set(arr(s,collection).map(x=>x[field]));let code;do{code=prefix+String(seq++).padStart(6,'0');}while(used.has(code));s.settings={...s.settings,[key]:seq};return code;}
function ensureLoad(s,order,id,at){let c=arr(s,'cargas').find(x=>x.compraFornecedorId===order.id||x.id===order.cargaId);if(c)return c;const f=byId(s,'fornecedores',order.fornecedorId,'Fornecedor');c={id,codigo:next(s,'nextCargaSeq','FC-','cargas','codigo'),compraFornecedorId:order.id,fornecedorId:f.id,fornecedor:f.nome,marca:order.itens.map(i=>i.marca).filter(Boolean).join(' / '),itens:order.itens,produtoId:order.itens[0].produtoId,produto:order.itens.map(i=>i.produto).join(' / '),qtd:order.itens.reduce((a,i)=>a+i.qtd,0),pesoKg:order.pesoKg,qtdSemDestino:order.itens.reduce((a,i)=>a+i.qtd,0),motoristaId:order.motoristaId,motorista:order.motorista,placas:order.placas,unidadeId:order.unidadeId,unidade:order.unidade,origem:order.origem,localCarregamento:order.origem,destino:order.destino,destinoTipo:order.destinoTipo,modalidadeFrete:order.modalidadeFrete,condicaoFornecedor:order.pagamento,regraPallets:order.regraPallets,pallet:order.pallet,palletQuantidade:order.palletQuantidade,aprovacaoPallets:order.aprovacaoPallets,nfPalletsAplica:order.nfPalletsAplica,numeroPedidoFornecedor:order.numeroPedidoFornecedor||'',vendaIds:[],status:'VERMELHO',fase:order.numeroPedidoFornecedor?'AGUARDANDO NOTAS FISCAIS':'AGUARDANDO RETORNO DO FORNECEDOR',criadaEm:at};s.cargas=[...arr(s,'cargas'),c];order.cargaId=c.id;order.codigoCarga=c.codigo;return c;}
export function documentStatus(s,c,type){if(type==='COMPROVANTE FRETE'&&c.modalidadeFrete==='CIF')return 'NÃO SE APLICA';if(type==='NF PALLETS'&&c.nfPalletsAplica===false)return 'NÃO SE APLICA';const docs=arr(s,'documentos').filter(d=>d.cargaId===c.id&&d.categoria===type);return docs.some(d=>d.validationStatus==='VALIDADO')?'VALIDADO':docs.length?'RECEBIDO — CONFERIR':'PENDENTE';}
export function applyWorkflow(original,b,p,{id,at}){
 if(!p.ativo||p.status_aprovacao!=='APROVADO'||p.trocar_senha||!['MASTER','ADMINISTRADOR','OPERADOR_GERAL','VENDEDOR_INTERNO'].includes(p.perfil))fail('Acesso ativo e aprovado necessário.');
 const request=JSON.stringify(Object.fromEntries(Object.entries(b).filter(([k])=>!k.startsWith('internal'))));
 const key=text(b.requestId,'identificador da operação');if(key.length>100)fail('Identificador inválido.');
 const prior=arr(original,'workflowEvents').find(e=>e.requestId===key);if(prior){if(prior.actor!==p.user_id||prior.action!==b.action||prior.request!==request)fail('Identificador já utilizado por outra operação.');return {state:original,result:prior.result,replayed:true};}
 const s=structuredClone(original);let result={};
 const purchase=()=>arr(s,'comprasFornecedor').find(x=>x.id===b.id)||fail('Pedido não localizado.');
 const load=()=>arr(s,'cargas').find(x=>x.id===b.cargaId&&x.status!=='CANCELADA')||fail('Carga não localizada.');
 if(b.action==='DRIVERS_IMPORTED'){
  const imported=b.internalDrivers||[];s.motoristas=[...arr(s,'motoristas').filter(m=>m.origemCadastro!=='FORTE FRETE'),...imported];result={count:imported.length};
 }else if(b.action==='FRETE_PUBLISHED'){
  const c=load();Object.assign(c,{fretePublicadaId:b.internalReceipt.id,fretePublicadaEm:at,ordemMotoristaEnviada:true,ordemEnviadaEm:b.internalReceipt.enviadaEm,ordemCanal:'FORTE FRETE',ordemDestinatario:b.internalReceipt.motoristaId,fase:'ORDEM DISPONÍVEL NO FORTE FRETE'});result={cargaId:c.id,freteId:b.internalReceipt.id};
 }else if(b.action==='SUPPLIER_CREATE'){
  const f=byId(s,'fornecedores',b.fornecedorId,'Fornecedor'),u=byId(s,'unidades',b.unidadeId,'Unidade');
  if(!supplierTerms(s,f.id).some(t=>norm(t)===norm(b.pagamento)))fail('Cadastre o prazo no fornecedor antes de gravar.');
  const itens=purchaseItems(s,b,p,at),pesoKg=itens.reduce((a,i)=>a+i.pesoKg,0),m=b.motoristaId?validDriver(s,b.motoristaId,pesoKg):null;
  if(!['FOB','CIF'].includes(b.modalidadeFrete)||!['GALPÃO','VENDA DIRETA','A DEFINIR'].includes(b.destinoTipo))fail('Selecione modalidade e tipo de destino.');
  const order={id,numero:next(s,'nextCompraSeq',`COMP-${at.slice(0,4)}-`,'comprasFornecedor','numero'),fornecedorId:f.id,fornecedor:f.nome,unidadeId:u.id,unidade:u.nome,codigoFornecedor:f.codigoCliente||f.codigoForte||'',itens,pesoKg,custoTotal:cents(itens.reduce((a,i)=>a+i.total,0)),qtd:itens.reduce((a,i)=>a+i.qtd,0),produto:itens.map(i=>i.produto).join(' / '),motoristaId:m?.id||'',motorista:m?.nome||'',placas:m?[m.placa1,m.placa2,m.placa3,m.placa4].filter(Boolean):[],origem:text(b.origem,'expedição'),destino:text(b.destino,'destino'),destinoTipo:b.destinoTipo,modalidadeFrete:b.modalidadeFrete,pagamento:b.pagamento,...pallets(s,b,p,at),nfPalletsAplica:b.regraPallets!==PALLETS[1],origemPreenchimento:b.origemPreenchimento||'MANUAL',status:'RASCUNHO — NÃO ENVIADO',criadaEm:at,criadaPor:p.nome};
  s.comprasFornecedor=[...arr(s,'comprasFornecedor'),order];result={id:order.id,numero:order.numero};
 }else if(b.action==='SUPPLIER_TERM'){
  if(!privileged(p)&&p.permissoes?.editarFornecedor!==true)fail('Seu perfil não pode alterar o prazo do fornecedor.');const f=byId(s,'fornecedores',b.fornecedorId,'Fornecedor');const term=text(b.pagamento,'prazo');f.prazosPagamento=[...new Set([...(f.prazosPagamento||[]),term])];result={id:f.id};
 }else if(b.action==='SUPPLIER_RECEIPT'){
  const o=purchase();if(o.envioComprovadoEm)fail('Envio já registrado para este pedido.');const recipient=text(b.destinatario,'destinatário');if(!['WHATSAPP','EMAIL','PORTAL'].includes(b.canal))fail('Selecione o canal.');
  const d=arr(s,'documentos').find(d=>d.id===b.documentoId&&d.compraFornecedorId===o.id&&d.categoria==='COMPROVANTE ENVIO FORNECEDOR')||fail('Anexe o comprovante do envio ao pedido.');
  Object.assign(d,{validationStatus:'VALIDADO',conferente:p.nome,validadoEm:at});Object.assign(o,{status:'AGUARDANDO RETORNO DO FORNECEDOR',envioComprovadoEm:at,envioComprovadoPor:p.nome,canalEnvio:b.canal,destinatario:recipient,envioDocumentoId:d.id});const c=ensureLoad(s,o,id,at);d.cargaId=c.id;result={id:o.id,cargaId:c.id};
 }else if(b.action==='OFFICIAL_CONFIRM'){
  const o=purchase(),n=text(b.numeroPedidoFornecedor,'número oficial'),evidence=text(b.evidencia,'referência do documento ou retorno conferido');if(o.numeroPedidoFornecedor&&norm(o.numeroPedidoFornecedor)!==norm(n))fail('Pedido já confirmado; alteração exige revisão administrativa.');officialUnique(s,o.fornecedorId,n,o.cargaId);o.numeroPedidoFornecedor=n;o.evidenciaRetorno=evidence;o.confirmadoEm=at;o.confirmadoPor=p.nome;o.status='AGUARDANDO NOTAS FISCAIS';const c=ensureLoad(s,o,id,at);Object.assign(c,{numeroPedidoFornecedor:n,fase:'AGUARDANDO NOTAS FISCAIS',pedidoConfirmadoEm:at,pedidoConfirmadoPor:p.nome});result={id:o.id,cargaId:c.id};
 }else if(b.action==='SALE_CREATE'){
  const customer=byId(s,'clientes',b.clienteId,'Cliente'),seller=byId(s,'usuarios',b.vendedorId,'Vendedor');if(!b.itens?.length)fail('Inclua produtos.');if(!['PIX','DINHEIRO','TRANSFERÊNCIA','CARTÃO','BOLETO','A PRAZO'].includes(b.formaPagamento))fail('Selecione o recebimento.');const prazo=text(b.condicaoPagamento,'condição de pagamento'),destino=text(b.destino,'endereço ou obra'),rate=num(b.fretePorTon||0,'frete por tonelada',true);const group=id,number=next(s,'nextVendaSeq',`VEN-${at.slice(0,4)}-`,'vendas','numeroVenda');
  const rows=b.itens.map((i,index)=>{const prod=byId(s,'produtos',i.produtoId,'Produto');if(norm(i.marca)!==norm(prod.marca)||!prod.marca)fail('Selecione a marca antes do produto.');if(prod.revenda===false||/USO|CONSUMO/.test(norm(prod.classificacao||prod.destinacao)))fail('Produto não classificado para revenda.');const qtd=integer(i.qtd,'Quantidade'),price=num(i.precoUnitario,'preço unitário'),expected=salePrice(s,customer.id,prod.id);if((expected<=0||cents(price)!==cents(expected))&&!privileged(p)&&p.permissoes?.editarPreco!==true)fail('Preço diferente do cadastro exige autorização.');const pesoKg=qtd*num(prod.pesoKg,'peso cadastrado');return {id:`${id}-${index}`,grupoPedidoId:group,numeroVenda:number,clienteId:customer.id,cliente:customer.nome,clienteEmail:customer.email||'',clienteWhatsapp:customer.whatsapp||customer.telefone||'',vendedorId:seller.id,vendedorNome:seller.nome,produtoId:prod.id,produto:prod.nome,marca:prod.marca,qtd,pesoKg,precoUnitario:price,totalVenda:cents(qtd*price),fretePorTon:rate,freteValor:cents(pesoKg/1000*rate),freteIncluso:!!b.freteIncluso,totalGeral:cents(qtd*price+(b.freteIncluso?0:pesoKg/1000*rate)),formaPagamento:b.formaPagamento,condicaoPagamento:prazo,destino,status:'APROVADO',origemComercial:'VR',workflowInterno:true,destinoPainel:'AGUARDANDO ROTEAMENTO',criadoEm:at,dataOperacao:at.slice(0,10)};});
  if(['BOLETO','A PRAZO'].includes(b.formaPagamento)){const total=rows.reduce((a,v)=>a+v.totalGeral,0),used=arr(s,'contasReceber').filter(x=>x.clienteId===customer.id&&!/LIQUIDADO|PAGO|RECEBIDO/.test(norm(x.status))).reduce((a,x)=>a+Number(x.saldoAberto??x.valor??0),0)+arr(s,'vendas').filter(v=>v.clienteId===customer.id&&!['CANCELADA','ENTREGUE'].includes(v.status)&&['BOLETO','A PRAZO'].includes(v.formaPagamento)&&!arr(s,'contasReceber').some(t=>t.vendaId===v.id)).reduce((a,v)=>a+Number(v.totalGeral||v.totalVenda||Number(v.qtd)*Number(v.precoUnitario)),0);if(total>Math.max(0,Number(customer.limiteCredito||0)-used))fail('Pedido excede o crédito disponível do cliente.');}
  s.vendas=[...arr(s,'vendas'),...rows];result={id:group,numero:number};
 }else if(b.action==='LOADING_SAVE'){
  const f=byId(s,'fornecedores',b.fornecedorId,'Fornecedor'),n=text(b.numeroPedidoFornecedor,'número oficial');const existing=arr(s,'cargas').filter(c=>c.status!=='CANCELADA'&&c.fornecedorId===f.id&&norm(c.numeroPedidoFornecedor)===norm(n));if(existing.length>1)fail('Há múltiplas cargas para este número. Solicite conferência.');let c=existing[0];if(b.cargaId&&c?.id!==b.cargaId)fail('Pedido não corresponde à carga selecionada.');if(c?.finalizadaEm)fail('Carga já finalizada.');text(b.evidencia,'documento ou retorno conferido');
  const date=text(b.dataCarregamento,'data');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date)fail('Data inválida.');
  if(!c){const u=byId(s,'unidades',b.unidadeId,'Unidade');if(!supplierTerms(s,f.id).some(t=>norm(t)===norm(b.pagamento)))fail('Cadastre o prazo do fornecedor.');const itens=purchaseItems(s,b,p,at);const o={id:id+'-compra',fornecedorId:f.id,fornecedor:f.nome,itens,pesoKg:itens.reduce((a,i)=>a+i.pesoKg,0),unidadeId:u.id,unidade:u.nome,origem:text(b.origem,'origem'),destino:text(b.destino,'destino'),destinoTipo:b.destinoTipo,pagamento:b.pagamento,modalidadeFrete:b.modalidadeFrete,numeroPedidoFornecedor:n,...pallets(s,b,p,at),nfPalletsAplica:b.regraPallets!==PALLETS[1]};if(!['GALPÃO','VENDA DIRETA','A DEFINIR'].includes(o.destinoTipo)||!['FOB','CIF'].includes(o.modalidadeFrete))fail('Selecione destino e modalidade.');c=ensureLoad(s,o,id,at);c.pedidoExterno=true;}
  const m=validDriver(s,b.motoristaId,c.pesoKg),rate=num(b.fretePorTon||0,'frete por tonelada',true);Object.assign(c,{motoristaId:m.id,motorista:m.nome,placas:[m.placa1,m.placa2,m.placa3,m.placa4].filter(Boolean),placa:m.placa1,dataCarregamento:date,evidenciaPedido:b.evidencia,origemPreenchimento:b.origemPreenchimento||'MANUAL',fretePorTon:rate,freteValor:c.modalidadeFrete==='CIF'?0:cents(c.pesoKg/1000*rate),ordemRevisadaEm:at,ordemRevisadaPor:p.nome,fase:'ORDEM PREPARADA — ENVIO PENDENTE'});result={id:c.id,cargaId:c.id};
 }else if(b.action==='SALE_LINK'){
  const c=load();if(c.finalizadaEm)fail('Carga finalizada.');const rows=arr(s,'vendas').filter(v=>v.grupoPedidoId===b.vendaId||v.id===b.vendaId);if(!rows.length||rows.some(v=>v.status==='CANCELADA'||v.cargaId&&v.cargaId!==c.id))fail('Venda indisponível ou vinculada a outra carga.');const future=[...new Set([...(c.vendaIds||[]),...rows.map(v=>v.id)])];for(const i of c.itens||[]){const qty=arr(s,'vendas').filter(v=>future.includes(v.id)&&v.produtoId===i.produtoId).reduce((a,v)=>a+Number(v.qtd),0);if(qty>i.qtd)fail('Quantidade de venda maior que a quantidade deste produto na carga.');}if(rows.some(v=>!(c.itens||[]).some(i=>i.produtoId===v.produtoId)))fail('Produto da venda não consta na carga.');c.vendaIds=future;rows.forEach(v=>{v.cargaId=c.id;v.destinoPainel='CARGA DIRETA';});result={cargaId:c.id};
 }else if(b.action==='DOCUMENT_ADD'){
  const c=b.cargaId?load():null,o=b.compraFornecedorId?arr(s,'comprasFornecedor').find(x=>x.id===b.compraFornecedorId):null;if(!c&&!o)fail('Selecione o pedido ou carga.');if(!DOCUMENTS.includes(b.categoria))fail('Categoria inválida.');const path=text(b.path,'arquivo'),hash=text(b.hash,'hash do arquivo');if(!path.startsWith(p.empresa_id+'/')||!/^[a-f0-9]{64}$/.test(hash))fail('Arquivo inválido ou de outra empresa.');const existing=arr(s,'documentos').find(d=>d.cargaId===(c?.id||'')&&d.compraFornecedorId===(o?.id||'')&&d.categoria===b.categoria&&d.hash===hash);if(existing)result={id:existing.id};else{const d={id,cargaId:c?.id||'',compraFornecedorId:o?.id||'',categoria:b.categoria,tipo:b.categoria,filename:text(b.filename,'nome do arquivo'),storageBucket:'forte-vendas-dossies',storagePath:path,hash,validationStatus:'RECEBIDO',identificacaoConfirmada:false,origem:'ANEXO MANUAL',receivedAt:at,usuario:p.nome};s.documentos=[...arr(s,'documentos'),d];result={id};}
 }else if(b.action==='DOCUMENT_VALIDATE'){
  const c=load(),d=arr(s,'documentos').find(x=>x.id===b.documentoId&&x.cargaId===c.id)||fail('Documento não localizado nesta carga.');text(b.evidencia,'referência conferida');Object.assign(d,{validationStatus:'VALIDADO',identificacaoConfirmada:true,validadoEm:at,conferente:p.nome,evidencia:b.evidencia});result={id:d.id};
 }else if(b.action==='DRIVER_RECEIPT'){
  const c=load();if(!c.ordemRevisadaEm||!c.numeroPedidoFornecedor)fail('Revise e grave a ordem primeiro.');const d=arr(s,'documentos').find(x=>x.id===b.documentoId&&x.cargaId===c.id&&x.categoria==='COMPROVANTE ENVIO MOTORISTA')||fail('Anexe comprovante de envio ao motorista.');Object.assign(d,{validationStatus:'VALIDADO',validadoEm:at,conferente:p.nome});Object.assign(c,{ordemMotoristaEnviada:true,ordemEnviadaEm:at,ordemDestinatario:text(b.destinatario,'destinatário'),ordemCanal:text(b.canal,'canal'),ordemDocumentoId:d.id,fase:'AGUARDANDO NOTAS FISCAIS'});result={cargaId:c.id};
 }else if(b.action==='LOAD_FINALIZE'){
  const c=load();if(c.finalizadaEm)fail('Carga já finalizada.');if(!c.numeroPedidoFornecedor||!c.ordemMotoristaEnviada||!c.itens?.length)fail('Pedido, produtos e envio da ordem precisam estar confirmados.');const required=['XML NF','PDF NF','BOLETO FORNECEDOR','COMPROVANTE FRETE','NF PALLETS','COMPROVANTE ENTREGA'];const pending=required.filter(t=>!['VALIDADO','NÃO SE APLICA'].includes(documentStatus(s,c,t)));if(pending.length)fail('Documentos pendentes de validação: '+pending.join(', '));if(c.destinoTipo==='A DEFINIR')fail('Defina a destinação da carga.');if(c.destinoTipo==='VENDA DIRETA'){for(const i of c.itens){if(arr(s,'vendas').filter(v=>(c.vendaIds||[]).includes(v.id)&&v.produtoId===i.produtoId).reduce((a,v)=>a+Number(v.qtd),0)!==i.qtd)fail('Distribua toda a quantidade por produto antes de finalizar.');}}
  if(c.destinoTipo==='GALPÃO'&&!arr(s,'estoqueMov').some(m=>m.cargaId===c.id||m.referencia===c.codigo&&String(m.tipo).startsWith('ENTRADA')))s.estoqueMov=[...arr(s,'estoqueMov'),...c.itens.map((i,index)=>({id:id+'-'+index,cargaId:c.id,produtoId:i.produtoId,produto:i.produto,marca:i.marca,unidade:c.unidade,tipo:'ENTRADA - COMPRA FORTE / CARGA',qtd:i.qtd,quantidade:i.qtd,custoUnitario:i.custoUnitario,data:at.slice(0,10),dataHora:at,criadoEm:at,usuario:p.nome,origem:'FINALIZAÇÃO DE CARGA',referencia:c.codigo}))];
  Object.assign(c,{status:'AZUL',fase:'FINALIZADA',finalizadaEm:at,finalizadaPor:p.nome});result={cargaId:c.id};
 }else fail('Ação inválida.');
 // Delivery is recomputed only from a real finalization, delivery receipt and actual billing receipts.
 s.vendas=arr(s,'vendas').map(v=>{const c=arr(s,'cargas').find(c=>c.id===v.cargaId);if(v.status==='CANCELADA'||!c?.finalizadaEm||documentStatus(s,c,'COMPROVANTE ENTREGA')!=='VALIDADO')return v;const group=arr(s,'vendas').filter(x=>(x.grupoPedidoId||x.id)===(v.grupoPedidoId||v.id));const ids=group.map(x=>x.id);const total=group.reduce((a,x)=>a+Number(x.totalGeral||x.totalVenda||Number(x.qtd)*Number(x.precoUnitario)),0);const issued=arr(s,'boletosClientes').filter(t=>(ids.includes(t.vendaId)||t.vendaId===v.grupoPedidoId)&&(t.nossoNumero||t.idCobranca)&&['EMITIDO','REGISTRADO','LIQUIDADO','PAGO'].includes(norm(t.status)));const billing=v.formaPagamento!=='BOLETO'||(issued.length>0&&cents(issued.reduce((a,t)=>a+Number(t.valor||0),0))>=cents(total));return billing?{...v,status:'ENTREGUE',entregueEm:v.entregueEm||at}:v;});
 s.auditoria=[...arr(s,'auditoria'),{id:id+'-aud',acao:b.action,detalhe:JSON.stringify(result),usuario:p.nome,userId:p.user_id,dataHora:at}];s.workflowEvents=[...arr(s,'workflowEvents'),{requestId:key,request,actor:p.user_id,action:b.action,result,at}];return {state:s,result};
}
