import {PURCHASE_MODES,driverSnapshot,supplierSnapshot,canEditPurchase,palletReleaseNeeded} from './complements.mjs';
import {purchaseSnapshot,queueCustomer,queueLoading,itemsText,phone} from './communications.mjs';
export const norm = v => String(v || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim().toUpperCase();
export const PALLETS = ['Com pallets', 'Sem pallets', 'Leva pallets', 'Solicitar pallets com liberação do vendedor'];
export const DOCUMENTS = ['XML NF', 'PDF NF', 'BOLETO FORNECEDOR', 'NF PALLETS', 'COMPROVANTE FRETE', 'COMPROVANTE PAGAMENTO CLIENTE', 'COMPROVANTE ENVIO FORNECEDOR', 'COMPROVANTE ENVIO MOTORISTA', 'COMPROVANTE ENTREGA'];
const active = x => x.ativo !== false;
const arr = (s,k) => s[k] || [];
const cents = n => Math.round(Number(n) * 100) / 100;
const fail = msg => { throw new Error(msg); };
const text = (v,label) => String(v || '').trim() || fail(`Informe ${label}.`);
const num = (v,label,zero=false) => { const n=Number(v); if(!Number.isFinite(n)||(zero?n<0:n<=0))fail(`Confira ${label}.`); return n; };
const integer = (v,label,zero=false) => {const n=num(v,label,zero);if(!Number.isSafeInteger(n))fail(`${label} deve ser inteiro.`);return n;};
const byId = (s,k,id,label) => arr(s,k).find(x=>x.id===id&&active(x)) || fail(`${label} não localizado ou inativo.`);
const privileged = p => ['MASTER','ADMINISTRADOR'].includes(p.perfil);
export function isResaleProduct(p) {
 const purpose=norm(p?.finalidade||p?.purpose||p?.tipoProduto||p?.classificacao||p?.destinacao||'REVENDA');
 return !!p&&active(p)&&p.revenda!==false&&!/USO|CONSUMO|IMOBILIZADO/.test(purpose);
}
export function supplierProducts(s,id) {
 const f=arr(s,'fornecedores').find(x=>x.id===id);if(!f)return [];
 const brands=(f.marcas||norm(f.nome).split(/\s*\/\s*/)).map(norm);
 return arr(s,'produtos').filter(p=>isResaleProduct(p)&&(p.fornecedorId===id||(p.fornecedorIds||[]).includes(id)||arr(s,'custosFornecedor').some(c=>active(c)&&c.fornecedorId===id&&c.produtoId===p.id)||brands.includes(norm(p.marca))));
}
export function supplierTerms(s,id){const f=arr(s,'fornecedores').find(x=>x.id===id)||{};return [...new Set([f.condicaoPagamento,f.formaPagamentoPadrao,...(f.prazosPagamento||[]),...arr(s,'custosFornecedor').filter(c=>active(c)&&c.fornecedorId===id).map(c=>c.condicaoPagamento)].filter(Boolean))];}
export function supplierCost(s,id,product,mode='PADRAO') {const p=arr(s,'produtos').find(p=>p.id===product);return mode==='CSN_DIRETO'?p?.precoNegociadoCsnDireto:mode==='CSN_FIBRA'?p?.precoNegociadoCsnFibra:p?.precoNegociado;}
export function palletQuantity(s,items,rule) {if(rule===PALLETS[1])return 0;return (items||[]).reduce((total,i)=>{const p=arr(s,'produtos').find(p=>p.id===i.produtoId),q=Number(i.qtd||0);if(!q)return total;const per=Number(p?.palletQtd||p?.qtdPorPallet||p?.sacosPorPallet||p?.unidadesPorPallet);if(!Number.isSafeInteger(per)||per<=0)fail('Cadastre a quantidade por pallet do produto '+(p?.nome||'selecionado')+'.');return total+Math.ceil(q/per);},0);}
export function salePrice(s,client,product){const p=arr(s,'produtos').find(x=>x.id===product);const c=arr(s,'precosClientes').find(x=>active(x)&&x.clienteId===client&&x.produtoId===product);return c?.precoFinal??cents(Number(p?.precoTabela||0)*(1-Number(c?.descontoPct||0)/100));}
export function validDriver(s,id,weight){const m=byId(s,'motoristas',id,'Motorista');if(/PENDENTE|ANALISE|RECUSADO|CONFERENCIA|AGUARDANDO/.test(norm(m.statusCadastro)))fail('Motorista aguarda aprovação.');const capacity=num(m.capacidadeMaximaKg||m.capacidadeAlvoKg,'capacidade do conjunto');if(weight>capacity)fail('Peso acima da capacidade do conjunto.');if(!m.placa1)fail('Cadastre a placa do conjunto.');return m;}
function pallets(s,b,p,at){if(!PALLETS.includes(b.regraPallets))fail('Selecione uma das quatro regras de pallets.');const suggested=palletQuantity(s,b.itens,b.regraPallets);const custom=b.palletQuantidadeAjustada;const qty=custom==null||custom===''?suggested:integer(custom,'Quantidade de pallets',true);if(b.regraPallets===PALLETS[1]&&qty!==0)fail('Sem pallets exige quantidade zero.');if(b.regraPallets!==PALLETS[1]&&qty<=0)fail('Informe a quantidade de pallets.');const reason=qty!==suggested?text(b.justificativaPallets,'justificativa do ajuste de pallets'):'';return {regraPallets:b.regraPallets,pallet:b.regraPallets,palletQuantidade:qty,pallets:qty,palletQuantidadeSugerida:suggested,palletQuantidadeAjustada:qty!==suggested?qty:'',justificativaPallets:reason,aprovacaoPallets:null,liberacaoPalletsFornecedor:null};}

function purchaseItems(s,b,p,at){const mode=b.modalidadeCompra||'PADRAO';if(!PURCHASE_MODES.includes(mode))fail('Modalidade de compra inválida.');if(mode!=='PADRAO'&&!norm(byId(s,'fornecedores',b.fornecedorId,'Fornecedor').nome).includes('CSN'))fail('Direto/Fibra disponíveis somente para CSN.');const allowed=supplierProducts(s,b.fornecedorId);if(!b.itens?.length)fail('Inclua ao menos um produto.');const seen=new Set();return b.itens.map(i=>{if(seen.has(i.produtoId))fail('Consolide quantidades do mesmo produto.');seen.add(i.produtoId);const prod=allowed.find(x=>x.id===i.produtoId)||fail('Produto não vinculado ao fornecedor.');const qtd=integer(i.qtd,'Quantidade'),pesoKg=qtd*num(prod.pesoKg,'peso cadastrado do produto');const cost=supplierCost(s,b.fornecedorId,prod.id,mode);const price=num(cost,'preço negociado no cadastro de produtos');if(i.custoUnitario!=null&&i.custoUnitario!==''&&cents(Number(i.custoUnitario))!==cents(price))fail('Preço negociado mudou no cadastro; selecione novamente o produto.');return {produtoId:prod.id,produto:prod.nome,marca:prod.marca,unidadeMedida:prod.unidadeMedida||prod.unidade||'sacos',qtd,pesoKg,custoUnitario:price,total:cents(qtd*price)};});}
function officialUnique(s,f,n,except){if(arr(s,'cargas').some(c=>c.id!==except&&c.status!=='CANCELADA'&&c.fornecedorId===f&&norm(c.numeroPedidoFornecedor)===norm(n)))fail('Este pedido oficial já está vinculado a outra carga.');}
function next(s,key,prefix,collection,field){let seq=Number(s.settings?.[key]||1);const used=new Set(arr(s,collection).map(x=>x[field]));let code;do{code=prefix+String(seq++).padStart(6,'0');}while(used.has(code));s.settings={...s.settings,[key]:seq};return code;}
function ensureLoad(s,order,id,at){let c=arr(s,'cargas').find(x=>x.compraFornecedorId===order.id||x.id===order.cargaId);if(c)return c;const f=byId(s,'fornecedores',order.fornecedorId,'Fornecedor');c={id,codigo:next(s,'nextCargaSeq','FC-','cargas','codigo'),compraFornecedorId:order.id,fornecedorId:f.id,fornecedor:f.nome,marca:order.itens.map(i=>i.marca).filter(Boolean).join(' / '),itens:order.itens,produtoId:order.itens[0].produtoId,produto:order.itens.map(i=>i.produto).join(' / '),qtd:order.itens.reduce((a,i)=>a+i.qtd,0),pesoKg:order.pesoKg,qtdSemDestino:order.itens.reduce((a,i)=>a+i.qtd,0),motoristaId:order.motoristaId,motorista:order.motorista,placas:order.placas,unidadeId:order.unidadeId,unidade:order.unidade,origem:order.origem,localCarregamento:order.origem,destino:order.destino,destinoTipo:order.destinoTipo,modalidadeFrete:order.modalidadeFrete,condicaoFornecedor:order.pagamento,modalidadeCompra:order.modalidadeCompra||'PADRAO',motoristaSnapshot:structuredClone(order.motoristaSnapshot),fornecedorSnapshot:structuredClone(order.fornecedorSnapshot),liberacaoPalletsFornecedor:order.liberacaoPalletsFornecedor,regraPallets:order.regraPallets,pallet:order.pallet,palletQuantidade:order.palletQuantidade,aprovacaoPallets:order.aprovacaoPallets,nfPalletsAplica:order.nfPalletsAplica,numeroPedidoFornecedor:order.numeroPedidoFornecedor||'',vendaIds:[],status:'VERMELHO',fase:order.numeroPedidoFornecedor?'AGUARDANDO NOTAS FISCAIS':'AGUARDANDO RETORNO DO FORNECEDOR',criadaEm:at};s.cargas=[...arr(s,'cargas'),c];order.cargaId=c.id;order.codigoCarga=c.codigo;return c;}
export function documentStatus(s,c,type){if(type==='COMPROVANTE ENTREGA'){const ids=c.vendaIds||[],jobs=arr(s,'comunicacoes').filter(j=>j.kind==='ENTREGA'&&j.cargaId===c.id&&j.reply?.answer==='SIM');if(ids.length&&ids.every(id=>jobs.some(j=>j.vendaIds.includes(id))))return 'VALIDADO';}if(type==='COMPROVANTE FRETE'&&c.modalidadeFrete==='CIF')return 'NÃO SE APLICA';if(type==='NF PALLETS'&&c.nfPalletsAplica===false)return 'NÃO SE APLICA';const docs=arr(s,'documentos').filter(d=>d.cargaId===c.id&&d.categoria===type);return docs.some(d=>d.validationStatus==='VALIDADO')?'VALIDADO':docs.length?'RECEBIDO — CONFERIR':'PENDENTE';}
export function applyWorkflow(original,b,p,{id,at}){
 if(!p.ativo||p.status_aprovacao!=='APROVADO'||p.trocar_senha||!['MASTER','ADMINISTRADOR','OPERADOR_GERAL','VENDEDOR_INTERNO'].includes(p.perfil))fail('Acesso ativo e aprovado necessário.');
 const request=JSON.stringify(Object.fromEntries(Object.entries(b).filter(([k])=>!k.startsWith('internal'))));
 const key=text(b.requestId,'identificador da operação');if(key.length>100)fail('Identificador inválido.');
 const prior=arr(original,'workflowEvents').find(e=>e.requestId===key);if(prior){if(prior.actor!==p.user_id||prior.action!==b.action||prior.request!==request)fail('Identificador já utilizado por outra operação.');return {state:original,result:prior.result,replayed:true};}
 const s=structuredClone(original);let result={};
 const purchase=()=>arr(s,'comprasFornecedor').find(x=>x.id===b.id&&(b.action==='SUPPLIER_CANCEL'||x.status!=='CANCELADO'))||fail('Pedido não localizado.');
 const load=()=>arr(s,'cargas').find(x=>x.id===b.cargaId&&x.status!=='CANCELADA')||fail('Carga não localizada.');
 if(b.action==='DRIVERS_IMPORTED'){
  const imported=b.internalDrivers||[];s.motoristas=[...arr(s,'motoristas').filter(m=>m.origemCadastro!=='FORTE FRETE'),...imported];result={count:imported.length};
 }else if(b.action==='FRETE_PUBLISHED'){
  const c=load();if(palletReleaseNeeded(c))fail('Liberação de pallets pendente.');Object.assign(c,{fretePublicadaId:b.internalReceipt.id,fretePublicadaEm:at,ordemMotoristaEnviada:true,ordemEnviadaEm:b.internalReceipt.enviadaEm,ordemCanal:'FORTE FRETE',ordemDestinatario:b.internalReceipt.motoristaId,fase:'ORDEM DISPONÍVEL NO FORTE FRETE'});result={cargaId:c.id,freteId:b.internalReceipt.id};
 }else if(['SUPPLIER_CREATE','SUPPLIER_EDIT'].includes(b.action)){
  const old=b.action==='SUPPLIER_EDIT'?purchase():null;if(old&&!canEditPurchase(s,old))fail('Pedido enviado, cancelado, confirmado ou faturado não pode ser editado.');const editReason=old?text(b.motivo,'motivo da edição'):'';
  const f=byId(s,'fornecedores',b.fornecedorId,'Fornecedor'),u=byId(s,'unidades',b.unidadeId,'Unidade');
  if(!supplierTerms(s,f.id).some(t=>norm(t)===norm(b.pagamento)))fail('Cadastre o prazo no fornecedor antes de gravar.');
  const itens=purchaseItems(s,b,p,at),pesoKg=itens.reduce((a,i)=>a+i.pesoKg,0),m=b.motoristaId?validDriver(s,b.motoristaId,pesoKg):null;
  if(!['FOB','CIF'].includes(b.modalidadeFrete)||!['GALPÃO','VENDA DIRETA','A DEFINIR'].includes(b.destinoTipo))fail('Selecione modalidade e tipo de destino.');
  const order={id:old?.id||id,numero:old?.numero||next(s,'nextCompraSeq',`COMP-${at.slice(0,4)}-`,'comprasFornecedor','numero'),fornecedorId:f.id,fornecedor:f.nome,unidadeId:u.id,unidade:u.nome,modalidadeCompra:b.modalidadeCompra||'PADRAO',fornecedorSnapshot:supplierSnapshot(f),motoristaSnapshot:driverSnapshot(m),codigoFornecedor:f.codigoCliente||f.codigoForte||'',itens,pesoKg,custoTotal:cents(itens.reduce((a,i)=>a+i.total,0)),qtd:itens.reduce((a,i)=>a+i.qtd,0),produto:itens.map(i=>i.produto).join(' / '),motoristaId:m?.id||'',motorista:m?.nome||'',placas:m?[m.placa1,m.placa2,m.placa3,m.placa4].filter(Boolean):[],origem:text(b.origem,'expedição'),destino:text(b.destino,'destino'),destinoTipo:b.destinoTipo,modalidadeFrete:b.modalidadeFrete,pagamento:b.pagamento,...pallets(s,b,p,at),nfPalletsAplica:b.regraPallets!==PALLETS[1],origemPreenchimento:b.origemPreenchimento||'MANUAL',status:'RASCUNHO — NÃO ENVIADO',criadaEm:old?.criadaEm||at,criadaPor:old?.criadaPor||p.nome,revisao:old?(old.revisao||0)+1:0,historico:[...(old?.historico||[]),{id,acao:old?'EDIÇÃO':'CRIAÇÃO',at,actor:p.user_id,motivo:editReason,...(old?{antes:purchaseSnapshot(old)}:{})}]};
  if(old){const c=arr(s,'cargas').find(c=>c.id===old.cargaId);if(c?.vendaIds?.length&&(c.fornecedorId!==order.fornecedorId||c.unidadeId!==order.unidadeId))fail('Carga com vendas vinculadas: mantenha fornecedor e unidade.');for(const v of arr(s,'vendas').filter(v=>c?.vendaIds?.includes(v.id))){const i=order.itens.find(i=>i.produtoId===v.produtoId);const qty=arr(s,'vendas').filter(x=>c.vendaIds.includes(x.id)&&x.produtoId===v.produtoId).reduce((a,x)=>a+Number(x.qtd),0);if(!i||qty>i.qtd)fail('Ajuste primeiro as vendas vinculadas.');}order.cargaId=old.cargaId;order.codigoCarga=old.codigoCarga;if(c)Object.assign(c,{...order,condicaoFornecedor:order.pagamento,localCarregamento:order.origem,qtdSemDestino:order.qtd-arr(s,'vendas').filter(v=>c.vendaIds?.includes(v.id)).reduce((a,v)=>a+Number(v.qtd),0),id:c.id,codigo:c.codigo,compraFornecedorId:old.id,status:'VERMELHO',vendaIds:c.vendaIds||[],fase:'PEDIDO EDITADO — CONFERIR ESPELHO'});for(const j of arr(s,'comunicacoes').filter(j=>j.compraFornecedorId===old.id&&['QUEUED','BLOCKED','FAILED'].includes(j.state))){j.state='CANCELLED';j.reason='PEDIDO EDITADO';}s.comprasFornecedor=arr(s,'comprasFornecedor').map(x=>x.id===old.id?order:x);}else s.comprasFornecedor=[...arr(s,'comprasFornecedor'),order];const c=ensureLoad(s,order,id+'-carga',at);c.fase='PEDIDO EM CONFERÊNCIA — ENVIO PENDENTE';result={id:order.id,numero:order.numero,cargaId:c.id};
 }else if(b.action==='SUPPLIER_CANCEL'){
  const o=purchase(),c=arr(s,'cargas').find(c=>c.id===o.cargaId);if(o.status==='CANCELADO')fail('Pedido já cancelado.');if(c?.fretePublicadaId||c?.ordemEnviadaEm)fail('Ordem já enviada ao motorista: revise o cancelamento operacional antes de cancelar.');if(c?.finalizadaEm||c&&arr(s,'documentos').some(d=>d.cargaId===c.id&&['XML NF','PDF NF'].includes(d.categoria)))fail('Pedido faturado ou carga finalizada exige revisão fiscal.');if(arr(s,'comunicacoes').some(j=>j.compraFornecedorId===o.id&&j.state==='SENDING'))fail('Aguarde a conclusão do envio antes de cancelar.');const motivo=text(b.motivo,'motivo do cancelamento');o.status='CANCELADO';o.canceladoEm=at;o.canceladoPor=p.user_id;o.historico=[...(o.historico||[]),{id,acao:'CANCELAMENTO',at,actor:p.user_id,motivo}];if(c){c.status='CANCELADA';c.fase='CANCELADA';for(const v of arr(s,'vendas').filter(v=>v.cargaId===c.id)){v.cargaId='';v.destinoPainel='AGUARDANDO ROTEAMENTO';}c.vendaIds=[];}for(const j of arr(s,'comunicacoes').filter(j=>(j.compraFornecedorId===o.id||j.cargaId===c?.id)&&['QUEUED','BLOCKED','FAILED'].includes(j.state))){j.state='CANCELLED';j.reason='PEDIDO CANCELADO';}result={id:o.id,warning:'Cancelamento registrado sem apagar o histórico. Se o fornecedor já recebeu o pedido, confirme o cancelamento com ele.'};
 }else if(b.action==='PALLETS_RELEASE'){
  if(!privileged(p)&&p.permissoes?.liberarPallets!==true)fail('Sem permissão para registrar a liberação.');const c=load();if(c.finalizadaEm)fail('Carga finalizada.');if(!String(c.regraPallets).startsWith('Solicitar'))fail('Esta carga não solicita liberação.');c.liberacaoPalletsFornecedor={evidencia:text(b.evidencia,'referência da autorização do fornecedor'),at,actor:p.user_id};const o=arr(s,'comprasFornecedor').find(o=>o.id===c.compraFornecedorId);if(o)o.liberacaoPalletsFornecedor=structuredClone(c.liberacaoPalletsFornecedor);result={cargaId:c.id};
 }else if(b.action==='SUPPLIER_PREVIEW'){
  const o=purchase();o.espelhoConferido={snapshot:purchaseSnapshot(o),at,actor:p.user_id};result={id:o.id};
 }else if(b.action==='SUPPLIER_SEND'){
  const o=purchase();if(o.espelhoConferido?.snapshot!==purchaseSnapshot(o)||o.espelhoConferido?.actor!==p.user_id)fail('Abra e confira o espelho atualizado antes de enviar.');
  if(!['WHATSAPP','EMAIL','AMBOS'].includes(b.canal))fail('Selecione WhatsApp, e-mail ou ambos.');const f=byId(s,'fornecedores',o.fornecedorId,'Fornecedor');
  const channels=b.canal==='AMBOS'?['WHATSAPP','EMAIL']:[b.canal];const destinations=channels.map(c=>c==='WHATSAPP'?phone(f.whatsapp||f.telefone):String(f.emailPedidos||f.email||'').trim());if(destinations.some((to,i)=>!to||channels[i]==='EMAIL'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(to)))fail('Cadastre os contatos dos canais selecionados no fornecedor.');
  s.comunicacoes??=[];channels.forEach((canal,i)=>{const key=o.id+':'+(o.revisao||0)+':FORNECEDOR:'+canal;const prior=s.comunicacoes.find(j=>j.key===key);if(prior)return;s.comunicacoes.push({id:key,key,kind:'FORNECEDOR',audience:'FORNECEDOR',canal,to:destinations[i],compraFornecedorId:o.id,cargaId:o.cargaId,reference:o.numero,snapshot:purchaseSnapshot(o),order:structuredClone(o),message:'FORTE ATACAREJO — Pedido '+o.numero+'. '+itemsText(o.itens)+'. Expedição: '+o.origem+'. Destino: '+o.destino+'. Motorista: '+(o.motorista||'A definir')+'. Placas: '+o.placas.join(' / ')+'. Pagamento: '+o.pagamento+'. Pallets: '+o.regraPallets+' — '+o.palletQuantidade+'. Responda a esta mensagem informando o número oficial do pedido.',state:'QUEUED',createdAt:at});});o.status='ENVIO PENDENTE';result={id:o.id,queued:channels.length};
 }else if(b.action==='CUSTOMER_CONSENT'){
  const c=byId(s,'clientes',b.clienteId,'Cliente');const evidence=text(b.evidencia,'evidência da autorização do cliente');c.whatsappAutorizado=b.autorizado===true;c.whatsappAutorizacao={actor:p.user_id,at,evidencia:evidence};for(const j of arr(s,'comunicacoes').filter(j=>j.clienteId===c.id&&['QUEUED','BLOCKED'].includes(j.state))){j.to=phone(c.whatsapp||c.telefone);j.state=c.whatsappAutorizado&&j.to?'QUEUED':'BLOCKED';j.reason=j.state==='BLOCKED'?'CONTATO OU AUTORIZAÇÃO PENDENTE':'';}result={id:c.id};
 }else if(b.action==='SALE_ADJUST'){
  const v=arr(s,'vendas').find(v=>v.id===b.vendaId&&v.status!=='CANCELADA')||fail('Venda não localizada.');const c=arr(s,'cargas').find(c=>c.id===v.cargaId);if(c?.finalizadaEm||v.status==='ENTREGUE')fail('Entrega finalizada não pode ser ajustada.');
  const group=arr(s,'vendas').filter(x=>(x.grupoPedidoId||x.id)===(v.grupoPedidoId||v.id)),ids=group.map(x=>x.id);if(arr(s,'boletosClientes').some(t=>(ids.includes(t.vendaId)||t.vendaId===v.grupoPedidoId)&&(t.nossoNumero||t.idCobranca))||arr(s,'contasReceber').some(t=>ids.includes(t.vendaId)&&t.idCobranca)||v.nf||v.numeroNF||v.chaveNfe||v.nfeId||c&&arr(s,'documentos').some(d=>d.cargaId===c.id&&['XML NF','PDF NF'].includes(d.categoria)))fail('Pedido com documento fiscal ou cobrança emitida exige revisão antes de alterar.');
  const qty=integer(b.qtd,'Quantidade ajustada');if(qty>=Number(v.qtd))fail('O ajuste para carregamento deve reduzir a quantidade.');const reason=text(b.motivo,'motivo do ajuste'),previous=itemsText(group),oldQty=v.qtd,weightPerUnit=num(v.pesoKg,'peso original')/oldQty;v.qtd=qty;v.pesoKg=qty*weightPerUnit;v.totalVenda=cents(qty*num(v.precoUnitario,'preço'));v.freteValor=cents(v.pesoKg/1000*Number(v.fretePorTon||0));v.totalGeral=cents(v.totalVenda+(v.freteIncluso?0:v.freteValor));v.ajustes=[...(v.ajustes||[]),{id,antes:oldQty,depois:qty,motivo:reason,actor:p.user_id,at}];
  for(const j of arr(s,'comunicacoes').filter(j=>j.vendaIds?.includes(v.id)&&['QUEUED','BLOCKED','FAILED'].includes(j.state))){j.state='CANCELLED';j.reason='SUBSTITUÍDA PELO PEDIDO AJUSTADO';}queueCustomer(s,group,'AJUSTE',id,at,previous);result={id:v.id,antes:oldQty,depois:qty,saldoPendente:0};
 }else if(b.action==='LOAD_ADJUST'){
  const c=load(),o=arr(s,'comprasFornecedor').find(o=>o.id===c.compraFornecedorId);if(!o||c.finalizadaEm||c.ordemRevisadaEm||o.numeroPedidoFornecedor||o.envioComprovadoEm||arr(s,'comunicacoes').some(j=>j.compraFornecedorId===o.id&&['SENDING','SENT','DELIVERED','READ','UNCERTAIN'].includes(j.state))||arr(s,'documentos').some(d=>d.cargaId===c.id&&['XML NF','PDF NF'].includes(d.categoria)))fail('Compra enviada, confirmada ou faturada exige revisão com o fornecedor.');
  const reason=text(b.motivo,'motivo do ajuste');if(!b.itens?.length||b.itens.length!==o.itens.length||b.itens.some(i=>!o.itens.some(x=>x.produtoId===i.produtoId&&Number(i.qtd)<=x.qtd)))fail('Ajuste somente as quantidades dos produtos existentes.');const seen=new Set();const itens=b.itens.map(i=>{if(seen.has(i.produtoId))fail('Consolide os produtos.');seen.add(i.produtoId);const old=o.itens.find(x=>x.produtoId===i.produtoId),qtd=integer(i.qtd,'Quantidade ajustada'),price=num(old.custoUnitario,'custo original');return {...old,qtd,pesoKg:qtd*num(old.pesoKg,'peso original')/old.qtd,total:cents(qtd*price)};});for(const i of itens){const distributed=arr(s,'vendas').filter(v=>(c.vendaIds||[]).includes(v.id)&&v.produtoId===i.produtoId).reduce((a,v)=>a+Number(v.qtd),0);if(distributed>i.qtd)fail('Ajuste primeiro os pedidos dos clientes para caber na carga.');}const before=structuredClone(o.itens),pesoKg=itens.reduce((a,i)=>a+i.pesoKg,0);if(o.motoristaId)validDriver(s,o.motoristaId,pesoKg);const updatedPallets=pallets(s,{...o,itens,palletQuantidadeAjustada:'',justificativaPallets:''},p,at),palletQuantidade=updatedPallets.palletQuantidade;Object.assign(o,{...updatedPallets,itens,pesoKg,qtd:itens.reduce((a,i)=>a+i.qtd,0),custoTotal:cents(itens.reduce((a,i)=>a+i.total,0)),palletQuantidade,pallets:palletQuantidade,status:'RASCUNHO — NÃO ENVIADO',espelhoConferido:null,revisao:(o.revisao||0)+1});Object.assign(c,{...updatedPallets,itens:structuredClone(itens),pesoKg,qtd:o.qtd,palletQuantidade,pallets:palletQuantidade});for(const j of arr(s,'comunicacoes').filter(j=>j.compraFornecedorId===o.id))j.state='CANCELLED';o.historico=[...(o.historico||[]),{id,acao:'AJUSTE DE QUANTIDADE',at,actor:p.user_id,motivo:reason}];c.ajustes=[...(c.ajustes||[]),{id,antes:before,depois:structuredClone(itens),motivo:reason,at,actor:p.user_id}];result={cargaId:c.id};
 }else if(b.action==='SUPPLIER_TERM'){
  if(!privileged(p)&&p.permissoes?.editarFornecedor!==true)fail('Seu perfil não pode alterar o prazo do fornecedor.');const f=byId(s,'fornecedores',b.fornecedorId,'Fornecedor');const term=text(b.pagamento,'prazo');f.prazosPagamento=[...new Set([...(f.prazosPagamento||[]),term])];result={id:f.id};
 }else if(b.action==='SUPPLIER_RECEIPT'){
  const o=purchase();if(o.envioComprovadoEm)fail('Envio já registrado para este pedido.');const recipient=text(b.destinatario,'destinatário');if(!['WHATSAPP','EMAIL','PORTAL'].includes(b.canal))fail('Selecione o canal.');
  const d=arr(s,'documentos').find(d=>d.id===b.documentoId&&d.compraFornecedorId===o.id&&d.categoria==='COMPROVANTE ENVIO FORNECEDOR')||fail('Anexe o comprovante do envio ao pedido.');
  Object.assign(d,{validationStatus:'VALIDADO',conferente:p.nome,validadoEm:at});Object.assign(o,{status:'AGUARDANDO RETORNO DO FORNECEDOR',envioComprovadoEm:at,envioComprovadoPor:p.nome,canalEnvio:b.canal,destinatario:recipient,envioDocumentoId:d.id});const c=ensureLoad(s,o,id,at);d.cargaId=c.id;result={id:o.id,cargaId:c.id};
 }else if(b.action==='OFFICIAL_CONFIRM'){
  const o=purchase(),n=text(b.numeroPedidoFornecedor,'número oficial'),evidence=text(b.evidencia,'referência do documento ou retorno conferido');if(o.numeroPedidoFornecedor&&norm(o.numeroPedidoFornecedor)!==norm(n))fail('Pedido já confirmado; alteração exige revisão administrativa.');officialUnique(s,o.fornecedorId,n,o.cargaId);o.numeroPedidoFornecedor=n;o.evidenciaRetorno=evidence;o.confirmadoEm=at;o.confirmadoPor=p.nome;o.status='AGUARDANDO NOTAS FISCAIS';const c=ensureLoad(s,o,id,at);Object.assign(c,{numeroPedidoFornecedor:n,fase:'AGUARDANDO NOTAS FISCAIS',pedidoConfirmadoEm:at,pedidoConfirmadoPor:p.nome});result={id:o.id,cargaId:c.id};
 }else if(b.action==='SALE_CREATE'){
  const customer=byId(s,'clientes',b.clienteId,'Cliente'),seller=byId(s,'usuarios',b.vendedorId,'Vendedor');if(!b.itens?.length)fail('Inclua produtos.');if(!['PIX','DINHEIRO','TRANSFERÊNCIA','CARTÃO','BOLETO','A PRAZO'].includes(b.formaPagamento))fail('Selecione o recebimento.');const prazo=text(b.condicaoPagamento,'condição de pagamento'),destino=text(b.destino,'endereço ou obra'),rate=num(b.fretePorTon||0,'frete por tonelada',true);const group=id,number=next(s,'nextVendaSeq',`VEN-${at.slice(0,4)}-`,'vendas','numeroVenda');
  const rows=b.itens.map((i,index)=>{const prod=byId(s,'produtos',i.produtoId,'Produto');if(norm(i.marca)!==norm(prod.marca)||!prod.marca)fail('Selecione a marca antes do produto.');if(!isResaleProduct(prod))fail('Produto não classificado para revenda.');const qtd=integer(i.qtd,'Quantidade'),price=num(i.precoUnitario,'preço unitário'),expected=salePrice(s,customer.id,prod.id);if((expected<=0||cents(price)!==cents(expected))&&!privileged(p)&&p.permissoes?.editarPreco!==true)fail('Preço diferente do cadastro exige autorização.');const pesoKg=qtd*num(prod.pesoKg,'peso cadastrado');return {id:`${id}-${index}`,grupoPedidoId:group,numeroVenda:number,clienteId:customer.id,cliente:customer.nome,clienteEmail:customer.email||'',clienteWhatsapp:customer.whatsapp||customer.telefone||'',vendedorId:seller.id,vendedorNome:seller.nome,produtoId:prod.id,produto:prod.nome,marca:prod.marca,unidadeMedida:prod.unidadeMedida||prod.unidade||'sacos',qtd,pesoKg,precoUnitario:price,totalVenda:cents(qtd*price),fretePorTon:rate,freteValor:cents(pesoKg/1000*rate),freteIncluso:!!b.freteIncluso,totalGeral:cents(qtd*price+(b.freteIncluso?0:pesoKg/1000*rate)),formaPagamento:b.formaPagamento,condicaoPagamento:prazo,destino,status:'APROVADO',origemComercial:'VR',workflowInterno:true,destinoPainel:'AGUARDANDO ROTEAMENTO',criadoEm:at,dataOperacao:at.slice(0,10)};});
  if(['BOLETO','A PRAZO'].includes(b.formaPagamento)){const total=rows.reduce((a,v)=>a+v.totalGeral,0),used=arr(s,'contasReceber').filter(x=>x.clienteId===customer.id&&!/LIQUIDADO|PAGO|RECEBIDO/.test(norm(x.status))).reduce((a,x)=>a+Number(x.saldoAberto??x.valor??0),0)+arr(s,'vendas').filter(v=>v.clienteId===customer.id&&!['CANCELADA','ENTREGUE'].includes(v.status)&&['BOLETO','A PRAZO'].includes(v.formaPagamento)&&!arr(s,'contasReceber').some(t=>t.vendaId===v.id)).reduce((a,v)=>a+Number(v.totalGeral||v.totalVenda||Number(v.qtd)*Number(v.precoUnitario)),0);if(total>Math.max(0,Number(customer.limiteCredito||0)-used))fail('Pedido excede o crédito disponível do cliente.');}
  s.vendas=[...arr(s,'vendas'),...rows];queueCustomer(s,rows,'PEDIDO',id,at);result={id:group,numero:number};
 }else if(b.action==='LOADING_SAVE'){
  const f=byId(s,'fornecedores',b.fornecedorId,'Fornecedor'),n=text(b.numeroPedidoFornecedor,'número oficial');const existing=arr(s,'cargas').filter(c=>c.status!=='CANCELADA'&&c.fornecedorId===f.id&&norm(c.numeroPedidoFornecedor)===norm(n));if(existing.length>1)fail('Há múltiplas cargas para este número. Solicite conferência.');let c=existing[0];if(b.cargaId&&c?.id!==b.cargaId)fail('Pedido não corresponde à carga selecionada.');if(c?.finalizadaEm)fail('Carga já finalizada.');text(b.evidencia,'documento ou retorno conferido');
  const date=text(b.dataCarregamento,'data');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date)fail('Data inválida.');
  if(!c){const u=byId(s,'unidades',b.unidadeId,'Unidade');if(!supplierTerms(s,f.id).some(t=>norm(t)===norm(b.pagamento)))fail('Cadastre o prazo do fornecedor.');const itens=purchaseItems(s,b,p,at);const o={id:id+'-compra',fornecedorId:f.id,fornecedor:f.nome,itens,pesoKg:itens.reduce((a,i)=>a+i.pesoKg,0),unidadeId:u.id,unidade:u.nome,origem:text(b.origem,'origem'),destino:text(b.destino,'destino'),destinoTipo:b.destinoTipo,pagamento:b.pagamento,modalidadeFrete:b.modalidadeFrete,numeroPedidoFornecedor:n,...pallets(s,b,p,at),nfPalletsAplica:b.regraPallets!==PALLETS[1]};if(!['GALPÃO','VENDA DIRETA','A DEFINIR'].includes(o.destinoTipo)||!['FOB','CIF'].includes(o.modalidadeFrete))fail('Selecione destino e modalidade.');o.motoristaSnapshot=null;o.fornecedorSnapshot=supplierSnapshot(f);o.modalidadeCompra=b.modalidadeCompra||'PADRAO';c=ensureLoad(s,o,id,at);c.pedidoExterno=true;}
  if(palletReleaseNeeded(c))fail('Carregamento bloqueado: registre a liberação de pallets pelo fornecedor.');const m=validDriver(s,b.motoristaId,c.pesoKg),rate=num(b.fretePorTon||0,'frete por tonelada',true);Object.assign(c,{motoristaSnapshot:driverSnapshot(m),motoristaId:m.id,motorista:m.nome,placas:[m.placa1,m.placa2,m.placa3,m.placa4].filter(Boolean),placa:m.placa1,dataCarregamento:date,evidenciaPedido:b.evidencia,origemPreenchimento:b.origemPreenchimento||'MANUAL',fretePorTon:rate,freteValor:c.modalidadeFrete==='CIF'?0:cents(c.pesoKg/1000*rate),ordemRevisadaEm:at,ordemRevisadaPor:p.nome,fase:'ORDEM PREPARADA — ENVIO PENDENTE'});queueLoading(s,c,id,at);result={id:c.id,cargaId:c.id};
 }else if(b.action==='SALE_LINK'){
  const c=load();if(c.finalizadaEm)fail('Carga finalizada.');const rows=arr(s,'vendas').filter(v=>v.grupoPedidoId===b.vendaId||v.id===b.vendaId);if(!rows.length||rows.some(v=>v.status==='CANCELADA'||v.cargaId&&v.cargaId!==c.id))fail('Venda indisponível ou vinculada a outra carga.');const future=[...new Set([...(c.vendaIds||[]),...rows.map(v=>v.id)])];for(const i of c.itens||[]){const qty=arr(s,'vendas').filter(v=>future.includes(v.id)&&v.produtoId===i.produtoId).reduce((a,v)=>a+Number(v.qtd),0);if(qty>i.qtd)fail('Quantidade de venda maior que a quantidade deste produto na carga.');}if(rows.some(v=>!(c.itens||[]).some(i=>i.produtoId===v.produtoId)))fail('Produto da venda não consta na carga.');c.vendaIds=future;rows.forEach(v=>{v.cargaId=c.id;v.destinoPainel='CARGA DIRETA';});if(c.ordemRevisadaEm)queueCustomer(s,rows,'CARREGAMENTO',c.ordemRevisadaEm,at);result={cargaId:c.id};
 }else if(b.action==='DOCUMENT_ADD'){
  const c=b.cargaId?load():null,o=b.compraFornecedorId?arr(s,'comprasFornecedor').find(x=>x.id===b.compraFornecedorId):null;if(!c&&!o)fail('Selecione o pedido ou carga.');if(!DOCUMENTS.includes(b.categoria))fail('Categoria inválida.');const path=text(b.path,'arquivo'),hash=text(b.hash,'hash do arquivo');if(!path.startsWith(p.empresa_id+'/')||!/^[a-f0-9]{64}$/.test(hash))fail('Arquivo inválido ou de outra empresa.');const existing=arr(s,'documentos').find(d=>d.cargaId===(c?.id||'')&&d.compraFornecedorId===(o?.id||'')&&d.categoria===b.categoria&&d.hash===hash);if(existing)result={id:existing.id};else{const d={id,cargaId:c?.id||'',compraFornecedorId:o?.id||'',categoria:b.categoria,tipo:b.categoria,filename:text(b.filename,'nome do arquivo'),storageBucket:'forte-vendas-dossies',storagePath:path,hash,validationStatus:'RECEBIDO',identificacaoConfirmada:false,origem:'ANEXO MANUAL',receivedAt:at,usuario:p.nome};s.documentos=[...arr(s,'documentos'),d];result={id};}
 }else if(b.action==='DOCUMENT_VALIDATE'){
  const c=load(),d=arr(s,'documentos').find(x=>x.id===b.documentoId&&x.cargaId===c.id)||fail('Documento não localizado nesta carga.');text(b.evidencia,'referência conferida');Object.assign(d,{validationStatus:'VALIDADO',identificacaoConfirmada:true,validadoEm:at,conferente:p.nome,evidencia:b.evidencia});result={id:d.id};
 }else if(b.action==='DRIVER_RECEIPT'){
  const c=load();if(palletReleaseNeeded(c))fail('Liberação de pallets pendente.');if(!c.ordemRevisadaEm||!c.numeroPedidoFornecedor)fail('Revise e grave a ordem primeiro.');const d=arr(s,'documentos').find(x=>x.id===b.documentoId&&x.cargaId===c.id&&x.categoria==='COMPROVANTE ENVIO MOTORISTA')||fail('Anexe comprovante de envio ao motorista.');Object.assign(d,{validationStatus:'VALIDADO',validadoEm:at,conferente:p.nome});Object.assign(c,{ordemMotoristaEnviada:true,ordemEnviadaEm:at,ordemDestinatario:text(b.destinatario,'destinatário'),ordemCanal:text(b.canal,'canal'),ordemDocumentoId:d.id,fase:'AGUARDANDO NOTAS FISCAIS'});result={cargaId:c.id};
 }else if(b.action==='LOAD_FINALIZE'){
  const c=load();if(palletReleaseNeeded(c))fail('Liberação de pallets pendente.');if(c.finalizadaEm)fail('Carga já finalizada.');if(!c.numeroPedidoFornecedor||!c.ordemMotoristaEnviada||!c.itens?.length)fail('Pedido, produtos e envio da ordem precisam estar confirmados.');const required=['XML NF','PDF NF','BOLETO FORNECEDOR','COMPROVANTE FRETE','NF PALLETS'];const pending=required.filter(t=>!['VALIDADO','NÃO SE APLICA'].includes(documentStatus(s,c,t)));if(pending.length)fail('Documentos pendentes de validação: '+pending.join(', '));if(c.destinoTipo==='A DEFINIR')fail('Defina a destinação da carga.');if(c.destinoTipo==='VENDA DIRETA'){for(const i of c.itens){if(arr(s,'vendas').filter(v=>(c.vendaIds||[]).includes(v.id)&&v.produtoId===i.produtoId).reduce((a,v)=>a+Number(v.qtd),0)!==i.qtd)fail('Distribua toda a quantidade por produto antes de finalizar.');}}
  if(c.destinoTipo==='VENDA DIRETA'&&documentStatus(s,c,'COMPROVANTE ENTREGA')!=='VALIDADO'){const groups=new Map();for(const v of arr(s,'vendas').filter(v=>(c.vendaIds||[]).includes(v.id))){const key=v.grupoPedidoId||v.id;groups.set(key,[...(groups.get(key)||[]),v]);}for(const rows of groups.values())queueCustomer(s,rows,'ENTREGA',c.id+':ENTREGA',at);c.fase='AGUARDANDO CONFIRMAÇÃO DE ENTREGA';result={cargaId:c.id,warning:'Solicitação de confirmação preparada. A carga aguarda o Sim/Não do cliente ou comprovante de entrega validado.'};}else{
  if(c.destinoTipo==='GALPÃO'&&!arr(s,'estoqueMov').some(m=>m.cargaId===c.id||m.referencia===c.codigo&&String(m.tipo).startsWith('ENTRADA')))s.estoqueMov=[...arr(s,'estoqueMov'),...c.itens.map((i,index)=>({id:id+'-'+index,cargaId:c.id,produtoId:i.produtoId,produto:i.produto,marca:i.marca,unidade:c.unidade,tipo:'ENTRADA - COMPRA FORTE / CARGA',qtd:i.qtd,quantidade:i.qtd,custoUnitario:i.custoUnitario,data:at.slice(0,10),dataHora:at,criadoEm:at,usuario:p.nome,origem:'FINALIZAÇÃO DE CARGA',referencia:c.codigo}))];
  Object.assign(c,{status:'AZUL',fase:'FINALIZADA',finalizadaEm:at,finalizadaPor:p.nome});const groups=new Map();for(const v of arr(s,'vendas').filter(v=>(c.vendaIds||[]).includes(v.id))){const key=v.grupoPedidoId||v.id;groups.set(key,[...(groups.get(key)||[]),v]);}result={cargaId:c.id};}
 }else fail('Ação inválida.');
 // Delivery is recomputed only from a real finalization, delivery receipt and actual billing receipts.
 s.vendas=arr(s,'vendas').map(v=>{const c=arr(s,'cargas').find(c=>c.id===v.cargaId);if(v.status==='CANCELADA'||!c?.finalizadaEm||documentStatus(s,c,'COMPROVANTE ENTREGA')!=='VALIDADO')return v;const group=arr(s,'vendas').filter(x=>(x.grupoPedidoId||x.id)===(v.grupoPedidoId||v.id));const ids=group.map(x=>x.id);const total=group.reduce((a,x)=>a+Number(x.totalGeral||x.totalVenda||Number(x.qtd)*Number(x.precoUnitario)),0);const issued=arr(s,'boletosClientes').filter(t=>(ids.includes(t.vendaId)||t.vendaId===v.grupoPedidoId)&&(t.nossoNumero||t.idCobranca)&&['EMITIDO','REGISTRADO','LIQUIDADO','PAGO'].includes(norm(t.status)));const billing=v.formaPagamento!=='BOLETO'||(issued.length>0&&cents(issued.reduce((a,t)=>a+Number(t.valor||0),0))>=cents(total));return billing?{...v,status:'ENTREGUE',entregueEm:v.entregueEm||at}:v;});
 s.auditoria=[...arr(s,'auditoria'),{id:id+'-aud',acao:b.action,detalhe:JSON.stringify(result),usuario:p.nome,userId:p.user_id,dataHora:at}];s.workflowEvents=[...arr(s,'workflowEvents'),{requestId:key,request,actor:p.user_id,action:b.action,result,at}];return {state:s,result};
}
