const fs=require('fs'),vm=require('vm'),assert=require('assert'),{stripTypeScriptTypes}=require('node:module');
const source=stripTypeScriptTypes(fs.readFileSync(require('path').join(__dirname,'../supabase/functions/mobile-carga-direta/index.ts'),'utf8')).replace(/^import .*;\n/gm,'');
const base={settings:{nextCargaSeq:1,nextVendaSeq:1},cargas:[],vendas:[],comprasFornecedor:[],locais:[{id:'l',nome:'Arcos',senha:'SECRET'}],rotas:[{id:'r',nome:'Caldas Novas',senha:'SECRET'}],pagamentos:[{id:'pg',descricao:'35 DIAS',senha:'SECRET'}],custosFornecedor:[{id:'cf',fornecedorId:'f',produtoId:'p',condicaoPagamento:'14 DIAS',custoUnitario:22}],precosClientes:[{clienteId:'c',produtoId:'p',descontoPct:5}],fornecedores:[{id:'f2',nome:'Outro',emailBusca:'fiscal-interno@example.test'},{id:'f',nome:'Fornecedor',emailPedidos:'pedidos@example.test',whatsapp:'34999999999'}],produtos:[{id:'p',nome:'Cimento',marca:'CSN',pesoKg:50,precoTabela:30}],motoristas:[{id:'m',nome:'Motorista',capacidadeMaximaKg:48000}],clientes:[{id:'c',nome:'Razão Social',nomeFantasia:'Loja do Cliente',limiteCredito:1000,endereco:'Rua do Cliente',vendedorResponsavelId:'v',condicaoPagamento:'14 DIAS',senha:'SECRET'}],usuarios:[{id:'v',nome:'Vendedor'}]};
async function setup({allowed=true,conflict=false}={}){let estado=structuredClone(base),writes=0;const ctx={URL,Response,JSON,Date,Number,String,Error,Math,crypto:require('crypto').webcrypto,Deno:{env:{get:()=>''},serve:fn=>ctx.handler=fn},createClient:()=>({auth:{getUser:async()=>({data:{user:{id:'u'}}})},from(table){let updating=false,next;const q={select(){return q},eq(){return q},is(){return q},update(value){updating=true;next=value.estado;return q},maybeSingle(){return q},then(res){let data=table==='fc_perfis'?{ativo:allowed,perfil:'MASTER',status_aprovacao:'APROVADO',empresa_id:'e',nome:'Admin'}:table==='access_requests'?[]:{estado,updated_at:'previous'};if(updating){data=conflict?[]:[{empresa_id:'e'}];if(!conflict){estado=next;writes++}}return Promise.resolve({data,error:null}).then(res)}};return q;}})};vm.createContext(ctx);vm.runInContext(source,ctx);return {async call(body){const r=await ctx.handler(new Request('https://example.test',{method:'POST',headers:{Authorization:'Bearer test'},body:JSON.stringify(body)}));return {status:r.status,data:await r.json()}},get state(){return estado},get writes(){return writes}}}
(async()=>{let c=await setup();let r=await c.call({acao:'LISTAR'});assert.equal(r.data.produtos.length,1);assert.equal(r.data.clientes.length,1);assert.equal(r.data.clientes[0].nomeFantasia,'Loja do Cliente');assert.equal(r.data.clientes[0].endereco,'Rua do Cliente');assert.equal(r.data.clientes[0].vendedorResponsavelId,'v');assert.equal(r.data.produtos[0].precoTabela,30);assert.equal(r.data.custosFornecedor[0].custoUnitario,22);assert(r.data.condicoesPagamento.includes('35 DIAS'));assert.equal(r.data.fornecedores.find(x=>x.id==='f2').email,'');assert(!JSON.stringify(r.data).includes('SECRET'));
const venda={acao:'CRIAR_VENDA',clienteId:'c',produtoId:'p',vendedorId:'v',qtd:10,precoUnitario:30,condicaoPagamento:'PIX',destino:'Obra',pallet:'SEM PALLETS'};r=await c.call(venda);assert.equal(r.status,200);assert.equal(c.state.vendas[0].status,'PENDENTE');assert.equal(c.state.vendas[0].totalVenda,300);assert.equal(c.state.vendas[0].numeroVenda,'VEN-'+new Date().getFullYear()+'-000001');r=await c.call({...venda,precoUnitario:0});assert.equal(r.status,400);r=await c.call({...venda,condicaoPagamento:'14 DIAS',qtd:100});assert.equal(r.status,400);
r=await c.call({...venda,qtd:800,fretePorTon:140,formaPagamento:'PIX'});assert.equal(r.status,200);const freteVenda=c.state.vendas.at(-1);assert.equal(freteVenda.pesoKg,40000);assert.equal(freteVenda.freteValor,5600);assert.equal(freteVenda.fretePorSaco,7);assert.equal(freteVenda.formaPagamento,'PIX');r=await c.call({...venda,formaPagamento:'INVALIDA'});assert.equal(r.status,400);r=await c.call({...venda,formaPagamento:'BOLETO',condicaoPagamento:'14 DIAS'});assert.equal(r.status,200);assert.equal(c.state.vendas.at(-1).condicaoPagamento,'BOLETO • 14 DIAS');r=await c.call({...venda,formaPagamento:'BOLETO',condicaoPagamento:'INVENTADO'});assert.equal(r.status,400);
r=await c.call({...venda,formaPagamento:'BOLETO',condicaoPagamento:'35 DIAS'});assert.equal(r.status,200);
const compra={acao:'CRIAR_PEDIDO',fornecedorId:'f',produtoId:'p',qtd:10,precoCompra:22,condicao:'14 DIAS',origem:'Arcos',destino:'Caldas Novas',pallet:'SEM PALLETS'};r=await c.call(compra);assert.equal(r.status,200);assert.equal(c.state.comprasFornecedor[0].totalCompra,220);assert.equal(c.state.comprasFornecedor[0].email,'pedidos@example.test');assert.equal(c.state.comprasFornecedor[0].status,'PEDIDO GERADO — AGUARDANDO ENVIO');
r=await c.call({acao:'CRIAR_CARGA',fornecedorId:'f',produtoId:'p',motoristaId:'m',qtd:800,origem:'Arcos',destino:'Caldas Novas',modalidadeFrete:'FOB',fretePorTon:140,pallet:'SEM PALLETS'});assert.equal(r.status,200);assert.equal(c.state.cargas[0].pesoKg,40000);assert.equal(c.state.cargas[0].freteValor,5600);
c=await setup({allowed:false});r=await c.call(venda);assert.equal(r.status,400);assert.equal(c.writes,0);c=await setup({conflict:true});r=await c.call(venda);assert.equal(r.status,400);assert.equal(c.writes,0);console.log('PASS: sale and purchase saved; values, supplier contacts, load weights; zero price, credit limit, permissions and concurrent change blocked.');})().catch(e=>{console.error(e);process.exitCode=1});
