import {test} from 'node:test';
import assert from 'node:assert/strict';
import {applyWorkflow,supplierProducts,documentStatus,isResaleProduct} from '../supabase/functions/orders-workflow/domain.mjs';
const p={user_id:'actor',empresa_id:'e',nome:'Admin',perfil:'MASTER',ativo:true,status_aprovacao:'APROVADO'};
const base=()=>({settings:{},unidades:[{id:'u',nome:'Filial'}],fornecedores:[{id:'f',nome:'CSN',condicaoPagamento:'14 DIAS'},{id:'g',nome:'CIPLAN',condicaoPagamento:'14 DIAS'}],produtos:[{id:'p',nome:'Cimento CSN',marca:'CSN',pesoKg:50,precoNegociado:22,palletQtd:50,precoTabela:34},{id:'q',nome:'Ciplan',marca:'CIPLAN',pesoKg:50,precoNegociado:22,palletQtd:50,precoTabela:34}],locais:[{id:'l',nome:'Arcos',ativo:true}],custosFornecedor:[{fornecedorId:'f',produtoId:'p',condicaoPagamento:'14 DIAS',custoUnitario:22}],motoristas:[{id:'m',nome:'Motorista',placa1:'ABC1D23',capacidadeMaximaKg:40000}],usuarios:[{id:'v',nome:'Vendedor'}],clientes:[{id:'c',nome:'Cliente',limiteCredito:100000}],cargas:[],vendas:[],documentos:[]});
const supplier={action:'SUPPLIER_CREATE',fornecedorId:'f',unidadeId:'u',pagamento:'14 DIAS',motoristaId:'m',itens:[{produtoId:'p',qtd:800}],regraPallets:'Sem pallets',palletQuantidade:0,origem:'Arcos',destino:'Galpão',destinoTipo:'GALPÃO',modalidadeFrete:'FOB'};
let seq=0;const execute=(s,b,actor=p)=>applyWorkflow(s,{...b,requestId:b.requestId||'r'+(++seq)},actor,{id:'id'+seq,at:'2026-10-09T02:00:00Z'});
function confirmed(){let o=execute(base(),supplier),s=o.state;const id=s.comprasFornecedor[0].id;s=execute(s,{action:'OFFICIAL_CONFIRM',id,numeroPedidoFornecedor:'123',evidencia:'Pedido portal 123'}).state;return s;}
test('fornecedor só exibe produtos vinculados, nunca de outra marca',()=>assert.deepEqual(supplierProducts(base(),'f').map(p=>p.id),['p']));
test('finalidade, classificação, inatividade e revenda falsa bloqueiam compra e venda comercial',()=>{
 for(const patch of [{finalidade:'USO E CONSUMO'},{purpose:'IMOBILIZADO'},{classificacao:'USO E CONSUMO'},{destinacao:'IMOBILIZADO'},{ativo:false},{revenda:false}]){
  const s=base();Object.assign(s.produtos[0],patch);assert.equal(isResaleProduct(s.produtos[0]),false);assert.deepEqual(supplierProducts(s,'f'),[]);assert.throws(()=>execute(s,supplier),/não vinculado/);assert.throws(()=>execute(s,sale),/não classificado|inativo/);
 }
 assert.equal(isResaleProduct(null),false);assert.equal(isResaleProduct({nome:'Cimento'}),true);
});
test('rascunho cria dossiê sem afirmar envio; retorno oficial reutiliza uma linha única',()=>{let s=execute(base(),supplier).state;assert.equal(s.cargas.length,1);assert.match(s.comprasFornecedor[0].status,/NÃO ENVIADO/);const b={action:'OFFICIAL_CONFIRM',id:s.comprasFornecedor[0].id,numeroPedidoFornecedor:'123',evidencia:'PDF'};s=execute(s,b).state;const loadId=s.cargas[0].id;s=execute(s,b).state;assert.equal(s.cargas.length,1);assert.equal(s.cargas[0].id,loadId);});
test('reenvio idempotente retorna mesmo resultado, mas reutilização com payload diferente bloqueia',()=>{const b={...supplier,requestId:'retry'};const out=execute(base(),b);const again=execute(out.state,b);assert(again.replayed);assert.equal(again.state.comprasFornecedor.length,1);assert.throws(()=>execute(out.state,{...b,destino:'Outro'}),/outra operação/);});
test('produto incompatível, excesso de peso e custo alterado sem permissão bloqueiam',()=>{assert.throws(()=>execute(base(),{...supplier,itens:[{produtoId:'q',qtd:1}]}),/não vinculado/);assert.throws(()=>execute(base(),{...supplier,itens:[{produtoId:'p',qtd:801}]}),/capacidade/);assert.throws(()=>execute(base(),{...supplier,itens:[{produtoId:'p',qtd:800,custoUnitario:23}]},{...p,perfil:'VENDEDOR_INTERNO'}),/Preço negociado mudou/);});
test('rascunho permite solicitar pallets; ordem exige autorização do fornecedor',()=>{let s=execute(base(),{...supplier,regraPallets:'Solicitar pallets com liberação do vendedor'},{...p,perfil:'VENDEDOR_INTERNO'}).state;const o=s.comprasFornecedor[0],c=s.cargas[0];assert.equal(o.liberacaoPalletsFornecedor,null);s=execute(s,{action:'OFFICIAL_CONFIRM',id:o.id,numeroPedidoFornecedor:'123',evidencia:'PDF'}).state;const b={...supplier,action:'LOADING_SAVE',cargaId:c.id,numeroPedidoFornecedor:'123',dataCarregamento:'2026-10-10',evidencia:'PDF'};assert.throws(()=>execute(s,b),/liberação/);assert.throws(()=>execute(s,{action:'PALLETS_RELEASE',cargaId:c.id,evidencia:'Fornecedor autorizou'},{...p,perfil:'VENDEDOR_INTERNO'}),/permissão/);s=execute(s,{action:'PALLETS_RELEASE',cargaId:c.id,evidencia:'Fornecedor autorizou em mensagem 123'}).state;s=execute(s,b).state;assert(s.cargas[0].ordemRevisadaEm);});
test('mesmo número oficial de outro pedido não duplica carga',()=>{let s=confirmed();s=execute(s,supplier).state;assert.throws(()=>execute(s,{action:'OFFICIAL_CONFIRM',id:s.comprasFornecedor[1].id,numeroPedidoFornecedor:'123',evidencia:'PDF'}),/outra carga/);});
test('envio exige arquivo comprovante e cria imediatamente o dossiê; nova confirmação reutiliza linha',()=>{let s=execute(base(),supplier).state;const id=s.comprasFornecedor[0].id;assert.throws(()=>execute(s,{action:'SUPPLIER_RECEIPT',id,canal:'WHATSAPP',destinatario:'55'}),/comprovante/);s.documentos=[{id:'d',compraFornecedorId:id,categoria:'COMPROVANTE ENVIO FORNECEDOR'}];s=execute(s,{action:'SUPPLIER_RECEIPT',id,canal:'WHATSAPP',destinatario:'55',documentoId:'d'}).state;assert.equal(s.cargas.length,1);const load=s.cargas[0].id;s=execute(s,{action:'OFFICIAL_CONFIRM',id,numeroPedidoFornecedor:'123',evidencia:'PDF'}).state;assert.equal(s.cargas[0].id,load);assert.equal(s.documentos[0].cargaId,load);});
const sale={action:'SALE_CREATE',clienteId:'c',vendedorId:'v',itens:[{produtoId:'p',marca:'CSN',qtd:800,precoUnitario:34}],formaPagamento:'PIX',condicaoPagamento:'À VISTA',destino:'Obra',fretePorTon:140};
test('venda interna nasce aprovada, frete por tonelada só é cobrado quando não incluso',()=>{let s=execute(base(),sale).state;assert.equal(s.vendas[0].status,'APROVADO');assert.equal(s.vendas[0].freteValor,5600);assert.equal(s.vendas[0].totalGeral,32800);s=execute(base(),{...sale,freteIncluso:true}).state;assert.equal(s.vendas[0].totalGeral,27200);assert.equal(s.boletosClientes,undefined);});
test('preço zero, marca errada e crédito insuficiente bloqueiam',()=>{assert.throws(()=>execute(base(),{...sale,itens:[{...sale.itens[0],precoUnitario:0}]}),/preço/);assert.throws(()=>execute(base(),{...sale,itens:[{...sale.itens[0],marca:'CIPLAN'}]}),/marca/);const s=base();s.clientes[0].limiteCredito=100;assert.throws(()=>execute(s,{...sale,formaPagamento:'BOLETO'}),/crédito/);});
test('pedido manual externo cria só uma carga, revisões da ordem reutilizam mesma linha',()=>{const b={...supplier,action:'LOADING_SAVE',numeroPedidoFornecedor:'789',dataCarregamento:'2026-10-09',evidencia:'Portal 789',fretePorTon:140};let s=execute(base(),b).state;assert.equal(s.cargas.length,1);assert.equal(s.cargas[0].freteValor,5600);const id=s.cargas[0].id;s=execute(s,{...b,cargaId:id}).state;assert.equal(s.cargas.length,1);assert.equal(s.cargas[0].id,id);assert(!s.cargas[0].ordemMotoristaEnviada);});
test('vínculo da venda controla quantidades por produto e recusa outra carga',()=>{let s=confirmed();s=execute(s,sale).state;const c=s.cargas[0].id,v=s.vendas[0].grupoPedidoId;s=execute(s,{action:'SALE_LINK',cargaId:c,vendaId:v}).state;assert.equal(s.cargas[0].vendaIds.length,1);s=execute(s,{...sale,itens:[{...sale.itens[0],qtd:1}]}).state;assert.throws(()=>execute(s,{action:'SALE_LINK',cargaId:c,vendaId:s.vendas.at(-1).grupoPedidoId}),/maior/);});
test('recebido não é validado; carga FOB não finaliza sem comprovante de frete',()=>{const s=confirmed(),c=s.cargas[0];s.documentos=[{id:'doc',cargaId:c.id,categoria:'COMPROVANTE FRETE',validationStatus:'RECEBIDO'}];assert.equal(documentStatus(s,c,'COMPROVANTE FRETE'),'RECEBIDO — CONFERIR');c.ordemMotoristaEnviada=true;assert.throws(()=>execute(s,{action:'LOAD_FINALIZE',cargaId:c.id}),/Documentos pendentes/);});
test('entrega exige finalização real e cobrança real, não fila de boleto',()=>{let s=confirmed();s=execute(s,{...sale,formaPagamento:'BOLETO'}).state;const c=s.cargas[0];s=execute(s,{action:'SALE_LINK',cargaId:c.id,vendaId:s.vendas[0].grupoPedidoId}).state;const cc=s.cargas[0];cc.ordemMotoristaEnviada=true;cc.destinoTipo='VENDA DIRETA';cc.nfPalletsAplica=false;s.documentos=['XML NF','PDF NF','BOLETO FORNECEDOR','COMPROVANTE FRETE','COMPROVANTE ENTREGA'].map((t,index)=>({id:'d'+index,cargaId:c.id,categoria:t,validationStatus:'VALIDADO'}));s.boletosClientes=[{id:'b',vendaId:s.vendas[0].id,status:'AGUARDANDO EMISSÃO API'}];s=execute(s,{action:'LOAD_FINALIZE',cargaId:c.id}).state;assert.equal(s.vendas[0].status,'APROVADO');s.boletosClientes[0].nossoNumero='real';s.boletosClientes[0].status='EMITIDO';s.boletosClientes[0].valor=s.vendas[0].totalGeral;s=execute(s,{action:'DOCUMENT_VALIDATE',cargaId:c.id,documentoId:'d0',evidencia:'XML 123'}).state;assert.equal(s.vendas[0].status,'ENTREGUE');assert.equal(s.estoqueMov,undefined);});
test('perfil motorista, cadastro pendente e senha temporária não operam',()=>{for(const patch of [{perfil:'MOTORISTA'},{status_aprovacao:'PENDENTE'},{trocar_senha:true}])assert.throws(()=>execute(base(),supplier,{...p,...patch}),/aprovado/);});
test('arquivo de outra empresa não entra no dossiê',()=>assert.throws(()=>execute(confirmed(),{action:'DOCUMENT_ADD',cargaId:confirmed().cargas[0].id,categoria:'XML NF',path:'outra/file.xml',hash:'a'.repeat(64),filename:'NF.xml'}),/não localizada|outra empresa/));

test('pallets usam quantidade cadastrada, arredondam automaticamente e ignoram valor manual',()=>{const s=execute(base(),{...supplier,regraPallets:'Com pallets',palletQuantidade:999,itens:[{produtoId:'p',qtd:101}]}).state;assert.equal(s.comprasFornecedor[0].palletQuantidade,3);assert.equal(s.comprasFornecedor[0].nfPalletsAplica,true);const missing=base();delete missing.produtos[0].palletQtd;assert.throws(()=>execute(missing,{...supplier,regraPallets:'Com pallets'}),/quantidade por pallet/);});
test('custo vem exclusivamente do produto e falta de preço negociado bloqueia inclusive administrador',()=>{const s=base();s.produtos[0].precoNegociado=25;assert.equal(execute(s,supplier).state.comprasFornecedor[0].itens[0].custoUnitario,25);delete s.produtos[0].precoNegociado;assert.throws(()=>execute(s,supplier),/preço negociado/);assert.throws(()=>execute(base(),{...supplier,itens:[{produtoId:'p',qtd:800,custoUnitario:1}]}),/Preço negociado mudou/);});

import {filterOrders,driverSnapshot,mayReadDriverPayment} from '../supabase/functions/orders-workflow/complements.mjs';
test('CSN Direto e Fibra usam preços próprios sem substituição por preço padrão',()=>{const s=base();Object.assign(s.produtos[0],{precoNegociadoCsnDireto:21,precoNegociadoCsnFibra:24});for(const [mode,cost] of [['PADRAO',22],['CSN_DIRETO',21],['CSN_FIBRA',24]])assert.equal(execute(s,{...supplier,modalidadeCompra:mode}).state.comprasFornecedor[0].itens[0].custoUnitario,cost);delete s.produtos[0].precoNegociadoCsnFibra;assert.throws(()=>execute(s,{...supplier,modalidadeCompra:'CSN_FIBRA'}),/preço negociado/);assert.throws(()=>execute(s,{...supplier,modalidadeCompra:'INVALIDO'}),/inválida/);assert.throws(()=>execute(s,{...supplier,fornecedorId:'g',modalidadeCompra:'CSN_DIRETO',itens:[{produtoId:'q',qtd:10}]}),/somente para CSN/);});
test('800 sacos de 50 kg calculam 20 pallets de 40; 801 e valores inválidos bloqueiam',()=>{const s=base();s.produtos[0].palletQtd=40;const o=execute(s,{...supplier,regraPallets:'Com pallets'}).state.comprasFornecedor[0];assert.equal(o.pesoKg,40000);assert.equal(o.palletQuantidade,20);for(const qtd of [801,'abc',NaN,Infinity,0,-1,1.1])assert.throws(()=>execute(s,{...supplier,itens:[{produtoId:'p',qtd}]}));});
test('ajuste manual de pallets exige justificativa e preserva sugestão',()=>{assert.throws(()=>execute(base(),{...supplier,regraPallets:'Com pallets',palletQuantidadeAjustada:20}),/justificativa/);const o=execute(base(),{...supplier,regraPallets:'Com pallets',palletQuantidadeAjustada:20,justificativaPallets:'Fornecedor exige embalagens adicionais'}).state.comprasFornecedor[0];assert.equal(o.palletQuantidade,20);assert.equal(o.palletQuantidadeSugerida,16);assert.throws(()=>execute(base(),{...supplier,palletQuantidadeAjustada:1,justificativaPallets:'x'}),/quantidade zero/);});
test('edição conserva pedido e dossiê, guarda histórico e invalida envio pendente',()=>{let s=execute(base(),supplier).state;const o=s.comprasFornecedor[0],c=s.cargas[0];s.comunicacoes=[{id:'queue',compraFornecedorId:o.id,state:'QUEUED'}];s=execute(s,{...supplier,action:'SUPPLIER_EDIT',id:o.id,motivo:'Ajuste do destino',destino:'Outra obra',itens:[{produtoId:'p',qtd:760}]}).state;assert.equal(s.comprasFornecedor.length,1);assert.equal(s.cargas.length,1);assert.equal(s.cargas[0].id,c.id);assert.equal(s.comprasFornecedor[0].numero,o.numero);assert.equal(s.comprasFornecedor[0].historico.at(-1).acao,'EDIÇÃO');assert.equal(s.comunicacoes[0].state,'CANCELLED');assert.equal(s.cargas[0].localCarregamento,'Arcos');assert.equal(s.cargas[0].qtdSemDestino,760);s.comunicacoes[0].state='SENT';assert.throws(()=>execute(s,{...supplier,action:'SUPPLIER_EDIT',id:o.id,motivo:'x'}),/não pode ser editado/);});
test('cancelamento preserva registro e auditabilidade, impede envio e novo número reutilizado',()=>{let s=execute(base(),supplier).state;const o=s.comprasFornecedor[0];s.comunicacoes=[{id:'queue',compraFornecedorId:o.id,state:'BLOCKED'}];s=execute(s,{action:'SUPPLIER_CANCEL',id:o.id,motivo:'Compra cancelada'}).state;assert.equal(s.comprasFornecedor[0].status,'CANCELADO');assert.equal(s.comprasFornecedor[0].historico.at(-1).acao,'CANCELAMENTO');assert.equal(s.cargas[0].status,'CANCELADA');assert.equal(s.comunicacoes[0].state,'CANCELLED');assert.throws(()=>execute(s,{action:'SUPPLIER_PREVIEW',id:o.id}),/não localizado/);s=execute(s,supplier).state;assert.notEqual(s.comprasFornecedor[1].numero,o.numero);});
test('snapshot de identidade preserva dados anteriores sem copiar Pix privado',()=>{const s=base();Object.assign(s.motoristas[0],{cnhNumero:'999',rntrc:'RN1',cpf:'123',chavePix:'PRIVADO'});const out=execute(s,supplier).state;out.motoristas[0].cnhNumero='OUTRO';assert.equal(out.comprasFornecedor[0].motoristaSnapshot.cnhNumero,'999');assert.equal(out.comprasFornecedor[0].motoristaSnapshot.chavePix,undefined);assert.equal(driverSnapshot(s.motoristas[0]).chavePix,undefined);assert.equal(mayReadDriverPayment({...p,perfil:'VENDEDOR_INTERNO',permissoes:{}}),false);assert.equal(mayReadDriverPayment(p),true);});
test('filtros combinados ignoram acentos e formatação da placa e CPF',()=>{const o=execute(base(),supplier).state.comprasFornecedor[0];assert.equal(filterOrders([o],{query:'ABC-1D23',status:o.status,from:'2026-10-01',to:'2026-10-10'}).length,1);assert.equal(filterOrders([o],{query:'ABC1D23',from:'2026-10-10'}).length,0);assert.equal(filterOrders([o],{query:'Címento CSN'}).length,1);});
