const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{stripTypeScriptTypes}=require('node:module');
const source=stripTypeScriptTypes(fs.readFileSync('supabase/functions/orders-workflow/index.ts','utf8')).replace(/^import .*;\n/gm,'');
const profile={user_id:'u',empresa_id:'e',perfil:'MASTER',ativo:true,status_aprovacao:'APROVADO'};
function fixture({user=true,p=profile,conflict=false}={}){let writes=0;const ctx={Response,Request,JSON,String,Error,Number,Array,Object,Uint8Array,AbortSignal,crypto:require('crypto').webcrypto,Deno:{env:{get:()=>''},serve:fn=>ctx.handler=fn},createClient:()=>({auth:{getUser:async()=>({data:{user:user?{id:'u'}:null}})},from(table){return{select(){return this},eq(){return this},async single(){return {data:table==='fc_perfis'?p:{estado:{},versao:2}}}}},async rpc(){writes++;return conflict?{error:{code:'40001'}}:{data:{}}}}),applyWorkflow:(s,b,p)=>({state:{cargas:[],documentos:[]},result:{id:'saved'}})};vm.createContext(ctx);vm.runInContext(source,ctx);return{async call(body){const response=await ctx.handler(new Request('https://test/',{method:'POST',headers:{Authorization:'Bearer test'},body:JSON.stringify(body)}));return {status:response.status,data:await response.json()}},get writes(){return writes}};}
test('unauthenticated endpoint returns 401 without writing',async()=>{const f=fixture({user:false});assert.equal((await f.call({action:'SUPPLIER_CREATE'})).status,401);assert.equal(f.writes,0);});
test('driver or pending profiles return 403 without writing',async()=>{for(const patch of [{perfil:'MOTORISTA'},{status_aprovacao:'PENDENTE'},{perfil:'VENDEDOR_INTERNO',permissoes:{}}]){const f=fixture({p:{...profile,...patch}});assert.equal((await f.call({action:'SUPPLIER_CREATE'})).status,403);assert.equal(f.writes,0);}});
test('clients cannot forge bridge receipts or import driver approval',async()=>{for(const action of ['DRIVERS_IMPORTED','FRETE_PUBLISHED']){const f=fixture();assert.equal((await f.call({action})).status,400);assert.equal(f.writes,0);}});
test('CAS conflict gives 409 and no false success',async()=>{const f=fixture({conflict:true});const r=await f.call({action:'SUPPLIER_CREATE'});assert.equal(r.status,409);assert.equal(r.data.ok,undefined);});
test('verified operation saves via CAS rpc',async()=>{const f=fixture();assert.equal((await f.call({action:'SUPPLIER_CREATE'})).data.id,'saved');assert.equal(f.writes,1);});
