import {chromium} from '../qa/node_modules/playwright/index.mjs';
import {build} from '../qa/node_modules/esbuild/lib/main.js';
import assert from 'node:assert/strict';
import path from 'node:path';
const root=process.cwd();
const fixture={settings:{},unidades:[{id:'u',nome:'Filial',cnpj:'00'}],fornecedores:[{id:'f',nome:'CSN',condicaoPagamento:'14 DIAS'},{id:'g',nome:'CIPLAN',condicaoPagamento:'14 DIAS'}],produtos:[{id:'p',nome:'Cimento CSN 50 KG',marca:'CSN',pesoKg:50,precoTabela:34},{id:'q',nome:'Cimento Ciplan 50 KG',marca:'CIPLAN',pesoKg:50,precoTabela:35}],custosFornecedor:[{fornecedorId:'f',produtoId:'p',condicaoPagamento:'14 DIAS',custoUnitario:22}],motoristas:[{id:'m',nome:'Motorista',cpf:'123',placa1:'ABC1D23',capacidadeMaximaKg:40000}],usuarios:[{id:'v',nome:'Vendedor'}],clientes:[{id:'c',nome:'Cliente',nomeFantasia:'Loja Teste',limiteCredito:100000,endereco:'Rua da Obra'}],cargas:[],vendas:[],documentos:[]};
const source=`import React,{useState} from 'react';import {createRoot} from 'react-dom/client';import Orders from './apps/web/src/OrdersWorkspace.jsx';import {applyWorkflow} from './supabase/functions/orders-workflow/domain.mjs';const profile={user_id:'actor',empresa_id:'e',nome:'Admin',perfil:'MASTER',ativo:true,status_aprovacao:'APROVADO'};function Harness(){const [data,setData]=useState(${JSON.stringify(fixture)});return <Orders data={data} currentUser={profile} onNavigate={()=>{}} onBilling={()=>{}} onCommit={async body=>{const out=applyWorkflow(data,body,profile,{id:crypto.randomUUID(),at:new Date().toISOString()});setData(out.state);window.fixtureState=out.state;return out.result;}}/>;}createRoot(document.getElementById('root')).render(<Harness/>);`;
const result=await build({stdin:{contents:source,resolveDir:root,sourcefile:'browser-harness.jsx',loader:'jsx'},bundle:true,jsx:'automatic',write:false,format:'iife',outfile:'harness.js',plugins:[{name:'mock-supabase',setup(b){b.onResolve({filter:/^\.\/supabase$/},()=>({path:'mock',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:'export const supabase=null;export const getAuthContext=()=>null;'}));}}]});
const js=result.outputFiles.find(f=>f.path.endsWith('.js')).text,css=result.outputFiles.find(f=>f.path.endsWith('.css')).text;
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox']});
for(const size of [{width:390,height:844},{width:1440,height:1000}]){
 const page=await browser.newPage({viewport:size});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://fixture.test/**',route=>route.fulfill({contentType:'text/html',body:'<html lang="pt-BR"><head><meta name="viewport" content="width=device-width"></head><body><div id="root"></div></body></html>'}));await page.goto('https://fixture.test');await page.addStyleTag({content:css});await page.addScriptTag({content:js});
 await page.getByRole('combobox',{name:'Unidade compradora',exact:true}).selectOption('u');await page.getByRole('combobox',{name:'Fornecedor',exact:true}).selectOption('f');assert.deepEqual(await page.getByRole('combobox',{name:'Produto 1',exact:true}).locator('option').allTextContents(),['Selecione...','Cimento CSN 50 KG']);
 await page.getByRole('combobox',{name:'Produto 1',exact:true}).selectOption('p');assert.equal(await page.getByLabel('Custo unitário 1',{exact:true}).inputValue(),'22');await page.getByLabel('Quantidade 1',{exact:true}).fill('800');await page.getByRole('combobox',{name:'Motorista, CPF ou placa',exact:true}).selectOption('m');await page.getByLabel('Expedição / origem',{exact:true}).fill('Arcos');await page.getByLabel('Destino',{exact:true}).fill('Galpão');await page.getByRole('button',{name:'Gravar pedido',exact:true}).click();await page.getByRole('status').filter({hasText:'Gravação confirmada'}).waitFor();assert.equal(await page.evaluate(()=>window.fixtureState.comprasFornecedor.length),1);assert.equal(await page.evaluate(()=>window.fixtureState.cargas.length),0);
 await page.getByRole('button',{name:'Pedido de Venda',exact:true}).click();await page.getByRole('combobox',{name:'Cliente, fantasia ou CPF/CNPJ',exact:true}).selectOption('c');await page.getByRole('combobox',{name:'Vendedor',exact:true}).selectOption('v');await page.getByRole('combobox',{name:'Marca 1',exact:true}).selectOption('CSN');await page.getByRole('combobox',{name:'Produto 1',exact:true}).selectOption('p');await page.getByLabel('Quantidade 1',{exact:true}).fill('10');await page.getByRole('combobox',{name:'Forma de recebimento',exact:true}).selectOption('PIX');await page.getByLabel('Condição / prazo do cliente',{exact:true}).fill('À VISTA');await page.getByRole('button',{name:'Registrar venda aprovada',exact:true}).click();await page.getByRole('status').filter({hasText:'Gravação confirmada'}).waitFor();assert.equal(await page.evaluate(()=>window.fixtureState.vendas[0].status),'APROVADO');
 await page.getByRole('button',{name:'Ordem de Carregamento',exact:true}).click();assert.equal(await page.locator('fieldset input').first().getAttribute('aria-label'),'1. Número oficial do pedido do fornecedor');await page.getByLabel('1. Número oficial do pedido do fornecedor',{exact:true}).fill('P-123');await page.getByRole('combobox',{name:'Fornecedor do pedido',exact:true}).selectOption('f');await page.getByRole('button',{name:'Buscar pedido confirmado',exact:true}).click();await page.getByRole('alert').filter({hasText:'Não foi possível encontrar'}).waitFor();assert.equal(await page.evaluate(()=>window.fixtureState.cargas.length),0);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'horizontal overflow');assert.deepEqual(errors,[]);console.log('PASS: independent supplier/sale/order tabs, real filtered fixture catalogs, approved sale, no invented matching, no overflow: '+size.width);
 await page.close();
}
await browser.close();
